department-of-veterans-affairs/diffusion-marketplace

app/controllers/admin_controller.rb, app/controllers/users_controller.rb, app/mailers/admin_mailer.rb, app/models/user.rb, app/views/admin_mailer/send_set_password.html.erb, app/views/users/index.html.erb, config/environments/test.rb, config/routes.rb, spec/features/user_admin_spec.rb
Adding in user creation for admins.
=> Dm 150 pt.2

app/controllers/admin_controller.rb, app/controllers/users_controller.rb, app/views/layouts/application.html.erb, app/views/shared/_messages.erb, app/views/users/index.html.erb, spec/features/user_admin_spec.rb
[DM-197](https://agile6.atlassian.net/secure/RapidBoard.jspa?rapidView=22&projectKey=DM3&modal=detail&selectedIssue=DM-197)
=> Add flash messages to admin user management

lib/tasks/dm.rake
[DM-325](https://agile6.atlassian.net/browse/DM-325)
This expects a CSV file with the path: `/tmp/practices_dummy_data.csv`
Dummy data CSV is attached in the Jira issue linked above.
The headings should be:
| project_name  | start_date  | business_office_sponsor  | purpose  | approach  |
|---|---|---|---|---|
|   |   |   |   |   |
=> Import dummy data

Gemfile, spec/spec_helper.rb
n/a
removes capybara webkit from our stack
n/a
n/a
n/a
=> DM-000: remove capybara-webkit

app/assets/javascripts/next-steps.js, app/controllers/practices_controller.rb, app/helpers/application_helper.rb, app/views/practices/next_steps.html.erb, app/views/practices/show.html.erb, config/routes.rb, db/seeds.rb, spec/features/practice_spec.rb
https://agile6.atlassian.net/browse/DM-387
- adds the "Next Steps" page for a practice
pre-req: have practice data
you can run `rails dm:reset_up` to get the data
1. go to a practice page
2. click on either "Next Steps" links on the page
3. click on checkboxes on the check list 😄 
4. click on "Print Checklist" button, make sure print window comes up
5. click on "Email Summary", make sure email link works
6. click on "Email Checklist", make sure email link works
https://www.figma.com/file/DDUSxYiD1MaWNrGFmMjY8d8a/Diffusion-Marketplace-Designs?node-id=4%3A562
=> DM-387: [App] Develop Next Steps and Checklist

app/views/practices/next_steps.html.erb, app/views/practices/show.html.erb
https://agile6.atlassian.net/browse/DM-541
- adds breadcrumbs at the top of the "Next Steps" page
- view the Next Steps page
=> DM-387: [DM-541] add breadcrumbs and missing Next Steps link

app/views/layouts/application.html.erb
https://agile6.atlassian.net/browse/DM-563
+ Adds "Full Story" integration to the application (https://fullstory.com)
n/a - on prod
n/a
=> DM-563: full story ui recording integration

Gemfile, app/views/practices/_timeline_and_checklist.html.erb, spec/spec_helper.rb
n/a
+ fixes an issue with long, run-on strings in the timeline graphic
=> DM-000: [practice show page] word break fix on timeline graphic

app/assets/javascripts/_marketplace-search-form.js, app/assets/javascripts/_search.js, app/assets/stylesheets/dm/_classes.scss, app/assets/stylesheets/dm/components/_marketplace-cards.scss, app/assets/stylesheets/dm/components/_search_bar.scss, app/assets/stylesheets/dm/pages/_search.scss, app/assets/stylesheets/dm_uswds/theme/_uswds-theme-custom-styles.scss, app/controllers/practices_controller.rb, app/views/home/index.html.erb, app/views/practices/_marketplace_card.html.erb, app/views/practices/index.html.erb, app/views/practices/search.html.erb, app/views/shared/_header.html.erb, config/routes.rb, spec/features/practice_spec.rb, spec/features/search_spec.rb
https://agile6.atlassian.net/browse/DM-516
DM-516: [DM-588] style marketplace page
DM-516: [DM-589] implement search bar in marketplace page 
+ search page styling updates
+ marketplace route
1. make sure you have data
2. browse to /marketplace
3. shop around
4. click on practice images, links, etc. to go a practice page
5. use the search bar 
6. make sure the search page looks good
https://www.figma.com/file/DDUSxYiD1MaWNrGFmMjY8d8a/Diffusion-Marketplace-Designs?node-id=10%3A2314
Implement three practices per row.
Search bar at the top of the page
Implement new subhead: "Search by...."
All practices are displayed
Practices are arranged alphabetically
Search starts when user hits “Search”
=> DM-516: [App] Implement New Marketplace Page  

Gemfile, Gemfile.lock, app/assets/stylesheets/dm/_classes.scss, app/views/home/index.html.erb, app/views/practices/_marketplace_card.html.erb
https://agile6.atlassian.net/browse/DM-598
Fixes the headings on the main page.
Heading levels are nested properly and no heading levels are skipped
Tested using Web Developer Extension -> Information -> View Document outline
~~- [ ] Unit tests written (if applicable)~~
~~- [ ] e2e/accessibility tests written (if applicable)~~
~~- [ ] Events are logged appropriately~~
~~- [ ] Documentation has been updated, if applicable~~
=> Properly nest headings on homepage

app/assets/stylesheets/dm/pages/_search.scss, app/assets/stylesheets/dm_uswds/theme/_uswds-theme-custom-styles.scss, app/views/practice_partners/index.html.erb, app/views/practice_partners/show.html.erb, app/views/shared/_header.html.erb, spec/features/practice_partners_spec.rb
https://agile6.atlassian.net/browse/DM-601
+ updates the practice partners page to the new layout and designs
Pre: have data
1. browse to /practice_partners
2. click on a practice partner
https://www.figma.com/file/DDUSxYiD1MaWNrGFmMjY8d8a/Diffusion-Marketplace-Designs?node-id=358%3A5276
=> DM-601: [Design][App] Update Practice PARTNERS Page

app/assets/stylesheets/dm_uswds/theme/_uswds-theme-custom-styles.scss, app/views/home/index.html.erb, app/views/shared/_beta_banner.html.erb, app/views/shared/_header.html.erb, spec/features/landing_page_spec.rb, spec/features/practice_spec.rb
https://agile6.atlassian.net/browse/DM-610
+ add verbiage to landing page
+ add beta banner
1. run the app
2. look at the home page
https://www.figma.com/file/DDUSxYiD1MaWNrGFmMjY8d8a/Diffusion-Marketplace-Designs?node-id=396%3A168
=> DM-610: [DM-663, DM-665] add banner and landingpage verbiage

app/models/user.rb, db/migrate/20190123205910_devise_create_users.rb, db/schema.rb
https://agile6.atlassian.net/browse/DM-550
+ add user sign in tracking via devise
1. run `rails dm:reset_up` to get the new user schema
2. sign in the application as a user
3. run `rails console` and check the user's `sign_in_count` property. make sure it incremented
n/a
=> DM-550: track user sign ins

app/views/home/index.html.erb, app/views/practices/_marketplace_card.html.erb, app/views/practices/show.html.erb
https://agile6.atlassian.net/browse/DM-599
Fixes headings on practices page.
Adds context to learn more link
Remove image links from tab order. (they are duplicate of text links)
=> DM599: practice headings link image links

README.md, app/assets/javascripts/_search.js, app/assets/stylesheets/dm_uswds/theme/_uswds-theme-custom-styles.scss, app/models/user.rb, app/views/shared/_beta_banner.html.erb, app/views/shared/_messages.erb, config/initializers/devise.rb
+ DM-610: [DM-679] update banner verbiage
https://agile6.atlassian.net/browse/DM-676
+ adds session timeout
+ this is also configurable via:
`SESSION_REMEMBER_FOR_IN_DAYS` - how long to remember the user for if they check the "Remember me" checkbox
`SESSION_TIMEOUT_IN_MINUTES` -  without checking the checkbox, how long the user's session stays alive if they are active
a little tricky to test. will have to turn on/make the time shorter for the session timeout in `config/intializers/devise.rb`
=> DM-676: add session timeout

Gemfile, Gemfile.lock, app/admin/dashboard.rb, app/admin/departments.rb, app/admin/practice_partners.rb, app/admin/practices.rb, app/admin/users.rb, app/assets/stylesheets/active_admin.scss, app/models/admin_user.rb, app/models/practice.rb, config/initializers/active_admin.rb, config/initializers/activeadmin_addons.rb, config/routes.rb, db/migrate/20190521102110_devise_create_admin_users.rb, db/migrate/20190521102115_create_active_admin_comments.rb, db/schema.rb, db/seeds.rb
https://agile6.atlassian.net/secure/RapidBoard.jspa?rapidView=22&modal=detail&selectedIssue=DM-631
Adds the active_admin gem and some additional addons. Providing us with an admin setup for managing various models.
Lacking rspecs and capybara specs, will be adding those in the following days. In the meantime, you can manually test by navigation to `/admin` and logging in with the info `demo_admin@va.gov` & `DemoAdmin#123`
=> dm-631 Active Admin

app/assets/javascripts/_feedback_survey.js, app/assets/javascripts/_search.js, app/assets/stylesheets/dm/_classes.scss, app/assets/stylesheets/dm/components/_modal.scss, app/assets/stylesheets/dm/components/_practice_timeline.scss, app/assets/stylesheets/dm/pages/_practice.scss, app/assets/stylesheets/dm_uswds/theme/_uswds-theme-custom-styles.scss, app/assets/stylesheets/dm_uswds/theme/_uswds-theme-utilities.scss, app/views/layouts/application.html.erb, app/views/practices/_complexity.html.erb, app/views/practices/_marketplace_card.html.erb, app/views/practices/_resources_required.html.erb, app/views/practices/_support_team.html.erb, app/views/practices/_timeline_and_checklist.html.erb, app/views/practices/show.html.erb, app/views/shared/_beta_banner.html.erb, app/views/shared/_feedback_survey.html.erb, app/views/shared/_footer.html.erb, spec/features/practice_partners_spec.rb
https://agile6.atlassian.net/browse/DM-561 - report a bug
https://agile6.atlassian.net/browse/DM-627 - app bugs
https://agile6.atlassian.net/browse/DM-537 - feedback survey
+ footer updates
+ dm-561 report a bug mailto link
+ dm-696 practice timeline mobile view
+ dm-697 complexity spacing mobile view
+ dm-698 "Next Steps" button mobile view
+ dm-699 cut-off photo
+ dm-700 cut-off photo
+ dm- 701 cut-off photo
entire app feedback links: "Give us feedback" and "click here" in the banner
=> DM-537: add feedback survey

app/views/practices/_resources_required.html.erb
https://agile6.atlassian.net/browse/DM-599
Adds screen reader only descriptive text for complexity circles
=> Add screen reader only text for complexity circles

.circleci/config.yml, Gemfile, Gemfile.lock
n/a
+ add brakeman security scan to our CI
=> DM-SECURITY: add brakeman security scanner gem

app/controllers/practice_partners_controller.rb, app/controllers/practices_controller.rb, app/views/practice_partners/index.html.erb, app/views/practices/_complexity.html.erb, app/views/practices/_risks_and_mitigations.html.erb, db/seeds.rb, spec/features/practice_spec.rb
https://agile6.atlassian.net/browse/DM-627
+ 750 add partner blurbs
+ 754 update partner page intro blurb
+ 758 unauthenticated user access to practices and search pages
+ 759 partners in alpha order asc
+ fix spacing between risk and mitigation lists
+ uppercase Yes and No in practice complexity section
=> DM-627: [DM-750, DM-754, DM-758, DM-759]

app/admin/users.rb, db/seeds.rb, lib/tasks/importer.rake
https://agile6.atlassian.net/browse/DM-834?atlOrigin=eyJpIjoiMzE5ODE0N2VjMTEwNGJmMmI5NzZlYmE5NWM5MmM3M2IiLCJwIjoiaiJ9
Adds `Skip va validation` option to new user on admin panel
Navigate to admin panel,
create new user
create user with non va email
select skip va validation
=> DM-834: Add "Skip VA" option to new user creation on admin panel

app/assets/stylesheets/dm/_classes.scss, app/assets/stylesheets/dm/variables/_colors.scss, app/views/users/edit_profile.html.erb
https://agile6.atlassian.net/browse/DM-972
=> Update font color, move upload under edit button

config/ldap.yml
https://agile6.atlassian.net/browse/DM-857
adds production environment ldap config
=> DM-857: production environment ldap config

app/assets/javascripts/ie.es6
https://agile6.atlassian.net/browse/DM-857
Removes FireFox as a supported/recommended browser 
IE11
=> DM-857: remove FireFox as supported browser in browse happy message

proxy/nginx.conf
=> update nginx file upload size to 1GB

config/environments/production.rb
https://agile6.atlassian.net/browse/DM-1325
configures SMTP settings for VAEC so that VAEC servers can send emails
on staging and prod on VAEC
adpot a practice
=> [DM-1325]: configure SMTP settings for VAEC

.circleci/config.yml, .gitignore, config/puma.rb, scripts/deploy.sh
https://agile6.atlassian.net/browse/DM-1351
updates some deploy configurations to get CD back!
i have to use this to test~
http://test.marketplace.agile6.com
=> DM-1351: update configurations for deployment

app/admin/practices.rb
only confirms users if NTLM is not activated
=> DM-1470: NTLM users do no confirm their accounts

app/admin/practices.rb
this got lost in the rebase wash
=> DM-1470: auto approve practices for now when created

app/assets/javascripts/_cropper.es6, app/assets/stylesheets/commontator/comments.scss, app/assets/stylesheets/dm/pages/_practice.scss, app/assets/stylesheets/dm/variables/_colors.scss, app/controllers/practices_controller.rb, app/models/va_employee.rb, app/views/practices/_support_team.html.erb, app/views/practices/contact.html.erb, app/views/practices/overview.html.erb, spec/features/practice_editor/contact_spec.rb, spec/features/practice_editor/overview_spec.rb
[DM-1348](https://agile6.atlassian.net/secure/RapidBoard.jspa?rapidView=22&projectKey=DM&modal=detail&selectedIssue=DM-1348&quickFilter=31) -> [DM-1463](https://agile6.atlassian.net/secure/RapidBoard.jspa?rapidView=22&projectKey=DM&modal=detail&selectedIssue=DM-1463&quickFilter=31)
This PR serves as a foundation for enabling the cropper for views with multiple images. It implements the cropper on the Contact page of the Practice Editor.
- Log in as a user with the ability to edit practices
- Go to the Contact section of the Practice Editor
- Crop, delete, upload, etc the contact headshot and also make sure deleting the contact doesn't throw any errors if a user cropped that contact's photo beforehand
- Ensure the Overview cropper still works as intended (I already did this but just in …
=> DM-1348: [DM-1463] Implement cropper on contact pg

app/assets/javascripts/_cropper.es6, app/assets/stylesheets/dm/components/_profile.scss, app/controllers/practices_controller.rb, app/controllers/users_controller.rb, app/models/application_record.rb, app/models/practice_creator.rb, app/models/user.rb, app/models/va_employee.rb, app/views/practices/contact.html.erb, app/views/practices/origin.html.erb, app/views/practices/overview.html.erb, app/views/users/edit_profile.html.erb, app/views/users/show.html.erb, config/application.rb, lib/modules/cropper_utils.rb, spec/features/practice_editor/contact_spec.rb, spec/features/user_profile_spec.rb
[DM-1348](https://agile6.atlassian.net/secure/RapidBoard.jspa?rapidView=22&projectKey=DM&modal=detail&selectedIssue=DM-1348&quickFilter=31&assignee=5e4d76fe393ea90c94b41b89&assignee=UNASSIGNED_USER_ID): [[DM-1456]](https://agile6.atlassian.net/secure/RapidBoard.jspa?rapidView=22&projectKey=DM&modal=detail&selectedIssue=DM-1456&quickFilter=31&assignee=5e4d76fe393ea90c94b41b89&assignee=UNASSIGNED_USER_ID)
This PR implements the cropper on the user avatar. This PR also cleans up cropper-related functionality into its own module called `CropperUtils`.
Log in as a user
- edit your profile photo (crop, remove, upload, etc)
Log in as a user that can edit a practice
- edit your practice thumbnail, practice creator, and contact photos
[Figma](https://www.figma.com/file/DDUSxYiD1MaWNrGFmMjY8d8a/Diff …
=> DM-1348: [DM-1456] Implement cropper on user profile

app/admin/dashboard.rb, app/controllers/application_controller.rb, app/models/practice.rb
[DM-1415](https://agile6.atlassian.net/browse/DM-1415): [[DM-1596]](https://agile6.atlassian.net/browse/DM-1596)
This PR adds the metrics that @ahay-agile6 pulled into a spreadsheet regarding the following:
- total accounts
- unique visitors
- number of site visits
- total number of practices, and newly added practices
- stats on practices favorited
- stats on practice comments
- stats on practice adotpions
into its own "Metrics" tab on the admin dashboard.
1. Log in as an `admin` user
2. Go to `.../admin/dashboard`
3. Click the "Metrics" tab
4. Ensure the counts you see are consistent with the DB
5. Add a practice
6. See the practice number increase
7. Repeat steps 5-6 with favoriting, commenting, and adopting practices
Not sure how to test the unique visitors and number of site visits …
=> DM-1415: [DM-1596] Add metrics tab to admin dashboard

Gemfile, Gemfile.lock, app/admin/dashboard.rb, app/models/practice.rb, config/routes.rb, spec/features/admin_spec.rb, spec/spec_helper.rb
[DM-1415](https://agile6.atlassian.net/secure/RapidBoard.jspa?rapidView=22&projectKey=DM&modal=detail&selectedIssue=DM-1415&quickFilter=31): [[DM-1599]](https://agile6.atlassian.net/secure/RapidBoard.jspa?rapidView=22&projectKey=DM&modal=detail&selectedIssue=DM-1599&quickFilter=31)
This PR adds the ability for an admin to export the data in the "Metrics" tab as a  `.xlsx` file.
- Log in as an admin user
- Click the "Metrics" tab
- Ensure the values are as expected...
- Click "Export as .xlsx"
- A file download prompt should open
- Download the file and make sure the data is equivalent to the one seen in the "Metrics" tab
=> DM-1415: [DM-1599] Allow metrics to be exported as .xlsx

app/admin/dashboard.rb, spec/features/admin_metrics_spec.rb
[DM-1648](https://agile6.atlassian.net/browse/DM-1648)
This PR applies copy changes to an admin's metrics dashboard.
2. Go to the "Metrics" tab of the admin dashboard `.../admin`
3. Ensure that the "Last Month" column only says "Last Month" and does not include a month and year.
4. Ensure that the 4th column of metrics breakdown by practices says "Current Total"
=> DM-1648: Tweak copy on metrics dashboard

Gemfile, Gemfile.lock, app/admin/dashboard.rb, app/models/practice.rb
fixes ntlm-sso missing library issue
=> DM-1673: point to agilesix ntlm-sso

app/assets/stylesheets/dm/components/_profile.scss, app/views/practices/_practice_editor_sidenav.html.erb, app/views/practices/planning_checklist.html.erb, app/views/users/edit_profile.html.erb, app/views/users/show.html.erb, spec/features/practice_editor/instructions_spec.rb, spec/features/practice_editor/sidenav_spec.rb
[DM-1731](https://agile6.atlassian.net/browse/DM-1731)
[DM-1721](https://agile6.atlassian.net/browse/DM-1727?focusedCommentId=11314)
This PR does the following:
- removes "Save your progress" and "Publish practice" from the instructions page
- IE styling fixes and copy edit in "Practice checklist"
1. 
- Log in as a user that can edit a practice
- Go to the instructions page
- Ensure that there is no "Save your progress" and "Publish practice" buttons
2. 
- Use a machine that has IE, to check that the width of the text inputs under Edit Profile are the same as in Figma
- Check that "Share checklist" has a lowercase "c" under a practice's checklist
=> DM-1731: Fix bugs on staging

app/controllers/nominate_practices_controller.rb, app/views/nominate_practices/index.html.erb, app/views/shared/_footer.html.erb, config/routes.rb, spec/features/nominate_practices/nominate_a_practice_page_spec.rb
[DM-1698](https://agile6.atlassian.net/browse/DM-1698)
This PR creates the "Nominate a practice" page.
1. Go to `/nominate-a-practice`
2. Ensure the copy is the same as in the designs (see below for screenshot)
3. Ensure the user is able to click "Start nomination" and it is a mailto link
4. Ensure the footer now says "Nominate a practice" and redirects to the `/nominate-a-practice` page
**Design Screenshot**
**In-app Screenshot**
[https://www.figma.com/file/DDUSxYiD1MaWNrGFmMjY8d8a/Diffusion-Marketplace-Designs?node-id=1745%3A27776 ](https://www.figma.com/file/DDUSxYiD1MaWNrGFmMjY8d8a/Diffusion-Marketplace-Designs?node-id=1745%3A27776)
- [] Practice Criteria (Header):
- [] Be adopted at 2 or more locations
- [] Endorsed by senior executive stakeholder
- [] Be an active practice
- [] Have …
=> DM-1698: Create "Nominate a practice" page

app/views/shared/_header.html.erb, config/routes.rb
[DM-1692](https://agile6.atlassian.net/browse/DM-1692): [[DM-1796](https://agile6.atlassian.net/browse/DM-1796)] 
This hides the Shark Tank page.... again! 😅 
Make sure there is no shark tank page in the navigation.
=> DM-1692: [DM-1796] Hide Shark Tank page

app/controllers/practices_controller.rb, spec/features/practice_editor/risk_and_mitigation_spec.rb
https://agile6.atlassian.net/browse/DM-1797
fixes 400 error when submitting an empty form for practice editor
**this is done easiest with a new practice**
1. own a practice/be an admin
2. go to the risk & mitigation edit page
3. make sure there are no risk and mitigations on the page, not by deleting, just that it had nothing on the page at all
4. click "Continue"
5. you should get to the next page. before this, there was an error received
6. this also works on the Resource page if it is not filled out. go there and click "Continue" to make sure it works
=> DM-1797: update practices checks for practice param

app/views/maps/_home_map_marker_modal.html.erb
https://agile6.atlassian.net/browse/DM-1788
Fixes an issue with displaying diffusion history statuses.
=> DM-1788: Fixed an issue with diffusion history statuses

Gemfile.lock
https://agile6.atlassian.net/browse/DM-1863
update rack due to CVE finding
=> DM-1863: update rack gem >= 2.2.3

app/assets/javascripts/turbolinksScrollTop.es6
https://agile6.atlassian.net/browse/DM-1830
makes scroll to top on page transition smoother
browse around the site
=> DM-1830: scroll to top of page transition from turbolinks

app/admin/practices.rb
https://agile6.atlassian.net/browse/DM-1881
cleans up practice form on active admin side
- browse to /admin/practices/new
- risk and mitigation and impact photos form fields shouldn't be there
=> DM-1881: clean up aa practices form

app/assets/stylesheets/dm/pages/_partials/_header.scss, app/views/shared/_header.html.erb
Fixes position issue for the header mobile menu button and "X" icon for IE.
=> DM-1818: Fixed header menu button and X icon button issue on IE

app/admin/adoptions.rb
[DM-2024](https://agile6.atlassian.net/browse/DM-2042)
This PR adds practice ids to the downloadable adoptions spreadsheet in the admin dashboard.
1. Log in as a user with the `admin` role.
2. Go to `.../admin/adoptions`
3. Click "Download All"
4. Open the downloaded and file and make sure the practice id appears under each practice
**Before**
**After**
=> DM-2042: Add practice ids to adoptions data downloadable file

app/assets/stylesheets/dm/components/_practice_timeline.scss, app/views/practices/show/implementation/_timelines.html.erb, spec/features/practice_editor/sidenav_spec.rb
N/A
Fix timeline styles for mobile view
Check the practice page for a view that is < 600px wide
=> DM-2018: Fix timeline style

spec/features/home_map_spec.rb, spec/features/practice_map_spec.rb
This PR fixes the failing diffusion map tests so our builds pass 😬
=> Fix failing diffusion map tests

.gitignore, Gemfile, Gemfile.lock, app/assets/stylesheets/dm/_classes.scss, app/assets/stylesheets/dm/pages/_home.scss, app/assets/stylesheets/dm/variables/_colors.scss, app/controllers/home_controller.rb, app/controllers/system/status_controller.rb, app/views/home/index.html.erb, app/views/maps/diffusion_map.html.erb, app/views/shared/_header.html.erb, app/views/system/status/index.html.erb, config/routes.rb, spec/features/home_map_spec.rb, spec/features/shared/header_spec.rb
This PR merges what is currently on master into the feature branch
=> Merge master

app/helpers/application_helper.rb, app/services/save_practice_service.rb, app/views/practices/form/implementation.html.erb, app/views/practices/show/introduction/_introduction.html.erb, spec/features/practice_editor/implementation/practice_resources_spec.rb
https://agile6.atlassian.net/browse/DM-2109
1.  Updated text in PE implementation page for Core and Optional attachments.
2.  Added department to Practice Origin in the Practice Show View.
3.  Prevent user from adding same department multiple times in the PE implementation page.
Issues #1 and #2 above can be verified by viewing the Practice Editor->Implementation page and the Practice Show view.
for #3 
1.  Login and select a practice.
2.  Go to the Practice Editor pages for Practice.
3.  Navigate to the Implementation page and scroll down to the "Departments" section.
4.  Add a department and click save.
5.  Select "Add another" and select the same department that you selected in step #4 
=> Expected Result: Second record is not saved in the DB.
6.  Add and save as many unique …
=> Practice resources fix

app/admin/adoptions.rb, app/admin/practices.rb, app/assets/stylesheets/active_admin.scss, app/helpers/active_admin_helpers.rb, lib/tasks/postgres.rake, spec/features/admin_adoptions_spec.rb
Merge master branch into `feature/new-practice-page` via temp branch
=> Temp feature branch

app/assets/javascripts/diffusion_history/practice_map.es6, app/helpers/practices_helper.rb, app/views/practices/form/implementation.html.erb, app/views/practices/implementation_forms/_resources.html.erb, spec/features/practice_editor/implementation/practice_resources_spec.rb
N/A
This PR fixes the copy for the resources section of the PE Implementation page and also merges the current `master` into the feature branch.
Ensure the copy on the PE Implementation resources section has copy that matches [this doc](https://docs.google.com/document/d/12FMO7do1BVXs3nfpsY_B2ynnp53R2BBBn1DPgHPQwl4/edit#heading=h.1thmo5v68gix).
**Core**
**Optional**
**Support**
N/A
=> Merge master and fix copy

app/mailers/covid_category_mailer.rb
Attempt to fix weird rendering issue regarding the subject text for Mac mail.
=> Trying to fix weird rendering of subject line on Mac mail app

app/views/practices/show/authenticated/_show_authenticated.html.erb
[DM-2237](https://agile6.atlassian.net/browse/DM-2237)
This PR adds a subject of "Question about PRACTICE_NAME" to the email when a user clicks "Email practice".
1. Log in as a user.
2. Go to a practice's show page.
3. Click "Email practice"
4. An email should open with a subject of "Question about PRACTICE_NAME"
=> DM-2237: Add subject to mailto for "Email Practice" btn

app/services/save_practice_service.rb
=> Downcase email for practice editors

app/admin/dashboard.rb, app/assets/stylesheets/dm/components/_modal.scss, app/assets/stylesheets/dm/pages/_home.scss, app/assets/stylesheets/dm/pages/_partials/_header.scss, app/assets/stylesheets/dm/pages/_partials/_navbar_search.scss, app/assets/stylesheets/dm/pages/_practice.scss, app/assets/stylesheets/dm/variables/_colors.scss, app/controllers/application_controller.rb, app/views/layouts/_ahoy_event_tracking.js.erb, app/views/shared/_header.html.erb, app/views/shared/_navbar_search.html.erb, spec/features/shared/header_spec.rb
[DM-2397](https://agile6.atlassian.net/browse/DM-2397)
This PR accomplishes the following:
- updates the header to use 2 rows (desktop and mobile version)
- tracks custom page subpage visits
- adds Shark Tank back to navigation link and removes Covid-19 navigation link
**Updated Header -- Desktop**
1. Log in as a user and make sure your window is greater than or equal to 1024px (desktop view)
2. Make sure the header is according to the [Figma designs](https://www.figma.com/file/fNXjZzLUS39bKmjdfDWyxy/My-VISN-VAMC?node-id=1%3A171) (minus the notification bell and Directories submenu)
3. Make sure clicking on the logo goes to the homepage
4. Make sure you can Log in, access your profile, and sign out
5. Make sure you can go to the shark tank page and diffusion map
6. Make sure when you go …
=> DM-2397: Update header and track custom page subpage visits

Gemfile.lock
update to 0.3.6
https://github.com/rails/rails/issues/41750
Updates magicmime gem to 0.3.6
1.  Log in as admin and navigate to a practice page.
2. Ensure that you can still add resources/images to the practice.
=> dm-mimemagic

.circleci/config.yml
[DM-2520](https://agile6.atlassian.net/browse/DM-2520)
We want to manually run the `test` CircleCI job in order to save credits.
=> DM-2520: Manually trigger test job in circleci

app/assets/javascripts/diffusion_history/_map_utilities.es6, spec/features/practice_viewer/contact_spec.rb, spec/features/practice_viewer/introduction_spec.rb, spec/features/practice_viewer/practice_map_spec.rb, spec/features/shared/header_spec.rb, spec/features/users/recommended_for_you_spec.rb
[DM-2527](https://agile6.atlassian.net/browse/DM-2372)
First pass at fixing tests that fail often in CI.
LOOK AT ALL THIS BEAUTIFUL GREEN
https://app.circleci.com/pipelines/github/agilesix/diffusion-marketplace?branch=elisa%2Ffix-tests
=> DM-2527: Fix tests

app/helpers/navigation_helper.rb
=> Fix facilities show breadcrumbs

app/controllers/visns_controller.rb, app/helpers/visns_helper.rb, app/models/va_facility.rb, app/models/visn.rb, app/views/visns/_visn_metadata_list.html.erb, app/views/visns/show.html.erb, lib/modules/practice_utils.rb
[DM-2585](https://agile6.atlassian.net/browse/DM-2585)
This PR will reduce load times on the VISN index page by reducing duplicate ActiveRecord queries
1. Make sure the VISN index and show counts are the same on `master` as well as on this branch.
2. Make sure you can still search by diffusion history facility and origin facility on the search and VISN show page
3. Take note of how long the VISN index page takes to load on `master` and take note how long it takes to load on this  branch
4. Take note of how long the same VISN show page takes to load on `master` and take note how long it takes to load on this branch (not a big difference... we may need to take a different approach here)
**VISN index**
`master`
`dm-2585`
**VISN show page**
`master`
`dm-2585`
=> DM-2585: Reduce load times on visn index page

app/views/practices/form/introduction.html.erb, spec/features/practice_editor/introduction/introduction_spec.rb
[DM-2630](https://agile6.atlassian.net/browse/DM-2630)
Updates the copy for the categories section of the practice editor
Go to the introduction section of a practice's practice editor
Check that the copy has been updated as follows:
=> DM-2630: Update categories PE copy

app/assets/javascripts/va_facilities/facility_adopted_practice_search.es6, app/assets/javascripts/visns/maps.es6, app/views/va_facilities/_facility_practice_adoptions.html.erb, app/views/visns/_search.html.erb, app/views/visns/_show.js.erb, app/views/visns/_visn_facilities_table.html.erb, app/views/visns/show.html.erb
[DM-2736](https://agile6.atlassian.net/browse/DM-2736)
Fixes loading spinner bugs. See below how to repro.
**VISN show**
1. Click between "Practices created in this VISN" and a "Practices adopted in this VISN"
There should be no loading spinner that appears and never goes away.
**Facilities show**
1. Search for a practices in the "Practices adopted at this facility" where there are no results
2. You should see a no results messaging and icon appear
3. The no results messaging should disappear when there are results
=> DM-2624 [DM-2736]: Fix spinners on VISN show

proxy/Dockerfile
Added code to switch to nginx user
=> Added code to switch to nginx user

app/assets/javascripts/showMoreItems.js, app/assets/stylesheets/dm/components/_practice_card.scss, app/assets/stylesheets/dm/pages/_explore.scss, app/assets/stylesheets/dm/pages/_facilities.scss, app/assets/stylesheets/dm/pages/_home.scss, app/assets/stylesheets/dm/pages/_search.scss, app/views/home/index.html.erb, app/views/page/show.html.erb, app/views/practice_partners/show.html.erb, app/views/practices/_search.js.erb, app/views/practices/explore.html.erb, app/views/practices/search.html.erb, app/views/shared/_practice_card.html.erb, app/views/users/show.html.erb, app/views/va_facilities/_facility_created_practice_search.html.erb, app/views/visns/_visn_card.erb
[DM-2825](https://agile6.atlassian.net/browse/DM-2825)
Fixes the following:
- /explore - Load more button is clickable on mobile view
- practice cards and bookmark practice button look good on every page and is mobile friendly
- featured practice, page builder practice card list, visn show search, facilities show search, explore, search, partners page, profile created practices and profile bookmarked practices
- /visns - visn cards are mobile friendly
- “Return to top” link isn’t colliding with other elements on the following pages: /search, /partners, /explore, page builder show page, profile page
Check the above as a logged in and logged out user
=> DM-2825: Fix styling issues

app/views/shared/_footer.html.erb, spec/features/shared/footer_spec.rb
https://agile6.atlassian.net/browse/DM-2849
This change removes "Nominate a practice" from the DM footer and adds "Privacy policy" link (https://www.va.gov/privacy-policy) to footer.  Link to va.gov privacy policy opens in a new tab.
1,  Login in to DM.
2,  Scroll down to the footer.  You will see the "Privacy policy" link in the footer.  
3.  Click on the link.  VA.gov privacy will display in new tab.
4.  Note: the "Nominate a practice" footer link is removed.
N/A
- Add "Privacy Policy" to footer
- Have it link to https://www.va.gov/privacy-policy/
- Check with Becca on which order it should go in
- [X ] Unit tests written (if applicable)
- [X ] Documentation has been updated, if applicable
- [X ] A link has been provided to the originating JIRA issue
- [X ] No sensitive information …
=> dm-2849 - Privacy Policy link in footer

README.md, app/controllers/va_facilities_controller.rb, app/helpers/visns_helper.rb, app/models/va_facility.rb, app/views/va_facilities/_index_table_row.html.erb, db/migrate/20210903160740_add_hidden_to_va_facilities.rb, db/schema.rb, lib/tasks/dm.rake, lib/tasks/va_facilities.rake, spec/features/admin/admin_spec.rb, spec/features/visn_spec.rb
https://agile6.atlassian.net/browse/DM-2820
This code updates the local va_facilities table with the latest and greatest facility information provided from the VAST data set.  This data set also includes VA Vet Center facilities which will be added to the table but marked as hidden for now.   Facilities provided in the VAST data set are either created if they don't exist or updated.  Not deleting any facilities at this time.
1.  From your rails terminal run the task => rails va_facilities:create_or_update_va_facilities.
2.  Code will output progress info on the facilities as they are being processed - either updated or created.
3.  When finished you should see the following: "All VA facilities have been created or updated in the DB!"
4. Prior to running the task the number of records in …
=> dm-2820: Update Facilities

app/controllers/practices_controller.rb
[DM-3000](https://agile6.atlassian.net/browse/DM-3000)
This PR bumps up the expiration time since we are using an AWS IAM profile to pre-sign the image URLs which means the URLs are only valid for up to 6 hours.
See: https://aws.amazon.com/premiumsupport/knowledge-center/presigned-url-s3-bucket-expiration/
=> DM-3000: Expire practices json every 4 hours

app/assets/stylesheets/dm/components/_buttons.scss, app/views/home/_featured_section.html.erb, app/views/home/index.html.erb, app/views/practices/show/desktop_partials/_maturity_level_banner.html.erb
https://agile6.atlassian.net/browse/DM-3012
Adds new styling to certain links
Check the following links to make sure they match the figma styling:
1. "Learn more" on homepage.
2. "Browse all innovations" on homepage.
3. Featured practice/topic on homepage.
4. "Start nomination" on homepage.
5. Various "See more" links on the practice page (overview section/comments).
https://www.figma.com/file/H2aII1WHRlySNG6r2HlZbY/Sitemap
Places to stylize links:
Homepage
- Featured links
- “Browse All”
- Learn More
- “See More” on practice pages
=> DM-3012: Finished restyling certain links

scripts/log-rotation.rb
=> add-log-rotation-script: Added the script

app/controllers/practice_partners_controller.rb, spec/features/practice_partners_spec.rb
Ensures the practices listed on the partners show page is associated with that practice
1. Log in as a user
2. Go to a partner's show page and ensure the practices listed there are the same ones associated with that partner.
3. Log out as a user
4. Go to a partner's show page and ensure the practices listed there are the same ones associated with that partner and the practices displayed are visible to the public
=> DM-3090: Display correct innovations associated with partner

app/helpers/application_helper.rb, app/helpers/practices_helper.rb, spec/spec_helper.rb
[DM-3244](https://agile6.atlassian.net/browse/DM-3244)
This PR accomplishes the following:
- rake tasks are not included when calculating test coverage
- remove some unused code
up from ~85% 😸
=> DM-3244: Remove rake tasks from test coverage

scripts/log-rotation.rb
=> Update log rotation script

Gemfile.lock
=> Remove GEM block added by dependabot

Gemfile.lock, lib/middleware/ntlm-sso.rb, spec/features/visn_spec.rb
=> Restrict public users

lib/middleware/ntlm-sso.rb
[DM-3388](https://agile6.atlassian.net/browse/DM-3388)
This PR allows for public users again.
Need to deploy to a production environment to see if this is working.
=> DM-3388: Allow public users again

Gemfile.lock, app/models/application_record.rb
Fixes s3 presigned url issue for filenames that have parentheses
=> Added URI parser to object_presigned_url method

app/admin/pages.rb, app/assets/javascripts/active_admin.js, app/assets/javascripts/application.js, config/application.rb, spec/features/admin/admin_page_spec.rb
Ensures the tinymce assets are copied to our public assets folder in production envs. Moves all the javascript to the `active_admin.js` file.
=> Fix tinymce for production envs

app/assets/javascripts/practice_editor_utilities.es6, app/assets/stylesheets/dm/pages/_practice.scss, app/views/practices/implementation_forms/_timeline.html.erb, app/views/practices/shared/_editing_guide_modal.html.erb
https://agile6.atlassian.net/browse/DM-3466
1. Fixes a column width issue with the practice partner and timeline components.
2. Cleans up some code.
1. Log in as an admin and visit the introduction page of any practice.
2. Scroll down to the "Partners" section.
3. If you don't have any practice partners selected, choose at least two by utilizing the "Add another" feature.
4. Also, make sure that when you click "Add another", the separator line and "Delete entry" link are aligned width-wise with the combobox above them.
5. Click save and check to make sure the separator line and "Delete entry" link are aligned properly as mentioned in the previous step, but on page load (as opposed to clicking "Add another").
6. If you do have practice partners, make sure the separator line and "Delete …
=> DM-3466: Fixed column issue for certain practice editor components

app/models/application_record.rb
https://agile6.atlassian.net/browse/DM-3472
Attempts to fix caching issue by reducing the expiration time of the cached `S3Signer`
=> DM-3472: Reduced expiration time for S3Signer

.circleci/config.yml
https://agile6.atlassian.net/browse/DM-3485
Fixes issue with CircleCI build
=> Circle ci deploy fix

app/admin/pages.rb, app/assets/javascripts/_page_show.es6, app/assets/stylesheets/dm/components/page_component.scss, app/assets/stylesheets/dm/pages/_partials/_header.scss, app/controllers/page_controller.rb, app/helpers/application_helper.rb, app/models/page_component.rb, app/models/page_event_component.rb, app/models/page_news_component.rb, app/views/active_admin/resource/_page_components_form.html.arb, app/views/active_admin/resource/_page_event_component_form.html.arb, app/views/active_admin/resource/_page_news_component_form.html.arb, app/views/page/_events_list.html.erb, app/views/page/_news_items_list.html.erb, app/views/page/_news_list.html.erb, app/views/page/show.html.erb, app/views/page/show.js.erb, app/views/shared/_header.html.erb, db/migrate/20220901222852_create_page_event_component.rb, db/migrate/20220902230740_create_page_news_component.rb, db/migrate/20220902230740_create_page_news_components.rb, db/schema.rb, spec/features/pages/paginated_components_spec.rb, spec/features/pages/show_page_spec.rb, spec/features/shared/header_spec.rb, spec/helpers/application_helper_spec.rb
[DM-3534: Events](https://agile6.atlassian.net/browse/DM-3534?atlOrigin=eyJpIjoiZThlYjYzYWUwMTdlNDliM2FhZDk2NTk5NDRiZTUyYzQiLCJwIjoiaiJ9
)
[DM-3561: News](https://agile6.atlassian.net/browse/DM-3561?atlOrigin=eyJpIjoiYzQxOGIzOGQ3YzcxNDcxZmIwOThlMzZhY2M4MjVkYWUiLCJwIjoiaiJ9)
This PR adds two new PageBuilder components with pagination: News and Events.
1. Create a new PageBuilder Group 
1. Create a new page. Set Template Type to `Narrow`.
2. Create 7 Event components
3. Save page and view page
4. Only 3 events should be displayed
5. Click 'Load more' button to load 3 more events. 
6. Click 'Load more' button to load 1 event. 
7. Event title links should have external styling and open in a new tab.
1. Edit the same page
2. Create 7 News components
3. Save page and view page
4. Only 6 news …
=> DM-3534 DM-3561: Add Events and News Components

app/assets/javascripts/active_admin.js
https://agile6.atlassian.net/browse/DM-3678
1. Adds a check to a select input to ensure malicious data does not get executed.
2. Either create a new Page or go to the edit page of an existing one.
3. Make sure you can add components as intended by using the component dropdown.
- Add code to improve security and mitigate XSS potential
=> Fortify fix

.circleci/config.yml
Renames workflow and removes unused deploy job
=> Renamed workflow and removed unused deploy job

app/views/home/index.html.erb
https://agile6.atlassian.net/browse/DM-3803
Changes the text of the Shark Tank banner.
1. Visit `/` and make sure the Shark Tank banner says "Click here to learn more about the 2023 VHA Shark Tank competition."
- Update banner to say: Click here to learn more about the 2023 VHA Shark Tank competition.
- Release to all three environments
- Test
=> DM-3803: Changed verbiage for shark tank banner

app/views/layouts/application.html.erb
See Slack discussion 3/21
- Removes Fullstory integration that we are no longer using!
- App templates render as expected
- Check browser console for errors. We should no longer be getting errors for failed loading and CORS issues related to fullstory.js.
=> Remove fullstory integration

app/controllers/page_controller.rb
This PR sets up a temporary redirect to 
In DEV: visit https://dev.marketplace.va.gov/competitions/shark-tank
In local dev:
1. Go to `page_controller.rb` and comment out `if request.url.match?(/dev\.marketplace\.va\.gov\/competitions\/shark-tank/)`
2. Add `if request.url.match?(/localhost:3200\/competitions\/shark-tank/)`
3. Go to `localhost:3200/competitions/shark-tank` and confirm the redirect works
=> Temporarily redirect DEV shark tank page to PROD shark tank

app/views/about/index.html.erb
Follow on from #592 
- Update links to VHA Innovation Ecosystem
1. Go to /about
2. Click on Diffusion of Excellence link. Link should take you directly to a page about this program.
3. Click on VHA Innovation Ecosystem. Link should take you to VHA Innovation Ecosystem homepage
=> Link directly to DoE page on VHA innovation ecosystem

Dockerfile
[DM-3716](https://agile6.atlassian.net/browse/DM-3716?atlOrigin=eyJpIjoiMWY0YmY5OThjY2Q2NDEwNGI4ZTAwODJkNGMzOTA0NmMiLCJwIjoiaiJ9)
- Unpins bundler version in Dockerfile, per [updated guidance](https://agilesix.slack.com/archives/C010LQ2V3MZ/p1686589346710739)
=> Unpin bundler version in Dockerfile after updated guidance

app/admin/pages.rb, app/assets/javascripts/_page_show.es6, app/views/active_admin/resource/_page_cta_component_form.html.arb, app/views/page/show.html.erb, db/migrate/20230629165759_add_has_background_color_to_page_cta_components.rb, db/schema.rb
https://agile6.atlassian.net/browse/DM-3947
Update Call to Action PageBuilder component to allow colored background. Adds checkbox to page builder form under the cta component to add background color to displayed component.
1. Add a cta button to a page in the page builder workflow, check the "add background color" checkbox. 
2. The rendered page should display the button and accompanying text with a black background and flipped text color. Text should appear to the left of the button. See second screenshot below
3. Edit the page again and uncheck the "add background color" checkbox.
4. The rendered page should display the button as it normally looked before the addition of the "add background color" option. See third second screenshot below.
* Note: I went through and checked all the …
=> Dm 3947 add color to cta pb component

.github/workflows/run-tests.yml
Part of DM-3780
Moves the `run-tests` workflow to another branch for troubleshooting so that we aren't running unnecessary broken builds every time we push to `master`
=> Move GitHub Actions run-tests workflow to a QA branch for testing

app/admin/pages.rb, app/assets/javascripts/active_admin.js, app/models/page_component.rb, app/models/page_triple_paragraph_component.rb, app/views/active_admin/resource/_page_components_form.html.arb, app/views/active_admin/resource/_page_triple_paragraph_component_form.html.arb, app/views/page/show.html.erb, db/migrate/20230629212614_create_page_triple_paragraph_components.rb, db/schema.rb, spec/features/pages/triple_paragraph_spec.rb, spec/models/page_triple_paragraph__component_spec.rb
https://agile6.atlassian.net/browse/DM-3935
Adds new three-column text page-builder component
1. As admin create a page, add Triple Body Text component
2. Fill in title and body for each text field
3. Check the page and verify the three columns and titles are displayed:
5. Edit the component and check the "Add background color" box
6. Visit the page and verify the component is displayed with background color:
https://www.figma.com/file/ccwLbt94U9QGfnuFCwOXzY/Core-Designs---VA-DM?type=design&node-id=6181-38719&mode=design&t=bS4wKIUGg2dWEVOu-0
=> Dm 3935 three column pb component

app/admin/pages.rb, app/assets/javascripts/_page_show.es6, app/assets/javascripts/active_admin.js, app/assets/stylesheets/dm/components/page_component.scss, app/controllers/page_controller.rb, app/models/page_component.rb, app/models/page_publication_component.rb, app/models/page_simple_button_component.rb, app/views/active_admin/resource/_page_components_form.html.arb, app/views/active_admin/resource/_page_publication_component_form.html.arb, app/views/active_admin/resource/_page_simple_button_component_form.html.arb, app/views/page/_publications_list.html.erb, app/views/page/_publications_list_cards.html.erb, app/views/page/show.html.erb, app/views/page/show.js.erb, db/migrate/20230524232434_create_page_publication_component.rb, db/migrate/20230707214035_create_page_publication_component.rb, db/migrate/20230711205117_create_page_simple_button_component.rb, db/schema.rb, spec/features/pages/publication_component_spec.rb, spec/models/page_publication_component_spec.rb, spec/models/page_simple_button_component_spec.rb
[DM-3954](https://agile6.atlassian.net/browse/DM-3954)
- Adds a publication component
- fields: title, url OR attachment, published_in, publication date, title
- paginates for 10+ components
- applies card styling for <2 publications 
- Adds a simple button component to support VA immersive homepage design (i.e. See more button that links to Publications page - https://www.figma.com/file/ccwLbt94U9QGfnuFCwOXzY/Core-Designs---VA-DM?type=design&node-id=6181%3A38719&mode=design&t=GsnXX0gGDh83hjz2-1)
1. Log in as an admin, create a page group and test page
2. Create 13 with publications only titles. Save page.
3. Insert a Simple Button component between publications 2 and 3. Save page.
4. View page. The first 2 components should have card styling applied. The latter publications should have …
=> Dm 3954: Add a PageBuilder Publications Component and Simple Button Component

app/views/page/show.html.erb
https://agile6.atlassian.net/browse/DM-4041
Adds bottom margin to Events List pb component
Local:
Mockup:
https://www.figma.com/file/ccwLbt94U9QGfnuFCwOXzY/Core-Designs---VA-DM?type=design&node-id=6181-38719&mode=design&t=ywFNNkBZ5uQUOT3W-0
=> dm-4041 Add bottom margin to events list pb component

app/models/page_component.rb
https://agile6.atlassian.net/browse/DM-4060
Renames and reorders components
Edit a page and verify the drop down looks like the screenshot below
=> Edits component selection list in pb

app/views/page/show.html.erb
https://agile6.atlassian.net/browse/DM-4061
Adds bottom margin to simple button pbc
Add a simple button followed by another cta button with background color, verify there is a margin between the two on the rendered page
Before:
After:
Not in mockup*
=> Add bottom margin to simple button pbc

.github/workflows/run-tests.yml
[DM-3780](https://agile6.atlassian.net/browse/DM-3780)
- Replaces GitHub Actions workflow for running tests with a vanilla Rails template
- allows `run-tests.yml` to run on individual devs' test branches
=> DM-3780: Use vanilla Rails template for GitHub actions run-tests.yml

.github/workflows/run-tests-ga-cli.yml, .github/workflows/run-tests.yml
=> DM-3780: Add another branch for testing results from GitHub Actions to CircleCI CLI 

config/routes.rb, spec/features/shared/header_spec.rb
https://agile6.atlassian.net/browse/DM-3938
Adds redirects for xr-network urls
1. In rails console:
```
page_group = PageGroup.create(name: 'va-immersive', slug: 'va-immersive', description: 'va-immersive page')
Page.create(page_group: page_group, title: 'VA Immersive', description: 'VA Immersive page', slug: 'home', has_chrome_warning_banner: true, created_at: Time.now, published: Time.now)
Page.create(page_group: page_group, title: 'VA Immersive About', description: 'VA Immersive about page', slug: 'about', has_chrome_warning_banner: true, created_at: Time.now, published: Time.now)
Page.create(page_group: page_group, title: 'VA Immersive Events And News', description: 'VA Immersive events page', slug: 'events-and-news', has_chrome_warning_banner: true, created_at: Time.now, published: …
```
=> DM-3938 add redirects for xr urls

.github/workflows/ruby-3.yml
[DM-3780](https://agile6.atlassian.net/browse/DM-3780)
Sets up a workflow file for testing GitHub Actions CI with a Ruby 3 branch
=> Create a GitHub Actions workflow for Ruby 3

.github/workflows/run-tests.yml, spec/spec_helper.rb
https://agile6.atlassian.net/browse/DM-4085
* updates github actions ci workflow, adds setup for chrome and chrome-driver, hard-codes version for chrome-driver as action for setting up based on stable versions have not yet aligned. see https://googlechromelabs.github.io/chrome-for-testing/
* updates config for selenium_chrome_headless driver
* adds config for selenium_firefox_headless driver
results of this build: https://github.com/department-of-veterans-affairs/diffusion-marketplace/actions/runs/5787615171/job/15684915692
=> DM-4085 Set up CI workflow on GitHub Actions

.github/workflows/run-tests.yml
[DM-3780](https://agile6.atlassian.net/browse/DM-3780)
Update the GitHub Actions workflow to run on pull requests against `master`
=> DM-3780: Run tests on GitHub Actions for PRs against master

app/assets/javascripts/practice_editor_risk_mitigation.es6
https://agile6.atlassian.net/browse/DM-4048
https://agile6.atlassian.net/browse/DM-4047
* Fix codeql incomplete string escape warning: remove unused function, `createUniqueRiskMitiId`, causing insecure randomness security warningedit string extracting by adding global flag to fix "incomplete-sanitization" codeql security warning
* Fix codeql insecure randomness warning: remove unused function, `createUniqueRiskMitiId`, causing "insecure randomness" security warning
1. Edit an existing practice
2. From the "Implementation" tab add a "Risk and Mitigation", save and update the page.
3. Nav back to the "Implementation" page, verify the risk/mitigation was saved.
4. Add another, save and submit, verify the page updates.
=> DM-4048 fix CodeQl security warnings

.github/workflows/run-tests.yml
=> pin chromedriver version in gh actions rspec workflow

app/admin/pages.rb
Adds a conditional to page builder image preview under form fields block
1. for an existing page builder page add a news component but don't add an image to it
2. update the page and verify the preview page renders
3. add a few other image components including an image at the top under "Page Information" and verify the preview page renders upon update.
=> add conditional to form field image preview

app/views/practices/_search.js.erb
https://agile6.atlassian.net/browse/DM-4145
edit search conditional to place empty search at top
move empty search search logic to defined function
1. verify the search page renders all practices upon page load
2. verify keyword search and filter functionality work as expected
=> edit search filter logic

Gemfile, Gemfile.lock, config/application.rb, scripts/container_start_server.sh
https://agile6.atlassian.net/browse/DM-4197
removes sidekiq
There is only one place I have found that once leveraged sidekiq, otherwise it is not in use. I deployed this branch to DEV and clicked around a bit to ensure the app is functioning which could be done locally to verify but ultimately I think this is a safe change.
=> dm-4197 remove sidekiq gem

app/views/about/index.html.erb, spec/features/about_spec.rb
[DM-4205](https://agile6.atlassian.net/browse/DM-4205)
- Renames "Contact us" to "Send us feedback"
- Adds a USWDS Alert component with info about the hotline and MyHealtheVet website
- Updates column divs to match design
Review [Figma design ](https://www.figma.com/file/ccwLbt94U9QGfnuFCwOXzY/Core-Designs---VA-DM?type=design&node-id=2290%3A13188&mode=design&t=ck2avy2deP90viDR-1) and compare with local dev
https://www.figma.com/file/ccwLbt94U9QGfnuFCwOXzY/Core-Designs---VA-DM?type=design&node-id=2290%3A13188&mode=design&t=ck2avy2deP90viDR-1
=> DM-4205: Add hotline and link to MyHealtheVet to contact form

app/assets/stylesheets/dm/components/_practice_card.scss, app/views/clinical_resource_hubs/_crh_show.js.erb, app/views/clinical_resource_hubs/show.html.erb, app/views/practices/_search.js.erb, app/views/visns/_show.js.erb, app/views/visns/show.html.erb
https://agile6.atlassian.net/browse/DM-4213
* Updates js involved in replacing practice card images: separates logic that handles identifying the placeholder divs with s3 images into a new function that can be utilized in the `/crh/:id` js
* Updates `.dm-practice-card-image-container` 
1. locally, log in as admin, nav to the `/search` page and verify the practice card images render as expected.
2. in rails console run: 
* Note: the `practice_origins_facilities` factory was added with https://github.com/department-of-veterans-affairs/diffusion-marketplace/pull/709 so this branch will need to be rebased with master once that is merged to run the above commands. However, if your local data is unchanged since running local tests indicated in the aforementioned pr, these commands have already …
=> dm-4213 fix practice card images

app/controllers/application_controller.rb
https://agile6.atlassian.net/browse/DM-4256
* breaks into helper methods
* adds error handling and logging
* reduces length of time the `s3_signer` object is cached to be less than its expiration time upon creation
=> dm-4256 refactor `#signed_resource` method

app/assets/javascripts/_practice_partner_practices_utilities.es6, app/assets/javascripts/_replaceImagePlaceholdersOnLoad.es6, app/views/practice_partners/show.html.erb, app/views/users/show.html.erb
https://agile6.atlassian.net/browse/DM-4269
Adds script tags to run practice card image replacement functions for user profile page
1. Locally as logged in user, go to a page on which practices can be favorited, such as a facility show page that has created or adopted practices and bookmark a few
2. Go to your user profile page and verify that the practice card images load and replace the black placeholder background
=> Dm 4269 fix user page practice images

app/views/home/index.html.erb
[DM-4334](https://agile6.atlassian.net/jira/software/c/projects/DM/boards/22?assignee=628bb7e140b157006f7272cd)
- Updates the Shark Tank banner link for better accessibility + SEO
=> Update the Shark Tank banner text for better accessibility

app/controllers/nominate_practices_controller.rb, spec/spec_helper.rb
https://agile6.atlassian.net/browse/DM-4348
adds recaptcha v3 to `NominatePracticesController#email`
* go to `/nominate-an-innovation` and send a message, verify it generates an email
=> DM-4348 add recaptcha to `NominatePracticesController#email`

scripts/jenkins/back_up_prod_db.sh
[DM-4347](https://agile6.atlassian.net/browse/DM-4347)
- Updates the Prod DB backup script to reflect operating system changes between [Ruby 2.7](https://github.com/agilesix/Dockerfiles/tree/master/ruby/2.7.8) and [Ruby 3.2](https://github.com/agilesix/Dockerfiles/tree/master/ruby/3.2.2)
1. Run the script in Jenkins
1. Confirm backup file was successfully uploaded
=> DM-4347: Update PROD DB backup script documentation

Gemfile, Gemfile.lock
- Updates `pg`. #741 was overwritten by #737
=> Restore pg 1.5.4

Gemfile, Gemfile.lock
[DM-4376](https://agile6.atlassian.net/browse/DM-4376)
- Diff: https://github.com/spohlenz/tinymce-rails/compare/v6.1.0...v6.4.2
- Log in as an admin, create a page group and page
- Use various components and confirm that WYSIWYG editor is rendering correctly and functioning as expected
- Save the page and confirm that rendered output matches WYSIWYG input
=> Bump Tiny MCE to 6.4.2

Gemfile, Gemfile.lock
Reverts department-of-veterans-affairs/diffusion-marketplace#756
=> Revert "Bump Tiny MCE to 6.4.2"

app/admin/pages.rb
https://agile6.atlassian.net/browse/DM-4317
* removes `versions` and `page_components` filters from `admin/pages` in order to alleviate page load timeouts.
* verify the filters do not appear on the `admin/pages` screen.
=> Dm 4317 admin pages timeout fix

app/assets/stylesheets/dm/pages/_home.scss, app/views/home/index.html.erb, spec/features/homepage_spec.rb
https://agile6.atlassian.net/browse/DM-4398
updates welcome banner on homepage to be in line with 2024 redesign
verify the layout mirrors the figma desing: https://www.figma.com/file/ccwLbt94U9QGfnuFCwOXzY/Core-Designs---VA-DM?type=design&node-id=10914-1114&mode=design&t=yg4Ih9zR6Izf89cY-0
=> DM-4398 update homepage welcome banner styling

.github/workflows/run-tests.yml
n/a
adds 'feature/homepage-refresh` feature branch to GH actions workflow so that prs pointed at feature branch will run through tests
=> add 'feature/homepage-refresh` branch to gh test workflow

proxy/nginx.conf
https://agile6.atlassian.net/browse/DM-4378
Helps to improve security by not revealing the Nginx version number to clients as per WASA scan  
Testing done on Dev server in the Nginx.conf file
=> dm-4378:server token added

app/assets/stylesheets/dm/pages/_home.scss, app/views/home/index.html.erb, spec/features/homepage_spec.rb
[DM-4396](https://agile6.atlassian.net/browse/DM-4396)
- Some CSS and markup tweaks to links 
- Change link text to match design
https://www.figma.com/file/ccwLbt94U9QGfnuFCwOXzY/Core-Designs---VA-DM?type=design&node-id=11121%3A875&mode=dev
=> Style tweaks for search dropdown links

Gemfile, Gemfile.lock
https://agile6.atlassian.net/browse/DM-4383
=> bump tinymce-rails to 6.5

app/assets/stylesheets/dm/pages/_facilities.scss, app/views/maps/_home_map_filters.html.erb, app/views/va_facilities/_index_complexity_select.html.erb, app/views/va_facilities/_index_table.html.erb, app/views/visns/_visn_facilities_table.html.erb, spec/features/va_facility_spec.rb
[DM-4476](https://agile6.atlassian.net/browse/DM-4476)
- Replaces instances of "Complexity" with "Facility complexity levels" in the UI
- Visit `/facilities`. Review table headers
- Visit a VISN show page, e.g. `/visns/2`
- In the Diffusion Map, open the search filters and look for facility complexity level
=> DM-4476: Update terminology for facility complexity levels

Gemfile, Gemfile.lock
1. Drop `sass-rails` as a dependency (it's been deprecated and was succeeded by `sassc`)
2. Bump our Bundler version
=> Bump bundler; drop sass-rails

app/models/page_group.rb
[DM-4493](https://agile6.atlassian.net/browse/DM-4493)
- adds slugs for upcoming communities
1. in local dev, log in as an admin
1. create a page group with the title `suicide-prevention`
1. create a page with that group with the slug `/home`.
1. Go to `/communities/suicide-prevention` and check that it renders the `home` page you created
=> DM-4493: Add new community slugs

spec/features/pages/triple_paragraph_spec.rb
DM-4531 / #814 
- Fixes up a test for the triple paragraph component
=> DM-4531: Update CSS class used in triple paragraph component spec

app/views/shared/_header.html.erb, config/routes.rb, spec/features/shared/header_spec.rb
[DM-4509](https://agile6.atlassian.net/browse/DM-4509)
=> DM-4509: Move VA Immersive into Communities dropdown

lib/tasks/dropdown_event_counter.rb
Adds script file for use in Jenkins for querying homepage dropdown user interaction
I tested on Jenkins on STG and it worked as expected, you can run the script locally by running:
```
bundle exec rails runner 'lib/tasks/dropdown_event_counter.rb' '2024-03-01' '2024-03-31'
```
=> Add dropdown event counter script

.github/workflows/run-tests.yml, README.md
DM-4580
-  updates the version mentioned in the documentation
- update the node version used in CI
- See the upstream Dockerfile for the actual version update.
=> DM-4580: Update node version

app/assets/stylesheets/dm/pages/_home.scss, app/views/home/index.html.erb
[DM-4577](https://agile6.atlassian.net/browse/DM-4577)
- Removes dark background and adjust whitespace
- Matches link style to featured topic / innovation
- Cleans up markup to remove extra divs and unneeded classes
=> DM-4577: Remove dark background from Nominate an Innovation section

README.md
=> Remove old environment links from README

.github/workflows/codeql-analysis.yml
`feature/homepage-refresh` was merged on 3/20 #771
=> Remove feature branch from codeQL workflow

app/assets/stylesheets/dm/components/page_component.scss, app/views/page/show.html.erb
[DM-4555](https://agile6.atlassian.net/browse/DM-4555)
- Updates background color PageBuilder map component and adjusts spacing accordingly
=> DM-4555: Change map component background color and adjust spacing

app/admin/users.rb, app/models/user.rb
[DM-4561](https://agile6.atlassian.net/browse/DM-4651)
1. Adds a scope for site admins
2. Adds a button to admin/users page to review this list
1. Go to admin/users and upgrade several test users to admin privs
2. Select the admins button and make sure the list updated appropriately
=> DM-4561: Add an admins filter for user  management

app/assets/stylesheets/dm/components/_gradient_banner.scss
[DM-4553](https://agile6.atlassian.net/browse/DM-4553)
- Update the gradient used in header banners across the site to match redesign colors
=> DM-4553: update the gradient banner color

app/controllers/page_controller.rb, spec/requests/page_controller_spec.rb
https://agile6.atlassian.net/browse/DM-4692
* updates `PageController` to allow users with `page_group_editor` role for given `page`'s `page_group` access to unpublished `page`'s show view.
* refactor's controller's `check_authorization` callback method to be less redundant
1. As admin add a user as editor to a `page_group` with an unpublished page
2. Log in as the editor and verify you can access the unpublished `page`'s show view
3. Verify you can also access it as an admin
4. Verify that as a logged in user with no editor role for the `page_group` you are redirected to the home page with an unauthorized flash message when trying to access the `page`'s show view
5. Verify the same as previous step but when not logged in
=> dm-4692 editor page preview

app/assets/stylesheets/dm/pages/_partials/_header.scss, app/views/shared/_header.html.erb
[DM-4830](https://agile6.atlassian.net/browse/DM-4830)
- Bumps up the font size for the main nav
- Consolidates some redundant sass
=> DM-4830: Increase font size for main navbar

app/helpers/pages_helper.rb, app/models/page_event_component.rb, app/models/page_news_component.rb, app/models/page_publication_component.rb, app/views/page/_events_list.html.erb, app/views/page/_news_items_list.html.erb, app/views/page/_publications_list_cards.html.erb
Follow up for #887
- DRY things out a bit by moving logic for setting CSS classes for <3 paginated components into a helper
=> DRY out column size logic for paginated components

app/services/save_practice_service.rb, app/views/about/index.html.erb, app/views/clinical_resource_hubs/_crh_categories_combo_box.html.erb, app/views/home/_popular_categories_section.html.erb, app/views/home/index.html.erb, app/views/practices/form/introduction.html.erb, app/views/practices/search_partials/_search_filters.html.erb, app/views/practices/show/desktop_partials/_search_terms.html.erb, app/views/practices/show/mobile_partials/_search_terms.html.erb, app/views/va_facilities/_facility_categories_combo_box.html.erb, app/views/visns/_categories_combo_box.html.erb, spec/features/homepage_spec.rb, spec/features/practice_editor/introduction/introduction_spec.rb, spec/features/search_spec.rb
https://agile6.atlassian.net/browse/DM-4859
changes "Categories" and "Category" to "Tags" and "Tag"
Go through the site and check for any instances of the word "Categories" or "Category" that I may have missed.
=> update user facing text

app/views/home/index.html.erb, spec/features/homepage_spec.rb
[DM-4854](https://agile6.atlassian.net/browse/DM-4854)
=> DM-4854: Title case 'browse all' links in homepage dropdown

app/models/page.rb, spec/models/page_spec.rb
updates method so that when adding a page to the subnav pages it is explicitly added to the end
updates unit test for method
1. In STG, as admin go to the admin view for the "test" `PageGroup` ([test | Diffusion Marketplace (va.gov)](https://staging.marketplace.va.gov/admin/page_groups/test)), note the first page, "Publication test", listed under "COMMUNITY PAGES" is at the top of the list (screenshot 1 below)
2. Go to the admin edit screen for the "Publication test" `Page` ([Edit Page | Diffusion Marketplace (va.gov)](https://staging.marketplace.va.gov/admin/pages/26/edit)) and remove it from the "COMMUNITY PAGES" collection by unchecking the "Should we include this page in the Suicide Prevention sub-navigation?" checkbox (screenshot 2 below) and save the form
3. Go back into the admin …
=> fix communities subnav management

app/views/home/index.html.erb, spec/features/admin/admin_spec.rb, spec/features/homepage_spec.rb, spec/features/practice_spec.rb, spec/features/shared/breadcrumbs_spec.rb
[DM-4887](https://agile6.atlassian.net/browse/DM-4887)
- Tweaks text for homepage feature links
=> DM-4887: Update homepage featured section links text

Dockerfile, install-certs.sh
[](https://agile6.atlassian.net/browse/DM-4928)
This code updates our AWS ECR base image with the VA-Internal-RCA2.CER
=> dm-4928:VA root certs2 Update

app/views/home/index.html.erb, app/views/practices/_search.js.erb, spec/features/homepage_spec.rb, spec/features/practice_partners_spec.rb
https://agile6.atlassian.net/browse/DM-4918
In homepage search dropdown:
* updates "Browse all Communities" to "Browse all Community Innovations"
* updates "Browse all Community Innovations" to nav to the search page with all "Communities" filter tags checked and innovation search results rendered reflect the filters
* updates "Browse all Tags" link to nav to search page with filters accordion open and in screen center
1. Verify the bullets in the description.
2. Verify that after clicking the links from the homepage dropdown and being nav'd to the search page that the filter and search functionality works as expected.
=> dm-4918 update search copy and functionality

app/views/home/index.html.erb
N/A, follow up to #909
Updates styling for `Discover VA innovations to adopt at your healthcare facility` so that it stays centered
=> Update homepage banner text styling to account for longer wording

proxy/Dockerfile
https://agile6.atlassian.net/browse/DM-4960
This configuration change updates our Nginx image from centos v7 to v9 
Testing done on dev and staging server
=> dm-4940:bump centosv7 to v9

app/controllers/home_controller.rb
adds caching to data pulled for facilities for the maps page
1. verify the diffusion map page loads
=> add caching to facilities query for map data

lib/tasks/va_facilities.rake
https://agile6.atlassian.net/browse/DM-4990
Updates `va_facilities.json` with recently obtained data from most recent VAST report, updates importer task to expect a few column names from the report that have been updated since last time (which was in 2020 I think)
[From the prior pr that Brad wrote up](https://github.com/department-of-veterans-affairs/diffusion-marketplace/pull/388):
1. From your rails terminal run the task => rails va_facilities:create_or_update_va_facilities.
2. Code will output progress info on the facilities as they are being processed - either updated or created.
3. When finished you should see the following: "All VA facilities have been created or updated in the DB!"
4. Count of `va_facilties` in my local data increases from 1590 to 1628
Note: the facilities within …
=> DM-4990 update va facilities data

Gemfile.lock
N/A
- Bump bundler version
- Deploy to DEV and confirm that dependencies are installed appropriately
=> Bump bundler to 2.5.16

spec/features/visn_spec.rb
adjusts VISN feature tests surrounding gmap to revisit the page for each assertion block
=> update VISN feature spec

config/ldap.yml
https://agile6.atlassian.net/browse/DM-5023
switches LDAP host address to known working address, currently deployed and working on DEV
Visit dev while connected to VA vpn and confirm the site loads as logged in user
=> update ldap host address

spec/features/home_map_spec.rb
updates to load page for each test in home map feature spec, change necessary due to recent changes in loading gmap libraries async
=> update home map feature spec

app/assets/javascripts/_practice_card_utilities.es6, app/assets/stylesheets/dm/components/_search_result.scss, app/assets/stylesheets/dm/pages/_search.scss, app/views/practices/_search.js.erb, app/views/practices/search.html.erb
[DM-5095](https://agile6.atlassian.net/browse/DM-5095)
- Fix search result styling for tablet width
- Move images onto their own row in mobile
- Remove irrelevant CSS properties migrated from practice cards
- Move styling out of JS builder function and into SCSS
=> DM-5095: Responsive behavior tweaks

app/views/practices/search.html.erb, app/views/practices/search_partials/_search_filters.html.erb
https://agile6.atlassian.net/browse/DM-5099
adds header above new search results list, adjusts padding and margins of a few search page elements
compare with [the Figma design](https://www.figma.com/design/D16fyBygVx88HpyczTuqXs/Diffusion-Marketplace-(2024)%2B?node-id=717-19920&t=VDDsa3S8XpLOg2hh-0)
=> Dm 5099 add search results list header

app/views/practices/_search.js.erb, app/views/practices/search_partials/_search_filters.html.erb, spec/features/search_spec.rb
https://agile6.atlassian.net/browse/DM-5097
adds `position-relative` class to search page filter checkboxes to fix auto-scroll issue while navigating by keyboard, incidentally fixed the issue with shifting focus when clicking so the `preventFocusShift` function I added is no longer needed.
1. on the search page navigate through the filters checkboxes via keyboard and verify the scrollable area auto-scrolls to follow focus
2. verify that when clicking any of the lower checkboxes the window focus does not shift
=> dm-5097 search filters accessibility

spec/spec_helper.rb
N/A
Remove a test suite step from the old Circle CI days.
=> Remove old Circle CI artifact generation

app/models/practice.rb
N/A
- Adds relevant `attr_accessor`s that were throwing errors in the importer workflow.
1. Run `dm:reset_up` and confirm the workflow runs without errors
=> Fix up importer workflow for local dev

spec/features/pages/show_page_spec.rb, spec/helpers/categories_helper_spec.rb, spec/spec_helper.rb
N/A
Updates caching approach for test suite to unblock some recent flakies.
=> Stop clearing Rails cache for all specs

app/controllers/nominate_practices_controller.rb, app/views/shared/_email_form.html.erb, spec/features/nominate_practices/nominate_a_practice_page_spec.rb
DM-5904 (Follow-up to #982)
- Hide reCAPTCHA HTML for VA users
=> DM-5904: Don't render reCAPTCHA for VA users

app/assets/stylesheets/dm/components/_search_result.scss
adds `object-fit: cover` to `.dm-search-result.search-result-img-container` class images
Locally and on STG (currently deployed) verify search result images are not warped
=> Update search result image css

.github/workflows/run-tests.yml
N/A
- Cleans out merged feature branches from our CI's push and pull request lists
=> Remove merged feature branches from CI workflow

app/models/page_group.rb
[DM-5141](https://agile6.atlassian.net/browse/DM-5141)
- Adds incoming Fellowships community to approved list of communities 
1. Go to `/admin/page_groups`
2. create a new page group with the name `fellowships` and save.
3. Edit the page group so that its name is now `VHA IE Fellowships`
4. Go to `/admin/pages` and create a page with slug `home`. Mark checkbox for including this page in the subnav.
5. Save the page and publish it
6. Go to `/communities/fellowships` and confirm the subnavigation menu is showing. 
7. Check that `VHA IE Fellowships` is shown in the main navbar's `Communities` dropdown
8. Check out `master`. 
9. Go back to `/communities/fellowships` and confirm the subnavigation menu disappears.
=> Add fellowships to approved communities list

install-certs.sh
Update VA root Certificate for compliancy measures
=> dm-5195:update VA root Certs

app/assets/stylesheets/dm/pages/_practice.scss, app/views/practices/form/implementation.html.erb, app/views/practices/implementation_forms/_departments.html.erb, app/views/practices/implementation_forms/_risks_and_mitigations.html.erb, app/views/practices/implementation_forms/_timeline.html.erb, spec/features/practice_editor/header_and_footer_spec.rb, spec/features/practice_editor/implementation/practice_resources_spec.rb, spec/features/practice_editor/implementation/risk_and_mitigation_spec.rb
[DM-5167](https://agile6.atlassian.net/browse/DM-5167)
- Update copy
- Remove PII / PHI alert 
- Make headers visually distinct
- Update styling for outline buttons (The inheritance is set up so we can remove these styles after palette consolidation)
- Bold all form labels
- Remove bold from add another / delete entry links
=> DM-5167: Visual design updates for editor "Implementations"

app/assets/stylesheets/dm/components/_buttons.scss, app/assets/stylesheets/dm/pages/_practice.scss, app/views/practices/form/about.html.erb, app/views/practices/form/introduction.html.erb, app/views/practices/form/overview.html.erb, app/views/practices/implementation_forms/_departments.html.erb, app/views/practices/implementation_forms/_resources.html.erb, app/views/practices/implementation_forms/_timeline.html.erb, app/views/practices/overview_forms/_image_form.html.erb, app/views/practices/shared/_caption_label.html.erb, app/views/practices/shared/_image_alt_text_label.html.erb, spec/features/practice_editor/overview/image_spec.rb, spec/features/practice_editor/overview/video_spec.rb
[DM-5166](https://agile6.atlassian.net/browse/DM-5166)
- Add headings
- Update markup and styling for image forms
- Start consolidating component classes
- Remove unnecessary uses of `dm-button--unstyled` on links.
=> DM-5166: Visual design updates for editor "Overview" page

app/assets/stylesheets/dm/pages/_practice.scss, app/views/practices/form/about.html.erb, spec/features/practice_editor/about_spec.rb
[DM-5168](https://agile6.atlassian.net/browse/DM-5168)
- Add headings
- Update link styles
- Reorder sections
- Update copy
=> DM-5168: Visual design updates for practice editor "About" page

app/assets/stylesheets/dm/pages/_practice.scss, app/views/practices/form/adoptions.html.erb, app/views/practices/form/adoptions_forms/_adoption_accordion_by_status.html.erb, app/views/practices/form/adoptions_forms/_adoption_form.html.erb, spec/features/practice_editor/adoptions_spec.rb
[DM-5165](https://agile6.atlassian.net/browse/DM-5165)
- Update copy and headings
- Use links instead of icons for child accordion controls
- Use flex box instead of `float-right` for more responsive button row behaviors
=> DM-5165: Visual design updates for editor "Adoptions" page

app/models/va_facility.rb
https://agile6.atlassian.net/browse/DM-4994
Adds `paper_trail` tracking to `VaFacility` model
1. in local rails console run `VaFacility.last.update!(hours_note: "test")`
2. verify it created a version in the `paper_trail` history by running `VaFacility.last.versions`
=> add paper_trail to VaFacility model

lib/assets/products.csv, lib/tasks/products.rake
https://agile6.atlassian.net/browse/DM-5204
* update products.csv file with new column "Innovators" containing names and roles of intrapreneurs found in the "Meet the Intrapreneur" column
* updates logic in product importer task to:
1. use `find_or_create_by` when creating associated records in order to prevent duplication, associate default user with each product
2. utilize data in the new "Innovators" column to create and associate `va_employees` with the product
3. wrap each product creation in a transaction block with error rescuing
1. drop your local db and run `dm:full_import`
2. verify that 12 `products` are created without issue
3. verify that each `product`'s `user` is the default user (`email: "marketplace@va.gov"`)
4. verify that each `product`'s `va_employees` coincide with …
=> DM-5204 add va employees to product importer

app/controllers/products_controller.rb, app/views/products/form/description.html.erb
[DM-5069](https://agile6.atlassian.net/browse/DM-5199)
- Update `Description` page in editor to have a field for tagline
=> DM-5069: Add "Tagline" to Description page in Product editor

app/admin/categories.rb, app/controllers/products_controller.rb, app/helpers/categories_helper.rb, app/models/product.rb, app/services/save_practice_service.rb, app/views/practices/introduction_forms/_category_checkbox.html.erb, app/views/products/form/description.html.erb, spec/features/product_editor/description_spec.rb
https://agile6.atlassian.net/browse/DM-5202
adds categories management ui to product editor "Description" page
refactors existing `category_checkbox` partial by extracting query methods to `CategoryHelper` module and making the field name dynamic depending on parent record type (so as to properly nest the request attrs)
refactors multimedia handling logic in `ProductsController` to be a `Product` model method
1. go to `/products/12/edit/description` and verify the "Tags" section of the form appears towards the bottom with all available `categories` as checkbox options
2. verify that adding and removing tags persists as expected after making some changes and submitting the form
3. verify that the "All" checkboxes check and uncheck their corresponding tags when clicked
4. go to the …
=> dm-5202 product editor categories

app/controllers/home_controller.rb
[DM-5264](https://agile6.atlassian.net/browse/DM-5264)
Unset an unused before action on the homepage
=> Stop pulling facility data on homepage

lib/tasks/products.rake
[DM-5073](https://agile6.atlassian.net/browse/DM-5073)
Add tags to Products bulk importer
1. Drop Products in your local DB and run the importer task `rake dm:reset_up`
2. Review each product page and confirm that tags rendered match the spreadsheet provided in the [parent story](https://agile6.atlassian.net/browse/DM-5071)
=> DM-5073: Bulk import tags for Products

.github/workflows/run-tests.yml
=> DM-5274: Add ImageMagick to GitHub Actions workflow

app/models/page_group.rb
[DM-5155](https://agile6.atlassian.net/browse/DM-5155)
- Adds QUERI to the list of approved communities
1. Go to `/admin/page_groups`
2. create a new page group with the name `queri` and save.
3. Edit the page group so that its name is now `QUERI`
4. Go to `/admin/pages` and create a page with slug `home`. Mark checkbox for including this page in the subnav.
5. Save the page and publish it
6. Go to `/communities/queri` and confirm the subnavigation menu is showing. 
8. Check out `master`. 
9. Go back to `/communities/queri` and confirm the subnavigation menu disappears.
=> Add QUERI to list of approved communities

db/migrate/20240827213548_create_products.rb, db/migrate/20240909214757_add_fields_to_products.rb, db/migrate/20240910212507_add_published_and_retired_to_products.rb, db/migrate/20240918010354_add_slug_to_products.rb, db/migrate/20240930214407_add_vendor_link_to_products.rb, db/migrate/20241010210000_add_main_display_image_caption_to_products.rb
Moves all simple migrations for `products` table into original creation migration
=> Consolidate products migrations

app/assets/stylesheets/dm/pages/_products.scss, app/controllers/products_controller.rb, app/views/layouts/application.html.erb, app/views/products/_product_editor_header.html.erb, app/views/products/_publication_validation.js.erb, app/views/products/form/description.html.erb, app/views/products/form/editors.html.erb, app/views/products/form/intrapreneur.html.erb, app/views/products/form/multimedia.html.erb, config/routes.rb, spec/features/product_editor/description_spec.rb
[DM-5228](https://agile6.atlassian.net/browse/DM-5228)
=> DM-5228: Add custom header for Product Editor

db/migrate/20240827213548_create_products.rb, db/schema.rb
=> Fix products migration

app/views/products/show.html.erb, spec/features/product_viewer_spec.rb
DM-5282
- Updates "Order Product" instructions with finalized copy
- Adds external link styling to Vendor links
=> DM-5282: Update order product copy, fix external links

app/admin/products.rb, spec/features/admin/admin_products_spec.rb
https://agile6.atlassian.net/browse/DM-5285
Updates logic for `products`' `ActiveAdmin` management so that when assigning or updating a `product`'s `user` it does not create a new user in the case of a submitted VA email not matching a registered `user`'s
Also updates so that the `user` is added as a `PracticeEditor` for the product if `product.user` is present.
Refactors controller actions and helper methods a bit. 
1. Verify that when trying to create or edit a product from `ActiveAdmin`, it will not create a user for a submitted "USER EMAIL" value that doesn't match a registered `user`'s `email`, it should go back to the form with a flash message indicating the failure.
2. Verify that submitting with no email works as expected.
3. Verify that submitting with an email that does match a …
=> dm-5285 update admin/products #set_product_user

lib/tasks/va_facilities.rake
https://agile6.atlassian.net/browse/DM-5018
update facilities importer task:
* adds logic to va_facilities:create_or_update_va_facilities that writes file with list of names and ids of non-current va_facilities
* adds new task va_facilities:delete_non_current_va_facilities that reads contents of non-current facilities file and deletes the facility if the diffusion_histories and practice_origin_facilities are empty, *Task outputs a file containing the names and ids of facilities deleted as well as names, ids, and names of associations for facilities that were not deleted*
1. Starting with normal local data, add a few facilities to the db using factory bot via rails console: `FactoryBot.create(:va_facility)`
2. run the facilities task which will generate a file of names and ids of …
=> dm-5018 update facilities importer task

.github/workflows/run-tests.yml
=> Remove merged feature branch from CI

spec/features/product_viewer_spec.rb
=> Fix typo in product viewer spec

Gemfile.lock, README.md, spec/features/nominate_practices/nominate_a_practice_page_spec.rb, spec/features/shared/header_spec.rb
=> 🧹 Repo tidying

app/views/shared/_header.html.erb
[DM-5315](https://agile6.atlassian.net/browse/DM-5315)
- Hold until Fellowships community is published in PROD
- Confirm that the VHA IE Fellowships community is linked to via the main nav
=> Add Fellowships community to main navbar

app/controllers/practices_controller.rb, app/models/practice.rb, app/models/practice_testimonial.rb, db/migrate/20241101005744_drop_practice_testimonials.rb, db/schema.rb
=> Drop retired PracticeTestimonials model

.github/workflows/run-tests.yml
[DM-4608](https://agile6.atlassian.net/browse/DM-4608)
=> Bump CI postgres version to 13

app/helpers/practice_managements_helper.rb, app/models/practice.rb, app/models/practice_management.rb, app/models/practice_management_practice.rb, db/migrate/20241101004315_drop_practice_managements.rb, db/schema.rb, db/seeds.rb, lib/tasks/importer.rake, spec/models/practice_management_spec.rb, spec/models/practice_spec.rb
[DM-5308](https://agile6.atlassian.net/browse/DM-5308)
- Drops defunct model
=> Drop retired PracticeManagements

app/models/practice.rb, app/models/va_secretary_priority.rb, app/models/va_secretary_priority_practice.rb, db/migrate/20241101010301_drop_va_secretary_priorities.rb, db/schema.rb, db/seeds.rb, lib/tasks/importer.rake, spec/models/practice_spec.rb, spec/models/va_secretary_priority_practice_spec.rb, spec/models/va_secretary_priority_spec.rb
[DM-5306](https://agile6.atlassian.net/browse/DM-5306)
- Remove defunct model
=> Drop retired VaSecretaryPriorities model

app/controllers/practices_controller.rb, app/models/practice.rb, app/models/practice_permission.rb, db/migrate/20241101003540_drop_practice_permissions.rb, db/schema.rb, lib/tasks/importer.rake, spec/models/practice_permission_spec.rb, spec/models/practice_spec.rb, spec/tasks/importer_spec.rb
[DM-5309](https://agile6.atlassian.net/browse/DM-5309)
=> Drop retired PracticePermissions model

README.md, lib/assets/practice_origin_lookup.json, lib/tasks/visns.rake
[DM-5330](https://agile6.atlassian.net/browse/DM-5330)
- Remove legacy VISN liaison creation task and relevant data
- Confirm that current VISN liaisons are managed via ActiveAdmin.
=> Remove VISN liaison creation task

app/models/clinical_location.rb, app/models/clinical_location_practice.rb, app/models/practice.rb, db/migrate/20241101005022_drop_clinical_locations.rb, db/schema.rb, db/seeds.rb, lib/tasks/dm.rake, lib/tasks/importer.rake, spec/models/clinical_location_practice_spec.rb, spec/models/clinical_location_spec.rb, spec/models/practice_spec.rb, spec/tasks/importer_spec.rb
[DM-5307](https://agile6.atlassian.net/browse/DM-5307)
- Retire a defunct model
=> Drop retired ClinicalLocations model

app/controllers/practices_controller.rb, app/models/additional_staff.rb, app/models/practice.rb, db/migrate/20241101002620_drop_additional_staffs.rb, db/schema.rb, lib/tasks/importer.rake, spec/models/additional_staff_spec.rb, spec/models/practice_spec.rb, spec/tasks/importer_spec.rb
[DM-5310](https://agile6.atlassian.net/browse/DM-5310)
- Retires a defunct model
=> Drop retired AdditionalStaffs model

proxy/Dockerfile
https://agile6.atlassian.net/browse/DM-5280
It upgrades Nginx Version from 1.25 to 1.27
Tested on Dev and Staging servers
=> dm-5280:Upgrade Nginx v1.25 to v1.27

app/assets/javascripts/metrics_page.es6
https://agile6.atlassian.net/browse/DM-4879
update metrics page js to sanitize query parameter used to generate url
On the metrics page for an innovation verify the duration can be updated from "the last 30 days" to "all time"
=> dm-4879 fix for dom text reinterpretation codeql warning

config/application.rb
=> rollback config.load_defaults from 6.0 to 5.2

app/views/users/bio.html.erb
update bio partial to render bio text with respect to blank lines
=> Render bio text with blank lines

.github/workflows/run-tests.yml
=> Add Rails-7 feature branch to CI pull request runs

app/views/home/index.html.erb
- Review client sync notes
- Remove Shark Tank competition banner
=> [HOLD until 12/31] Remove shark tank banner 
