department-of-veterans-affairs/diffusion-marketplace

app/views/practices/_form.html.erb

none
Simply removes a lorem ipsum tooltip that was left in place on the practice editor.

Remove lorem ipsum tooltip.

---

Gemfile
Gemfile.lock

Updates the papercrop gem to use our forked version which uses `turbolinks:load` to initialize papercrop.

fix papercrop to use turbolinks:load

---

app/controllers/practices_controller.rb
app/mailers/practice_mailer.rb
app/models/practice.rb
app/models/user_practice.rb
app/views/practice_mailer/commitment_response_email.html.erb
app/views/practice_mailer/support_team_notification_of_commitment.html.erb
app/views/practices/committed.html.erb
app/views/practices/next_steps.html.erb
app/views/shared/_messages.erb
config/routes.rb
db/migrate/20190517052133_create_user_practices.rb
db/schema.rb
spec/features/practice_spec.rb
spec/models/practice_spec.rb

https://agile6.atlassian.net/browse/DM-552
+ adds the commit to practice flow
1. have data
2. go to a practice
3. click "Next Steps"
4. scroll all the way down to the end of the checklist
5. click "Commit to this practice"
6. end up at the confirmation screen
7. get two emails: one sent to the user and one sent to the support team
https://www.figma.com/file/DDUSxYiD1MaWNrGFmMjY8d8a/Diffusion-Marketplace-Designs?node-id=115%3A0
“Commit to a Practice” (verbiage tbd) button created
Button sends out email to Practice support network email
Button sends out email verification to person signing up for practice
Verification screen/pop-up for having signed up (Design)--new page
Can hit button any time

DM-552: commit to practice full flow

---

app/controllers/application_controller.rb

Fixes devise redirect by saving location on every non-devise, non-
ajax request.
https://agile6.atlassian.net/secure/RapidBoard.jspa?rapidView=22&modal=detail&selectedIssue=DM-732
When clicking the login button, on the practice page, it would redirect to the wrong page after logging in. Either the root directory, or the practices search page. Because either no cookie was stored for location, or it only got saved when redirected to login. 
Adds a few lines for devise, which saves the user's location on most requests, so that proper information is stored when directing yourself to login.

dm-732 Fix devise redirect

---

app/assets/javascripts/_feedback_survey.js
app/views/shared/_feedback_survey.html.erb

599
For modals, they should not allow focus behind the modal. Because of the iframe, its difficult to track where the focus is. To fix this, i placed two empty divs, one at the beginning and one at the end. When these get focused, I close the modal. 
When the modal is launched, i place the focus on the close button so that triggering element isn't focused first. 
I also added keyboard controls for the close button and an aria label for it.

Feedback modal

---

app/assets/stylesheets/dm_uswds/theme/_uswds-theme-custom-styles.scss
app/controllers/home_controller.rb
app/controllers/practices_controller.rb
app/models/user.rb
app/views/home/index.html.erb
app/views/practices/_favorite_button.html.erb
app/views/practices/_marketplace_card.html.erb
app/views/practices/_show_authenticated.html.erb
app/views/practices/favorite.js.erb
app/views/practices/index.html.erb
config/routes.rb
db/migrate/20190910185301_add_favorite_to_user_practices.rb
db/schema.rb
spec/features/favorite_spec.rb
spec/spec_helper.rb

https://agile6.atlassian.net/browse/DM-996
Adds a favorite feature throughout the site. On the homepage and practice list page, a favorite icon will appear on practice images for logged in users (on the practice detail page it will be a link). Clicking this icon/button with toggle the user's favorite state for the practice. The state of the icon should update asynchronously without a page load to give the user visual confirmation of the change.
Visit homepage while logged in, click heart icon on any practice, heart should become read, and state should be persisted on reload

DM-996 Build Favorites Feature

---

spec/features/favorite_spec.rb

Accidentally left a focus in my last PR which only ran the specs I added. This should remove that so CI runs all the specs.

Remove focus from favorites spec

---

app/controllers/users_controller.rb
app/views/users/show.html.erb
spec/features/favorite_spec.rb
spec/features/user_profile_spec.rb

https://agile6.atlassian.net/browse/DM-1068
Adds a favorites section to a user's profile
Go to user's profile page, see favorites section
https://www.figma.com/file/DDUSxYiD1MaWNrGFmMjY8d8a/Diffusion-Marketplace-Designs?node-id=767%3A1

DM-1068 Add favorites section to profile

---

app/controllers/practices_controller.rb
app/helpers/application_helper.rb
app/views/practices/overview.html.erb
spec/features/practice_editor/overview_spec.rb
spec/helpers/application_helper_spec.rb

[DM-1336](https://agile6.atlassian.net/secure/RapidBoard.jspa?rapidView=22&projectKey=DM&modal=detail&selectedIssue=DM-1336&quickFilter=31)
This PR allows any user who can edit a practice page to be able to update the `date_initiated` and `number_adopted` fields of a practice via the edit form.
1. Be logged in as a user that can edit a practice page
2. Go to the "Overview" section of the practice page edit form
3. You should see the new origin date and number of practices adopted fields
4. You should be able to edit those fields
5. Those changes should persist on the DB
[Figma](https://www.figma.com/file/DDUSxYiD1MaWNrGFmMjY8d8a/Diffusion-Marketplace-Designs?node-id=3788%3A2721)

DM-1336: Allow edit of adoption # and origin date

---

app/controllers/practices_controller.rb
app/views/practices/_practice_editor_sidenav.html.erb
app/views/practices/instructions.html.erb
app/views/practices/overview.html.erb
spec/features/practice_editor/collaborators_spec.rb
spec/features/practice_editor/instructions_spec.rb
spec/features/practice_editor/overview_spec.rb
spec/features/practice_editor/sidenav_spec.rb

[DM-1324](https://agile6.atlassian.net/secure/RapidBoard.jspa?rapidView=22&projectKey=DM&modal=detail&selectedIssue=DM-1324)
This PR ensures that all links to the "Collaborators" section are removed or changed in favor of the "Overview"/"Instructions" section. The user will no longer be able to see the "Collaborators" link in the side navigation. The user will also be redirected to the "Overview" edit page if they navigate to `.../practices/:practice_id/edit/collaborators`
- Log in as a user who can edit a practice page
- Navigate to the edit pages
- You should not see the "Collaborators" tab in the side navigation
- When navigating to `.../practices/:practice_id/edit/collaborators`, you should be redirected to `.../practices/:practice_id/edit/overview`
- When clicking the "Continue" …

DM-1324: [App] Hide Collaborators tab and page

---

app/assets/javascripts/practice_editor_overview.es6
app/assets/stylesheets/dm/pages/_practice.scss
app/controllers/practices_controller.rb
app/models/practice.rb
app/views/practices/impact.html.erb
app/views/practices/overview.html.erb
spec/features/practice_editor/impact_spec.rb
spec/features/practice_editor/overview_spec.rb

[DM-1338](https://agile6.atlassian.net/secure/RapidBoard.jspa?rapidView=22&projectKey=DM&modal=detail&selectedIssue=DM-1338&quickFilter=31) + subtasks: [DM-1375](https://agile6.atlassian.net/secure/RapidBoard.jspa?rapidView=22&projectKey=DM&modal=detail&selectedIssue=DM-1375&quickFilter=31), [DM-1376](https://agile6.atlassian.net/secure/RapidBoard.jspa?rapidView=22&projectKey=DM&modal=detail&selectedIssue=DM-1376&quickFilter=31), [DM-1414](https://agile6.atlassian.net/secure/RapidBoard.jspa?rapidView=22&projectKey=DM&modal=detail&selectedIssue=DM-1414&quickFilter=31)
This PR moves the ability to edit a practice's thumbnail from the "Impact" section to the "Overview" section.
- Log in as a user that can edit a practice
- Click edit and go to the "Overview" section
- You should be able to …

DM-1338: [App] Move main practice img to Overview

---

Dockerfile

makes it so the credentials key does not show in the console while building.

DM-DEVOPS: silence credentials key

---

app/admin/practices.rb
app/models/practice.rb
app/models/user.rb
spec/features/admin_spec.rb
spec/features/breadcrumbs_spec.rb
spec/features/practice_spec.rb

including unit tests
https://agile6.atlassian.net/browse/DM-1470
In the admin panel (`/admin`), an admin user can now go to the Practices page and create a new Practice and assign a user, that does not have to exist in the system yet, to said Practice.
1. log in a user with `:admin` role
2. browse to `/admin`
3. click `Practices`
4. click `New Practice`
5. You can choose to fill in the user email or not, but, the Practice Name is `required` (you can test that out). 
6. Also, the Practice's name must not exist in the system yet (you can also test that out)
7. Create the Practice
8. Bonus: edit the Practice. You can take off the user, put in a different user, change the name? but I think the slug will stay the same
9. browse to the edit url (`overview`: i.e.: …

DM-1470: add ability for admin to create a practice

---

app/assets/javascripts/_cropper.es6
app/assets/stylesheets/dm/pages/_practice.scss
app/controllers/practices_controller.rb
app/models/practice_creator.rb
app/views/practices/contact.html.erb
app/views/practices/origin.html.erb
spec/features/practice_editor/contact_spec.rb
spec/features/practice_editor/origin_spec.rb

[DM-1348](https://agile6.atlassian.net/secure/RapidBoard.jspa?rapidView=22&projectKey=DM&modal=detail&selectedIssue=DM-1348&quickFilter=31&assignee=5e4d76fe393ea90c94b41b89&assignee=UNASSIGNED_USER_ID): [[DM-1462](https://agile6.atlassian.net/secure/RapidBoard.jspa?rapidView=22&projectKey=DM&modal=detail&selectedIssue=DM-1462&quickFilter=31&assignee=5e4d76fe393ea90c94b41b89&assignee=UNASSIGNED_USER_ID)]
This PR implements the cropper on "Origin" page of the practice editor for the practice creator avatar.
- Log in as a user with the ability to edit practices
- Go to the "Origin" section of the Practice Editor
- Crop, delete, upload, etc the contact headshot 
[Figma](https://www.figma.com/file/DDUSxYiD1MaWNrGFmMjY8d8a/Diffusion-Marketplace-Designs?node-id=1745%3A27776)
(Contact - completed …

DM-1348: [DM-1462] Implement cropper on origin pg

---

app/views/practices/_show_authenticated.html.erb

https://agile6.atlassian.net/browse/DM-1613
defaults the adoption number to `number_adopted` if they have it already and have not started the adoptions page.

DM-1566: default adoptions number

---

app/assets/javascripts/save-editor-progress.es6
app/controllers/practices_controller.rb
app/models/practice.rb
app/services/save_practice_service.rb
app/views/layouts/application.html.erb
app/views/practices/_practice_editor_sidenav.html.erb
app/views/practices/publication_validation.js.erb
config/routes.rb
spec/features/practice_editor/complexity_spec.rb
spec/features/practice_editor/origin_spec.rb
spec/features/practice_editor/overview_spec.rb
spec/features/practice_editor/publish_practice_spec.rb
spec/services/save_practice_service_spec.rb

[DM-1492](https://agile6.atlassian.net/secure/RapidBoard.jspa?rapidView=22&projectKey=DM&modal=detail&selectedIssue=DM-1492&quickFilter=31)
This PR ensures that once the "Publish practice" button is clicked the practice is saved before it is published.
1. Log in as a user that can edit/publish a practice.
2. Ensure this user has access to an unpublished practice.
(If you do not have an unpublished practice, you create an unpublished practice as an admin in `.../admin/practices`)
3. Navigate to the unpublished practice
4. a. Make edits to the practice that do not fulfill conditions for publishing (e.g. do not fill out the contact support email)
4. b. Click "Publish practice". Edits to the practice should be saved but you should see a modal saying "Cannot publish"
4. c. BONUS: Make sure you …

DM-1492: Save practice on publish

---

app/controllers/practices_controller.rb
app/views/practices/_search.js.erb

[DM-1686](https://agile6.atlassian.net/browse/DM-1686)
This PR will remove sponsored tags from search results for each practice.
1. Search for a practice with an associated practice partner.
2. User should no longer see a "Sponsored" tag for each practice result.

DM-1686: Remove sponsored tag from search results

---

README.md
app/admin/categories.rb
app/admin/practices.rb
app/controllers/home_controller.rb
app/controllers/practices_controller.rb
app/models/category.rb
app/models/practice.rb
app/views/practices/_search.js.erb
db/migrate/20200514200744_add_related_terms_to_categories.rb
db/schema.rb
lib/tasks/categories.rake
lib/tasks/dm.rake
spec/features/admin_spec.rb
spec/features/search_spec.rb
spec/models/category_spec.rb

[DM-1681](https://agile6.atlassian.net/browse/DM-1681)
This PR implements the following:
- adds COVID related categories and assigns practices to those categories
- implement CRUD operations for categories in ActiveAdmin
- allow admins to add/remove categories to practices in ActiveAdmin
- allow search by practice categories and a categories' related terms
**Before Testing**
- run `rails db:migrate`
- run `rails categories:add_covid_cats` to add the new categories and assign them to practices
**As an admin:**
1. Categories
- Go to `/admin/categories`
- Ensure you see 5 categories: COVID (with COVID-19, COVID 19, Coronavirus as related terms), Telehealth, Pulmonary Care, Environmental Services, Follow-up Care
- Ensure you are able to add new categories, their description, and related terms …

DM-1681: Search practices by category

---

app/helpers/application_helper.rb

https://agile6.atlassian.net/browse/DM-1807
makes the complexity label correct
1. Edit a practice
2. Go to "Complexity"
3. Choose more than 4 departments - this will make the aggregate greater than 4
4. Save the practice
5. Go to the show view
6. Go to the Complexity section
7. The label next to the four wrenches should say: "High or large complexity to implement"
**Before (BUG):**
**After (FIXED):**

DM-1807: correct label when more than 4 complexity aggregate

---

app/assets/javascripts/_facilitySelect.es6
app/helpers/application_helper.rb
app/views/maps/_home_map_filters.html.erb
app/views/maps/_home_map_marker_modal.html.erb
app/views/maps/_infowindow.html.erb
app/views/practices/_adoptions_list.html.erb
app/views/practices/_show_authenticated.html.erb
app/views/practices/adoptions.html.erb
app/views/practices/overview.html.erb
spec/features/home_map_spec.rb
spec/features/practice_editor/adoptions_spec.rb
spec/features/practice_editor/overview_spec.rb
spec/helpers/application_helper_spec.rb

[DM-1778](https://agile6.atlassian.net/browse/DM-1778)
This PR adds the common names of VA facilities in parentheses if the common name is not included in the official name.
**Homepage practice map**
1. Click on a map marker. 
2. Ensure the common name appears in parentheses in the info box.
May need to click around to find one. ^_^"
e.g. Raymond G. Murphy Department of Veterans Affairs Medical Center (Albuquerque)
2. Click "Filter results"
3. Click "View list of facilities"
4. Ensure the common name appears in parentheses in the list
5. Click "view more" for a map marker and see that the header facility name also has the common name (if applicable)
**Practice page**
1. Log in as a user in order to view a practice
2. Go to a practice show page
3. Ensure the "Origin" facility has a common …

DM-1778: Add common name to facility names

---

app/assets/javascripts/ie.es6
app/views/competitions/shark_tank.html.erb

[DM-1851](https://agile6.atlassian.net/browse/DM-1851)
This PR adds an alert for users viewing the Shark Tank in IE and edits the copy for the page.
1. View shark tank page with IE browser
2. Ensure you see an alert
3. Ensure the conference codes are correct for each date
4. View shark tank page with Chrome browser
5. Ensure you do not see an alert

DM-1851: Add IE alert to Shark Tank and edit copy

---

Gemfile
Gemfile.lock

https://agile6.atlassian.net/browse/DM-1850
adds `route_downcaser` gem to make urls in application case insenitive
- `bundle install`
- restart server
- browse to: http://localhost:3200/Competitions/Shark-Tank
- ER: shark tank page should come up
- you can do this for any url with any case

DM-1850: add downcaser gem for case insensitive urls

---

app/views/active_admin/resource/_page_image_component_form.html.arb

N/A
This PR sets the 'center' option as the default alignment in the select dropdown for the page image component.
2. Go to /admin/pages
3. Edit a page
4. Add an image component
5. Ensure that the default is set to 'Center'
6. Ensure that saving the image component renders a centered image on the page.

DM-1777: Set default alignment for PageImageComponent

---

lib/tasks/departments.rake

https://agile6.atlassian.net/browse/DM-1878
https://docs.google.com/spreadsheets/d/1YvpSoc9BHHbl-kEXq69m7ML17RxDfVXp5_2BT5hxBAs/edit#gid=1924758396
**Warning:** if this fails, may need to run `rails dm:reset_up`
**Note:** prod data may not match local data
1. run `rails departments:update_departments`
2. There will be some output:
1. the "FROM" output counts how many practices were in the old Department
2. The "TO" output counts how many practices are now in the new Department
1. This number should be the same or greater than the "FROM" output

DM-1878: task to move practices to departments based on ux spreadsheet

---

.gitignore
app/controllers/system/status_controller.rb
app/views/system/status/index.html.erb
config/routes.rb

https://agile6.atlassian.net/browse/DM-1885
creates the route `/system/status` to view when the application was deployed last, and a link to github of the most recent commits (REVISION number)
the plan is to run 
```
git rev-parse --verify HEAD | tee REVISION
```
at build time to get the `REVISION` file into the build for us to report on in the application
1. without the `REVISION` file created yet, as an admin, browse to `/system/status`
2. you should see "No REVISION file" for the two line items on the page
3. in your terminal, in the root of the application, run this command: `git rev-parse --verify HEAD | tee REVISION`. this will create the `REVISION` file in the root of your application for the application to read
4. refresh the `/system/status` page to see values for "Deployed at" …

DM-1885: system status: build revision number and deploy time

---

.circleci/config.yml

in theory, will cut build times to a third of the previous time (15 mins to about 5-7 mins), and lessen build failures in CircleCi

DM-DEVOPS: bump test machine size and add parallelism

---

app/views/practices/_show_authenticated.html.erb

https://agile6.atlassian.net/browse/DM-1974
renders paragraph breaks for practice summary
1. go to any practice edit page (i.e. http://localhost:3200/practices/preventing-contextual-errors-pce-program/edit/introduction)
2. In the "Summary" make some new lines and returns in the textarea
3. Save
4. Go to the show page (http://localhost:3200/practices/preventing-contextual-errors-pce-program)
5. should render the line breaks as you put them in the PE

DM-1974: render practice summary line breaks

---

app/views/practices/show/introduction/_introduction.html.erb

https://agile6.atlassian.net/browse/DM-1974
renders line breaks in the practice summary
1. go to any practice edit page (i.e. http://localhost:3200/practices/preventing-contextual-errors-pce-program/edit/introduction)
2. In the "Summary" make some new lines and returns in the textarea
3. Save
4. Go to the show page (http://localhost:3200/practices/preventing-contextual-errors-pce-program)
5. should render the line breaks as you put them in the PE

DM-1974: render line breaks for practice summary

---

README.md
app/views/practices/overview_forms/_image_form.html.erb
lib/tasks/dm.rake
lib/tasks/milestones.rake
lib/tasks/practice_multimedia.rake

[DM-2092, DM-2093] write tasks to create PracticeMultimedia from ImpactPhotos and VideoFiles
https://agile6.atlassian.net/browse/DM-2091
exactly what the title says it does
1. run `rails practice_multimedia:transfer_practice_impact_photos`
2.run `rails practice_multimedia:transfer_practice_videos`
3. you can run them again to make sure no duplicates get created
4. check a new practice view page (http://localhost:3200/practices/cards-for-connection) that was outputted in the log to see the multimedia section populated
5. check a new practice editor overview page (http://localhost:3200/practices/cards-for-connection/edit/overview) to see the multimedia section populated
n/a
As a user, I would like my video and pictures and comments to be ported over to the new practice pages so that I don't …

DM-2091: Map Impact Photos and videos to Multimedia

---

README.md
app/assets/stylesheets/dm/pages/_practice.scss
app/controllers/practices_controller.rb
app/models/practice.rb
app/views/practices/_adoption_form.html.erb
app/views/practices/_publication_validation_modal.html.erb
spec/features/practice_editor/publish_practice_spec.rb
spec/features/search_spec.rb

[DM-2071](https://agile6.atlassian.net/browse/DM-2071)
This PR requires a practice to have at least one adoption before publishing the practice.
Prereq: Have a practice that is unpublished
1. Log in as a user that can edit a practice.
2. Navigate to the edit page of your practice that is unpublished.
3. Try to publish without an adoption
4. Ensure you are unable to publish the practice and you see why you are unable to publish in the "Can't publish yet" modal
5. Add an adoption and any other required fields
6. Ensure the practice saves and publishes successfully

DM-2071: Require practices to have an adoption before publish

---

app/views/practices/_show_authenticated.html.erb

https://agile6.atlassian.net/browse/DM-2108
make origin title not required for origin story to show up on practice view
1. fill in origin story in a practice page (i.e. http://localhost:3200/practices/testing/edit/origin)
2. go to practice view (i.e. http://localhost:3200/practices/testing)
3. origin section should show up

DM-2108: Origin story bug

---

.gitignore
app/controllers/system/status_controller.rb
app/views/system/status/index.html.erb

https://agile6.atlassian.net/browse/DM-2098
adds a bit of information about the database file used to restore on the server
0. browse to http://localhost:3200/system/status
1. the "No REFRESHED_DB_WITH file" text should show up
1. in a terminal run  `echo Refreshed DB with vadm_db_backup at $(date +"%Y-%m-%d-%H%M-%Z") | tee REFRESHED_DB_WITH`
1. this mimics what the db backup/refresh script does in VAEC when the db is done being refreshed: what backup file was used and when
2. browse to http://localhost:3200/system/status
3. the DB Version should be populated on the right

DM-2098: add db backup information to system status page

---

app/assets/stylesheets/dm/_classes.scss
app/assets/stylesheets/dm/pages/_home.scss
app/assets/stylesheets/dm/variables/_colors.scss
app/controllers/home_controller.rb
app/views/home/index.html.erb
app/views/maps/diffusion_map.html.erb
app/views/shared/_header.html.erb
config/routes.rb
spec/features/home_map_spec.rb
spec/features/shared/header_spec.rb

[DM-2115](https://agile6.atlassian.net/browse/DM-2115)
This PR moves the homepage diffusion map over to its own page.
1. Go to the homepage.
2. Ensure the diffusion map no longer appears on the homepage.
3. Ensure the navigation has "Diffusion map" instead of "Shark Tank" and it redirects to the `/diffusion-map` page.
4. Ensure the new diffusion map banner links to the `/diffusion-map` page.
5. Ensure the banner is mobile friendly.
(Note: Virus icon disappears on smaller screen widths as discussed with Becca)
6. Ensure the diffusion map and filters load as intended on the `/diffusion-map` page.
[Figma](https://www.figma.com/file/FogT5mBUVl8rE7OgWDQWeJ/VADM?node-id=7011%3A4)
Conversation with Becca additional AC:

DM-2115: Move homepage map

---

Gemfile.lock
app/assets/javascripts/_introduction_image_editor.es6
app/assets/javascripts/_overview_image_editor.es6
app/assets/javascripts/practice_editor_utilities.es6
app/assets/javascripts/replies.es6
app/assets/stylesheets/dm/pages/_practice.scss
app/assets/stylesheets/dm_uswds/theme/_uswds-theme-custom-styles.scss
app/services/save_practice_service.rb
app/views/commontator/comments/create.js.erb
app/views/home/index.html.erb
app/views/practices/_practice_editor_sidenav.html.erb
app/views/practices/favorite.js.erb
app/views/practices/form/about.html.erb
app/views/practices/form/contact.html.erb
app/views/practices/form/implementation.html.erb
app/views/practices/form/overview.html.erb
app/views/practices/implementation_forms/_attachment_file_form.html.erb
app/views/practices/implementation_forms/_attachment_link_form.html.erb
app/views/practices/introduction_forms/_image_editor.html.erb
app/views/practices/overview_forms/_file_form.html.erb
app/views/practices/overview_forms/_form_actions.html.erb
app/views/practices/overview_forms/_image_form.html.erb
app/views/practices/overview_forms/_link_form.html.erb
app/views/practices/overview_forms/_video_form.html.erb
spec/features/practice_editor/introduction/image_editor_spec.rb
spec/features/practice_editor/overview/resource_file_spec.rb

This PR fixes the following:
- styling of the "See more" buttons for the "COVID-19" and "Diffusion map" banners on the home page
- removes the `aria-describedby` attribute on file inputs on the "Overview" and "Implementation" sections of the PE
- fixes the issue of uploading/deleteing multiple files on the "Implementation" section of the PE
- fixes an issue where a resource's(video, file, link, etc.) section title was not added/removed when expected.
- Minor styling changes for copy across the practice editor(`choose from folder`,` File` attachment link, label margins).
- Fixes styling for inputs and resource containers to ensure they coincide with UX mockups.
- fixes the issue of adding/deleting multiple link on the "Implementation" section of the PE
- fixes editing of saved practice …

Fix button style on homepage

---

app/assets/javascripts/diffusion_history/practice_map.es6

[DM-2147](https://agile6.atlassian.net/browse/DM-2147)
This PR zooms out the practice diffusion map so that when a practice has one adoption the practice map is not zoomed in to the street level. This PR also centers the map so that Alaska, Hawaii, and the continental US appear on practice page load.
1. Log in as a user that can view a practice.
2. Go to a practice with one adoption.
3. Ensure you can see Alaska, Hawaii, and the continental US on practice page load as well as the marker.
4. Go to a practice with multiple adoptions.
5. Ensure you can see Alaska, Hawaii, and the continental US on practice page load as well as the markers.

DM-2147: Zoom out practice diffusion map

---

app/views/practices/show/desktop_partials/_search_terms.html.erb
app/views/practices/show/mobile_partials/_search_terms.html.erb

[DM-2174
](https://agile6.atlassian.net/browse/DM-2174)
This PR changes the "tags" copy in the Practice View to "categories"
1. Log in as a user.
2. Go to a practice page with categories.
3. Ensure on the desktop view it says "CATEGORIES:" instead of "TAGS:"
4. Ensure on a mobile view it says "Search categories" instead of "Search tags"

DM-2174: Change tags to categories on practice page

---

app/admin/categories.rb
app/admin/departments.rb

[DM-2201](https://agile6.atlassian.net/browse/DM-2201)
This PR fixes the admin's ability in the admin panel to delete departments that have a practice associated with them.
1. Log in as a admin.
2. Edit a practice's departments on the Overview page.
3. Go to the admin panel's department page.
4. Ensure you can delete the department that you assigned to the  practice in Step 2.
5. Ensure you see a notice saying the Department was successfully deleted.
BONUS: Make sure when you delete a category in the admin panel you also see a notice saying the Category was successfully deleted.

DM-2201: Fix deleting dept assoc w/ practice in admin panel

---

app/assets/javascripts/_explore.es6
app/assets/stylesheets/dm/_classes.scss
app/assets/stylesheets/dm/components/_practice_card.scss
app/assets/stylesheets/dm/components/_profile.scss
app/assets/stylesheets/dm/components/_side-nav.scss
app/assets/stylesheets/dm/pages/_explore.scss
app/assets/stylesheets/dm/pages/_practice.scss
app/assets/stylesheets/dm/variables/_colors.scss
app/assets/stylesheets/dm_uswds/theme/_uswds-theme-custom-styles.scss
app/controllers/home_controller.rb
app/controllers/practices_controller.rb
app/controllers/users_controller.rb
app/helpers/navigation_helper.rb
app/models/category.rb
app/models/category_practice.rb
app/models/diffusion_history.rb
app/models/practice.rb
app/views/practices/_explore.js.erb
app/views/practices/_search.js.erb
app/views/practices/explore.html.erb
app/views/shared/_practice_card.html.erb
config/initializers/assets.rb
config/routes.rb
spec/features/explore_spec.rb
spec/features/search_spec.rb

[DM-2176](https://agile6.atlassian.net/browse/DM-2176)
This PR adds functionality for the "Explore all practices" page.
In addition, this PR also addresses the following:
- practice card styling changes - on desktop view, practice cards take up full width of the container
- scss color variable update
- caches practices based on 3 sorting options
- resets the cache when a `CategoryPractice` and `DiffusionHistory` are updated/deleted
**Explore all practices**
1. Visit `/explore`
2. Ensure you do not see any breadcrumbs from previous site navigation
3. When first loading or reloading the "Explore all practices" page, check the following:
- no categories are selected
- the sort option is set to "Sort by A to Z"
- the total results count = total number of published practices in your local DB
- …

DM-2176: Add explore all practices page

---

app/models/application_record.rb

[DM-2246](https://agile6.atlassian.net/browse/DM-2246)
This code extends the expiration time of the Amazon s3's presigned urls that our app generates from 900 seconds to 86400 seconds or 1 day.
1. Go to a practice with a file that can be downloaded.
2. Make sure the file can be opened and viewed
3. If you want, I guess you can see after a day if it expires haha 😅 or you can change the expires_in time to see that it expires correctly.
4. Try steps 1 - 2 for other practices as well

DM-2246: Extend s3 expiration for presigned urls

---

app/admin/dashboard.rb
app/controllers/practices_controller.rb
app/helpers/practice_editor_sessions_helper.rb
app/models/practice.rb
app/models/practice_editor_session.rb
app/models/user.rb
app/views/layouts/_ahoy_event_tracking.js.erb
app/views/practices/form/_practice_last_updated.html.erb
app/views/practices/show/authenticated/_ahoy_event_tracking.js.erb
app/views/practices/show/authenticated/_show_authenticated.html.erb
spec/helpers/practice_editor_sessions_helper_spec.rb

[DM-2369](https://agile6.atlassian.net/secure/RapidBoard.jspa?rapidView=22&projectKey=DM&modal=detail&selectedIssue=DM-2369)
This PR allows for the following:
- not double count "Practice show" visits when clicking on a practice's practice card
- filter site visits by the `is_duplicate` property so we do not count those visits that were corrected by this [script](https://agile6.atlassian.net/browse/DM-2375). (**NOTE**: The way we are currently fetching "Practice show" counts on the metrics page -- we may want to refactor later to use the same queries throughout the codebase--meant we did not need to explicitly filter by the `is_duplicate` property added by this [script](https://agile6.atlassian.net/browse/DM-2374).) We needed to filter by the is_duplicate property when getting practice …

DM-2369: Fix site and practice show visit counts

---

app/views/layouts/_ahoy_event_tracking.js.erb

This PR ensures the previous page isn't tracked when clicking on internal links.
Prereq:
1. Make sure your local COVID-19 page has a `PageSubpageHyperlinkComponent` that links to a custom subpage like `/covid-19/telehealth`
Testing Steps
1. Log in as a user.
2. Click on the "COVID-19" homepage banner link.
3. Check in the admin dashboard custom page traffic that only the view count for `covid-19` increased by 1
4. Now click on the subpage hyperlink like `/covid-19/telehealth`
5. Check in the admin dashboard custom page traffic that only the view count for `covid-19/telehealth` went up by 1 and that `covid-19` view count remains the same as step 3
6. Now go to a practice page
7. Open your `ahoy_events` table and ensure only the visit for the show page was tracked
8. Click on "Edit …

DM-2397: Fix page tracking

---

app/models/concerns/external_url_validator.rb
app/models/page_image_component.rb
app/views/active_admin/resource/_page_image_component_form.html.arb
app/views/page/_page_image.html.erb
app/views/page/show.html.erb
db/migrate/20210406142716_add_url_to_page_image_component.rb
db/schema.rb
spec/features/pages/show_page_spec.rb
spec/models/concerns/external_url_validator_spec.rb

[DM-2469](https://agile6.atlassian.net/browse/DM-2469)
This PR adds the ability to add a link to a `PageImageComponent`. The link can be an internal or external one.
2. Go to `/admin/pages` and edit a page.
3. Add an image component without a URL.
4. Ensure the show page of the custom displays the image correctly and it has no URL.
5. Go to `/admin/pages` and edit the same page.
6. Add/Change the image component to include an internal URL.
7. Ensure the show page of the custom displays the image correctly and when you click it it leads to the internal page you designated.
8. Go to `/admin/pages` and edit the same page.
9. Add/Change an image component to include an external URL.
10. Ensure the show page of the custom displays the image correctly and when you click …

DM-2469: Add URLs to PageImageComponents

---

Gemfile.lock

N/A
Update `mimemagic` gem to `0.3.10` to resolve build issues since current mimemagic version (0.3.6) is missing.

Update mimemagic to v0.3.10

---

app/views/shared/_header.html.erb
spec/features/shared/header_spec.rb

[DM-2480](https://agile6.atlassian.net/browse/DM-2480)
This PR adds "Vaccine Acceptance" nav link to the header
PREREQ:
1. Add and publish page to the "covid-19" page group called "vaccine-acceptance"
TESTING
1. Log in as a user
2. In any page you should see the, "Vaccine Acceptance" link
3. Clicking it should redirect you to the page and the breadcrumbs should look good
Desktop - Hover over link
Mobile

DM-2480: Add "Vaccine Acceptance" to nav header

---

app/admin/visn_liasons.rb
app/views/visns/show.html.erb
spec/features/admin/admin_visn_liaisons_spec.rb

[DM-2466](https://agile6.atlassian.net/browse/DM-2466)
This PR adds the "Visn Liaison" tab to the admin dashboard. This PR adds the ability to perform CRUD operations for a `VisnLiaison`.
1. Log in as an admin and navigate to `/admin/visn_liaisons`
2. You should be able to add a new VISN liaison as well as edit and delete them
3. When you try to create or edit another user and set them as a "Primary" contact for a VISN that already has a primary contact that you see an error
4. You should be able to "Make Secondary" any VISN liaison
5. Check a specific VISN page with only "Secondary" VISN liaisons and make sure you do not see a VISN Liaison section

DM-2466: Add Visn Liaison CRUD to active admin

---

app/admin/practices.rb
app/mailers/commontator/subscriptions_mailer.rb
app/models/commontator/subscription.rb
spec/features/admin/admin_spec.rb
spec/features/practice_viewer/contact_spec.rb

https://agile6.atlassian.net/browse/DM-2651
1. Adds the practice owner to the list of email recipients when a comment is created for a practice, unless they are already subscribed to the thread.
2. Adds the practice's `support_network_email` to the list of email recipients when a comment is created for a practice, unless a `user` exists with the same email address AND that user is already subscribed to the thread.
_**Subscribing/Unsubscribing Practice Owner**_
1. Log in as an admin and visit `/admin/practices/new`.
2. Create a new practice with a user that has a `va.gov` email address (ex: test@va.gov).
3. Open up the rails console.
4. Run `Practice.last.commontator_thread.subscribers` and make sure the only subscriber is the `practice.user`.
5. Update the same practice with a new …

DM-2651: Wrote some unit tests and refactored some code

---

app/controllers/home_controller.rb
app/views/maps/diffusion_map.html.erb
spec/features/home_map_spec.rb

[DM-2670](https://agile6.atlassian.net/browse/DM-2670)
This PR replaces the banner on the diffusion map page with counts of successful, unsuccessful, and in-progress adoptions.
1. Go to `/diffusion-map`
2. You should now see adoptions counts as the copy instead of a gold banner.
[Figma](https://www.figma.com/file/xjaSwxytWsGGGCcc9f9Yfa/Desktop?node-id=7%3A49)
*Note: This PR only addresses the copy change and NOT the rebranding changes in this Figma.

DM-2670: Update diffusion map copy

---

Gemfile.lock
app/views/commontator/comments/_form.html.erb
app/views/commontator/comments/_show.html.erb
app/views/commontator/comments/_votes.html.erb
app/views/commontator/threads/_show.html.erb
app/views/practices/show/contact/_contact.html.erb
db/schema.rb
spec/features/practice_viewer/contact_spec.rb
spec/features/retire_practice_spec.rb

https://agile6.atlassian.net/browse/DM-2726
This code identifies if the current user is a "public" user and if so disables the ability to comment or reply to the Practice comment's section on the Practice show page.  User can still view previous comments but comments are read only and they can not create new comments on the practice.  Edit and delete links are disabled.
1.  Login to DM as a a non "ntlm" user.  i.e., non-gfe or cag user.  Following method should return nil for user in the application controller.  This will set the current user to a "public" user.
2.  Navigate to a Practice show page that contains comments.  
3. Scroll down to the pages "Contact / Comment" section.  Since you are logged in as a public user you should see the INformation banner stating that "Comments and …

Dm 2726 - Disable ability to comment for public users.

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/views/commontator/comments/_show.html.erb
app/views/commontator/comments/_votes.html.erb
config/environments/test.rb
spec/features/admin/admin_spec.rb
spec/features/practice_viewer/contact_spec.rb
spec/spec_helper.rb

https://agile6.atlassian.net/browse/DM-2313
When public users visit a Practice's show page the Comments section displays as an anonymous user i.e., "VA User" instead of the VA user's actual name for all comments.  The users role does display.
1.   Login to DM as a public user.
2.  Visit any Practice's show page that has comments.
3. Ensure that the user who created the comments name is anonymized and displays as "VA User".
4. Ensure that the user's role does display - i.e., "Practice Owner, Practice Adopter ...etc".
5. Ensure that nested comments are anonymized as well.
Comments are anonymized for public facing users
Commentor name reads as “VA User”
Role in practice implementation displays
Test on Dev when it’s public

Dm 2313 - Make VA employee comments anonymized for public users

---

app/admin/practices.rb
app/assets/stylesheets/active_admin.scss
app/models/diffusion_history.rb
app/models/practice.rb
app/views/practices/show/authenticated/_practice_status_banner.html.erb
app/views/practices/show/authenticated/_show_authenticated.html.erb
db/migrate/20210817165620_add_hidden_to_practices.rb
db/schema.rb
spec/features/admin/admin_spec.rb
spec/features/practice_spec.rb

[DM-2797](https://agile6.atlassian.net/browse/DM-2797)
This adds the ability to hide a practice from search results but let it remain viewable to any user.
1. Go to `/admin/practices`
2. Click "Hide" on a practice
3. Go to that practice's show page and ensure you see the "Hidden" banner
4. Then try to search for that practice in any of the searches (visn, facilities, regular search) and it should not appear as a result
5. Go back to `/admin/practices`
6. "Show" the practice
7. Search for the practice in the different searches and it should appear
8. Go to the practices show page and ensure you no longer see the "Hidden" banner

DM-2797: Add hidden practice feature

---

app/admin/topics.rb
app/controllers/home_controller.rb
app/models/topic.rb
app/views/home/index.html.erb
db/migrate/20210910151628_create_topics.rb
db/schema.rb
spec/features/admin/admin_topics_spec.rb

[DM-2801](https://agile6.atlassian.net/browse/DM-2801)
- adds ability to add featured topics via the admin panel
- dynamically displays topic on homepage
- Ensure you do not see featured topic section on homepage
- Go to `/admin/topics`
- Add a new topic and feature it
- Check the homepage to see the topic is featured
- Add a new topic again and feature it -- it should automatically unfeature the previous featured topic
- Check the homepage to see the topic is featured
- Make sure editing the topic works
- Make sure internal and external url works
- [] Once selected as “Featured” they are prompted with above info
- [] e2e/accessibility tests written (if applicable)

DM-2801: Add featured topic functionality

---

app/controllers/session_timeout_controller.rb
app/models/concerns/internal_url_validator.rb
config/initializers/active_admin.rb
config/locales/devise.en.yml
lib/modules/internal_url_utils.rb
spec/models/concerns/internal_url_validator_spec.rb

[DM-2924](https://agile6.atlassian.net/browse/DM-2924)
This PR accomplishes the following:
1. sanitizes the session timeout URLs before displaying it to the users
2. Ensures internal url validations are more robust
3. Runs the session timeout poller in the /admin routes
**Page Builder Component**
1. Log in as an admin user
2. Go to edit a Page component
3. Add the "Subpage Hyperlink" component and save the page (try `/`, `/diffusion-map`, `/innovations/flow3`, `/admin/users/1/edit`, `/visns/1`, page builder pages etc... try a bunch of valid links)
4. It should save successfully
5. Edit the "Subpage Hyperlink" component with invalid links (try `/non-existant-url`, `/visns/3`, `path-name-with-no-forward-slash`, `/innovations/fake-innovation` etc...)
6. This should throw an error
**Admin …

DM-2924: Sanitize session timeout URLs

---

app/controllers/practices_controller.rb

[DM-2969](https://agile6.atlassian.net/browse/DM-2969)
This PR invalidates the practices json cache after 12 hours even if select practice fields have not been updated. This is to ensure the AWS URLs for the practice's main display images for the practice have not expired.
- In the practices_controller change the expires_in value to something you can test like `1.minutes`.
- Have a rails console open
In the console
- run `Rails.cache.clear`
- run `Rails.cache.redis.keys` and make sure you do not see any keys
- Go to the search page
In the console
- run `Rails.cache.redis.keys` and make sure you see keys
- after 1 min,  run `Rails.cache.redis.keys` and make sure you do not see any keys
- Reload the search page
In the console
- run `Rails.cache.redis.keys` and make sure you see keys

DM-2969: Invalidate practices json cache every 12 hours

---

app/views/page/show.html.erb

https://agile6.atlassian.net/browse/DM-3019
Removes extra underline from page-builder's `SubpageHyperlink` component.
1. If you don't have a page-builder page that contains a subpage hyperlink, log in as an admin, add one, and then visit the page.
2. Make sure you don't see the extra small line at the end of the text.
Before:
After:
https://www.figma.com/file/H2aII1WHRlySNG6r2HlZbY/Sitemap?node-id=1431%3A5109
- Remove the little line from the end of a PB link

DM-3019: Removed extra underline from subpage hyperlink component

---

app/assets/javascripts/_otherCategories.es6
app/views/practices/_search.js.erb
app/views/practices/search.html.erb
spec/features/search_spec.rb

N/A
This PR fixes the issue on the search page where if users selected "All clinical" or "All strategic" or "All operational" category filters it would not select all categories.
Ensure you can select all categories using the checkbox and the search works.
Ensure you can deselect all categories all the checkboxes are unselected.
Do this on both the search page and the innovation's introduction edit page.

DM-3009: Fix all parent categories filter select in search

---

app/assets/javascripts/_page_show.es6
app/assets/stylesheets/dm/_classes.scss
app/assets/stylesheets/dm/components/_breadcrumbs.scss
app/assets/stylesheets/dm/components/_gradient_banner.scss
app/assets/stylesheets/dm/pages/_home.scss
app/assets/stylesheets/dm/pages/_page_builder.scss
app/assets/stylesheets/dm_uswds/theme/_uswds-theme-custom-styles.scss
app/controllers/page_controller.rb
app/helpers/navigation_helper.rb
app/views/layouts/application.html.erb
app/views/maps/diffusion_map.html.erb
app/views/page/show.html.erb
app/views/practice_partners/index.html.erb
app/views/practice_partners/show.html.erb
app/views/practices/search.html.erb
app/views/shared/_breadcrumbs.html.erb
app/views/shared/_text_breadcrumb.html.erb
app/views/users/show.html.erb
app/views/va_facilities/index.html.erb
app/views/va_facilities/show.html.erb
app/views/visns/index.html.erb
app/views/visns/show.html.erb
spec/features/pages/show_page_spec.rb
spec/features/shared/breadcrumbs_spec.rb

[DM-2985](https://agile6.atlassian.net/browse/DM-2985)
This PR updates the following:
- styling of the breadcrumbs to match the figma designs
- breadcrumbs have not been updated for the innovation show and edit pages
- page builder pages and all other pages use the same breadcrumb logic
- Check the practice show and edit pages to ensure the breadcrumbs have not changed
- Check the partners index and show pages to ensure the breadcrumbs match the designs
- Check the diffusion map, facility show and index, and VISN show and index pages to ensure the breadcrumbs match the designs
- Check the page builder pages and landing pages to ensure breadcrumbs appear as intended
[Figma](https://www.figma.com/file/H2aII1WHRlySNG6r2HlZbY/Sitemap?node-id=1408%3A4059)
- [] Unit tests written (if …

DM-2985: Update breadcrumb styles for non innovation pages

---

app/views/shared/_breadcrumbs.html.erb

[DM-3093](https://agile6.atlassian.net/browse/DM-3093)
Removes extra padding in gradient banners
Check the individual partners page or a page builder page with breadcrumbs and the title that is visible
**Before**
**After**

DM-3093: Fix styles for gradient banner breadcrumbs

---

app/controllers/terms_and_conditions_controller.rb
app/helpers/application_helper.rb
app/helpers/navigation_helper.rb
app/views/shared/_footer.html.erb
app/views/shared/_terms_and_conditions_modal.html.erb
app/views/terms_and_conditions/index.html.erb
config/routes.rb
spec/features/shared/footer_spec.rb
spec/features/terms_and_conditions_spec.rb
spec/helpers/application_helper_spec.rb

[DM-2994](https://agile6.atlassian.net/browse/DM-2994)
This PR does the following:
- updates the terms and conditions modal to use the updated forced action modal style
- adds a terms and conditions page
**User that did not accept terms**
1. Log in as a user that did not accept the terms and conditions.
2. Go to various pages and you should see the terms and conditions modal on every page
3. Agree to the terms and conditions
4. Navigating to different pages should not show the modal
5. Clicking on the terms and conditions link in the footer navigates to the terms and conditions page
**Public "user"**
1. Do not be signed in as any user
2. Navigate to any page on the site
3. You should not see a terms and conditions modal
4. Clicking on the terms and conditions link in the footer navigates …

DM-2994: Add terms and conditions page & update modal

---

app/assets/stylesheets/dm/pages/_practice_partners.scss
app/controllers/practice_partners_controller.rb
app/views/page/_practice_list_container.html.erb
app/views/page/show.html.erb
app/views/page/show.js.erb
app/views/practice_partners/show.html.erb
app/views/practice_partners/show.js.erb
app/views/shared/_practice_cards_row.html.erb
spec/features/pages/show_page_spec.rb
spec/features/practice_partners_spec.rb

[DM-3090](https://agile6.atlassian.net/browse/DM-3090)
This PR paginates the innovations cards on the partners show page. On page load, it paginates the innovation cards if there are more than 12. Clicking "Load more" shows another 12 cards. It also shows the appropriate public or all innovation cards associated with a partner for a logged in user vs. a public user.
As a logged in user
- Go to a partner's show page and ensure all practices associated with that partner are appearing
- Ensure any pagination is correct
As a public user
- Go to a partner's show page and ensure only public practices associated with that partner are appearing
- Ensure any pagination is correct
page builder page with innovation cards
- ensure innovation cards are correctly being paginated on page builder pages

DM-3090: Paginate partners page innovation cards

---

app/views/practice_partners/show.html.erb
spec/features/practice_partners_spec.rb

Ensures pagination only appears on partners pages with more than 12 innovations

DM-3090: Fix pagination for < 12 innovations on partners pg

---

app/assets/stylesheets/dm/components/_prose.scss
app/assets/stylesheets/dm/components/_step_indicator.scss
app/controllers/practices_controller.rb
app/helpers/navigation_helper.rb
app/views/home/index.html.erb
app/views/practices/form/_practice_last_updated.html.erb
app/views/practices/form/about.html.erb
app/views/practices/form/adoptions.html.erb
app/views/practices/form/contact.html.erb
app/views/practices/form/editors.html.erb
app/views/practices/form/implementation.html.erb
app/views/practices/form/instructions.html.erb
app/views/practices/form/introduction.html.erb
app/views/practices/form/metrics.html.erb
app/views/practices/form/overview.html.erb
app/views/practices/shared/_step_indicator.html.erb
app/views/practices/show/show.html.erb
app/views/shared/_breadcrumbs.html.erb
spec/features/practice_editor/metrics_spec.rb
spec/features/practice_editor/step_indicator_spec.rb
spec/features/shared/breadcrumbs_spec.rb

[DM-3138](https://agile6.atlassian.net/browse/DM-3138)
This PR addresses the following:
- adds the step indicator to the innovation editor pages
- removes breadcrumbs from innovation editor pages
1. Log in as a user that can edit an innovation
2. Go to the editor pages of an innovation
3. Ensure the "last updated..." text matches the format in [Figma](https://www.figma.com/file/ccwLbt94U9QGfnuFCwOXzY/VA-Diffusion-Marketplace---Final-Designs?node-id=680%3A1021)
4. Ensure the step indicator designs matches the format in [Figma](https://www.figma.com/file/ccwLbt94U9QGfnuFCwOXzY/VA-Diffusion-Marketplace---Final-Designs?node-id=680%3A1021)
Note: The metrics page needs to be updated. This will be done in a separate story.
[Figma](https://www.figma.com/file/ccwLbt94U9QGfnuFCwOXzY/VA-Diffusion-Mar …

DM-3138: Add step indicator to innovation editor

---

app/models/application_record.rb

N/A
Expires the s3 signer cache in 60 minutes rather than 5 minutes
Ensure you can still crop images successfully and images continue to load as expected

Extend s3 signer cache expiration to 60 mins

---

lib/middleware/ntlm-sso.rb

Added return statement for internal auth.
NA
Adds the return statement so internal users can be authenticated.  Without the return statement... internal users fall in to the public access method.. and are public users.
- internal users get logged in via ldap and have internal permissions.

dm-fix-middleware

---

app/controllers/practices_controller.rb
app/helpers/navigation_helper.rb
config/routes.rb
spec/features/practice_editor/session_spec.rb
spec/features/search_spec.rb

https://agile6.atlassian.net/browse/DM-3178
This PR is a follow up to #468 / DM-3178. DM-3178 combined the Contact and About editor pages. This PR removes some related code in the practices controller, routing, and breadcrumb nav.
1. Sign in as a user that can edit an innovation
2. Navigate to innovations/#{practice name}/edit/contact. You should receive an error

Remove deprecated Contact editor page routing

---

app/assets/javascripts/_header_utilities.es6
app/assets/javascripts/_practice_editor_header.es6
app/assets/javascripts/_terms_and_conditions.es6
app/assets/javascripts/shared/_utilityFunctions.es6
app/views/practices/shared/_editing_guide_modal.html.erb
app/views/visns/_show.js.erb

Fixes modal flicker issue for editing guide modal and cleans up modal flicker code.
1. Log in as an admin-level user and visit the homepage. Make sure the crisis line and terms & conditions modals do not flicker. You can refresh the page multiple times to confirm.
2. Visit the practice editor introduction page for any practice and make sure both the editing guide and close modals do not flicker. You can refresh the page multiple times to confirm.
3. Visit the show page for any VISN and make sure the complexity modal does not flicker. You can refresh the page multiple times to confirm.

Fixed modal flicker issue for editing guide modal and cleaned up code

---

app/helpers/active_admin_helpers.rb
app/models/va_facility.rb

[DM-3454](https://agile6.atlassian.net/browse/DM-3454?atlOrigin=eyJpIjoiOTViODI3NDQ1Yzc5NDJmMmI5N2ZiNjk5YzFlNzNhNDYiLCJwIjoiaiJ9)
Added STA3N and originating facilities to QUERI adoption download in admin panel
2. Create multiple origin locations for a particular practice that has been adopted
3. Go to `/admin/adoptions`
4. Click on `QUERI Download` button
5. Check that STA3N and Originating Facilities columns have been created and populated, i.e. multiple originating facilities are in a comma-delimited list within the Originating Facilities column
6. Verify all other data is correct
N/A
- Add Originating Facility (some have more than one) for the adopted Innovation to Adoptions QUERI Dataset
- Add STA3N to Adoptions QUERI dataset (Parent)
-We should be seeing 136 …

DM-3454: Added STA3N and originating facilities to QUERI adoption download

---

lib/tasks/dm.rake

[DM-3477](https://agile6.atlassian.net/browse/DM-3477?atlOrigin=eyJpIjoiMTMwYjE2OWJjNDVlNGI5NTkyMTVmZGIzNzdlZjJlMTMiLCJwIjoiaiJ9)
This PR adds clinical resource hub creation to the `full_import` task used in local dev. This fixes a local development issue where the VISN index threw an error for public users.
1. In your local dev environment run `rails dm:reset_up` (this destroys the current data and runs `full_import`).
2. As a public user, click on the VISN index. No errors should occur and several VISNs should be visible.
3. Go to the Facilities Index. Several Clinical Resource Hubs should be visible at the bottom of the list.

Add CRH creation to full import task

---

app/assets/javascripts/_page_show.es6
app/assets/javascripts/active_admin.js
app/helpers/application_helper.rb
app/views/page/show.html.erb
spec/features/pages/show_page_spec.rb

[DM-3473](https://agile6.atlassian.net/browse/DM-3473?atlOrigin=eyJpIjoiYzgyYTc0YjNjZTI1NDI3ZGE3ZjBhYjQ3YTlkMjYxMzgiLCJwIjoiaiJ9)
This code handles accessibility best practices for Page Builder links. 
- Remove "Open link in" option from TinyMCE editor 
- Remediate legacy data without a db update (e.g.internal links set to open in a new tab; external links set to open in the same tab)
- Identify external links
- Apply USWDS styling so these links receive an icon
-  set to open in a new tab
- Identify internal links
- add `.usa-link` styling so that links get `:hover` and `:visited` styles
- unset any instances of `target='_blank'`
I looked into a Rails approach to doing this but decided to take the JS route. Hopefully this means we won't need to remember to reimplement accessible link …

DM-3473: Ensure that PageBuilder links use appropriate target and styling

---

spec/spec_helper.rb

This is a small tweak for developer experience. By running our tests with `:selenium_chrome_headless`, developers can run tests locally without the browser taking over the mouse. This increases our ability to multitask while tests are running. My initial tests indicate that test suite times and flaky test rates are similar. 
I commented out `:selenium_chrome` and left it in the code because it may still provide utility while debugging tests locally. For example, a developer can debug a flaky test by adding `byebug` to the middle of a test and inspect markup in the browser.
1. Run `bundle exec rspec` in your local dev environment.
2. You should be able to use Chrome for other work while running the test suite.

Run tests with a headless driver

---

app/assets/javascripts/_page_show.es6
app/views/page/show.html.erb
spec/features/pages/show_page_spec.rb

https://agile6.atlassian.net/browse/DM-3592
Create anchor # links to jump to a particular element/component on the same page or when a page loads.
**Note to Devs**: PB show page /app/views/page/show.html.erb must have an element (<div, ..etc) with an id that is generated dynamically for each instance of the component. For example if there are 5 accordion components on the same page a counter can be used to generate unique IDs for each accordion component - i.e.,
<% when 'PageAccordionComponent' %>
<% accordion_ctr += 1 %>
<div id="accordion_anchor_<%= accordion_ctr %>"/>
So the unique id for each accordion component is "accordion_anchor_1", "accordion_anchor_2", "accordion_anchor_3" ... and so on.  See page/show.html.erb for code above.  This same technique can be used to create anchor …

Dm 3592 anchor tags

---

app/assets/stylesheets/dm/components/page_component.scss
app/views/page/_compound_body_component.html.erb
spec/features/pages/show_page_spec.rb

https://agile6.atlassian.net/browse/DM-3626
Makes adjustments to the column widths for the `PageCompoundBodyComponent`
1. Log in as an admin and create/edit a Page via `/admin/pages`.
2. Add two or more "Text and Images" components. For at least one of them, be sure to NOT add any images.
3. Once you've got them added to the Page, visit that Page's show page and confirm the following:
- For a `PageCompoundBodyComponent` that only has text, that text should take up eight columns.
- For a `PageCompoundBodyComponent` that has text AND image(s), the text should take up six columns, the image(s) should take up five columns, and there should be one column of space in between them.
- Each column should have a gutter size of `24px`.
- Grid for component should have a 24px gutter (grid gap)
- …

DM-3626: Refactored grid column setup for 'CompoundBody' component

---

app/admin/pages.rb
app/assets/stylesheets/dm/components/page_component.scss
app/models/page_compound_body_component.rb
app/views/active_admin/resource/_page_compound_body_component_form.html.arb
app/views/page/_compound_body_component.html.erb
app/views/page/show.html.erb
db/migrate/20221013211727_rename_margin_columns_for_page_compound_body_components.rb
db/schema.rb
spec/features/admin/admin_page_spec.rb
spec/features/pages/show_page_spec.rb
spec/models/page_compound_body_component_spec.rb

https://agile6.atlassian.net/browse/DM-3640
https://agile6.atlassian.net/browse/DM-3638
1. Changes the `margin_bottom` and `margin_top` columns for the `PageCompoundBodyComponent` to `padding_bottom` and `padding_top`, in order to allow for stackable spacing between multiple `PageCompoundBodyComponent`'s.
2. Fixes the issue where the caption for a `PageCompoundBodyComponent`'s `PageComponentImage` was not being included in the overall height of the container for the text and image.
_**PREREQUISITE:**_ Run `rails db:migrate` in the terminal.
1. Log in as an admin and visit `/admin/pages` and either create or edit a page.
2. Select two or more "Text and Images" components.
3. Scroll down and you should now see "MARGIN BOTTOM" and "MARGIN TOP" have now been replaced with "PADDING BOTTOM" and …

Dm compound body spacing fix

---

app/controllers/page_controller.rb
spec/requests/page_controller_spec.rb

Fixes a small issue with the `/communities` redirect code.
**PREREQUISITE:** Make sure you have at least two Pages, one that has the slug of `home` with a `PageGroup` of `xr-network`, and a different slug (e.g. `events`, `news`, `some-random-slug`) with a `PageGroup` of `xr-network`.
1. Log in as an admin (unless your Pages are published).
2. In the URL bar, enter `http://localhost:3200/xr-network` and then hit enter. Make sure you are now redirected to `/communities/xr-network`, as opposed to `/communities/xr-network/home`.
3. In the URL bar, enter `http://localhost:3200/xr-network/#{slug of the other Page mentioned in step 1}`. Make sure you are redirected to `communities/xr-network/#{slug of the other Page mentioned in step 1}` as expected.

Communities redirect fix

---

app/helpers/application_helper.rb
app/views/layouts/application.html.erb
spec/features/analytics.rb

[DM-3628](https://agile6.atlassian.net/browse/DM-3628)
- Adds an application helper to define which pages should be excluded from Google Analytics
- Adds a snippet to the application view template
TODO:
1. Go to the homepage. Open the inspector and look for the `` comment in `<head>`.
There should be no snippets in the following:
1. a non-public practice
1. practice editor
1. admin pages
1. unpublished PageBuilder pages

Add DAP GA analytics snippet to app template

---

app/assets/javascripts/_practice_card_utilities.es6
app/assets/stylesheets/dm/components/_practice_card.scss
app/views/practices/_search.js.erb
app/views/shared/_practice_card.html.erb

https://agile6.atlassian.net/browse/DM-3697
Adjusts practice origin text styles to better reflect mockups
1. Make sure you have at least one practice with multiple originating facilities (2-3 with long names/3-4 with short names).
2. Log in and visit `/search`. Filter for the practice from step 1 and make sure the ellipsis is visible for the origin text and that the text styles match the Figma designs.
3. Edit the practice from step 1 and assign the QUERI practice partner to it. Now visit `/partners/quality-enhancement-research-initiative` and confirm the ellipsis is visible for the origin text and that the text styles match the Figma designs.
https://www.figma.com/file/dkvSpADVqwN5KKByF1TVIa/Design-System---VA-DM?node-id=1305%3A334&t=Gm3JO466s0d38ibE-0
- Running AXE DevTools scan on page …

DM-3697: Adjust practice origin text styles to better reflect mockups

---

.github/workflows/run-tests.yml

Part 1  of [DM-3780](https://agile6.atlassian.net/browse/DM-3780?atlOrigin=eyJpIjoiZDM5NTA1MGNkZGVjNDI4ZTljMGVkMTI5ZTRjZTlmYWMiLCJwIjoiaiJ9)
- Adds a GitHub Workflow for running tests 
- After merging PR, info about this workflow should appear in the [Actions tab for this repo](https://github.com/department-of-veterans-affairs/diffusion-marketplace/actions) (similar to our CodeQL workflow)

DM-3780: Add GitHub Actions workflow for running tests

---

app/controllers/page_controller.rb
app/views/about/index.html.erb

- Reverts #590
- Updates links to VHA Innovation Ecosystem (flagged by [failing test](https://app.circleci.com/pipelines/github/department-of-veterans-affairs/diffusion-marketplace/5794/workflows/fe5854df-1e6e-4709-9188-2e012f2fa129/jobs/7359/parallel-runs/45/steps/45-109))
Remove redirect
- visit https://dev.marketplace.va.gov/competitions/shark-tank
- page should display a logo and a link to the 2023 competition info page
Update VHA Innovation Ecosystem
- Go to About page and click on links for `Diffusion of Excellence` and `VHA Innovation Ecosystem`. You should see the redesigned innovation ecosystem site instead of a redirect warning.

Remove temporary shark tank redirect from DEV to PROD

---

app/models/user.rb

[DM-3931](https://agile6.atlassian.net/browse/DM-3931?atlOrigin=eyJpIjoiNmMwNGMyMzYyODUwNDA4YmIyYTM5YmM4Y2M1NWY1MmYiLCJwIjoiaiJ9)
This PR allows us to create users for the rare VA user with an apostrophe in their email! 
In local development: 
1. Sign in > Register
2. Register a user with an apostrophe in their email name. (e.g. o'shea@va.gov). Add a valid password. 
3. You should get a new tab that simulates a confirmation email.
Example of successful user creation:

Allow emails with apostrophes

---

app/models/page_group.rb

- Adds VA immersive to community slugs. This makes pages available under `/communities/va-immersive` for the content team.
In local dev:
1. Create a page group named `va-immersive`
2. Create a new page. Set URL suffix to `home`. Add required title and description. Set page group to va-immersive.
3. Visit `/communities/va-immersive`. Your new page should load. 
4. Visit `/va-immersive`. The browser should redirect to `/communities/va-immersive`.
5. Create a second page. Set URL suffix to `events`. Add required title and description. Set page group to va-immersive.
6. Visit `/communities/va-immersive/events`. Your events page should load.
7. Visit `/va-immersive/events`. The page should redirect to `/communities/va-immersive/events`

Add VA Immersive to Communities list

---

app/models/page_header2_component.rb
app/models/page_header3_component.rb
app/views/active_admin/resource/_page_header2_component_form.html.arb
app/views/active_admin/resource/_page_header3_component_form.html.arb
app/views/page/show.html.erb
db/migrate/20230515234423_add_url_to_page_header2_component.rb
db/migrate/20230516000120_add_url_to_page_header3_component.rb
db/schema.rb
spec/features/pages/headings_spec.rb

[DM-3942](https://agile6.atlassian.net/browse/DM-3942?atlOrigin=eyJpIjoiMjBlZTI1MzM4ODc1NDgxY2JiZjZjMmYxOWVmMTgwZTgiLCJwIjoiaiJ9)
This PR updates the Heading2 and Heading3 components so that an editor can supply a link for each heading.
In local dev: 
1. run `rails db:migrate`
2. Create a new page group and page. Go to page editing UI
Heading 2
1. Create a Heading2 component with an internal URL 
1. Create a Heading2 component with an external URL 
1. Create a Heading2 component with no URL 
1. Confirm that links get appropriate styling (e.g. external URL should open in a new tab and get an icon)
Repeat for Heading3 component.

DM-3942: Support links in Heading2 and Heading3 PageBuilder components

---

Gemfile
Gemfile.lock

Address deprecation warning: 
```
[DEPRECATED] Your Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source.
```

Move rails-assets gems to a source block

---

app/views/page/_news_items_list.html.erb

https://agile6.atlassian.net/browse/DM-4006
Moves news component's body to above published date / authored by
1. Create page with news component
2. add body and published date
3. view the page and verify body is above published date
https://www.figma.com/file/ccwLbt94U9QGfnuFCwOXzY/Core-Designs---VA-DM?type=design&node-id=6181-38873&t=odXdjQxK4fxa7YeN-0

DM-4006: Move news component body above publish date / authors

---

app/admin/pages.rb
app/assets/javascripts/_page_show.es6
app/views/active_admin/resource/_page_map_component_form.html.arb
app/views/page/_page_map.html.erb
app/views/page/show.html.erb
db/migrate/20230609232224_add_text_alignment_to_page_map_component.rb
db/migrate/20230612222945_change_page_map_component_description.rb
db/schema.rb

[DM-3937](https://agile6.atlassian.net/browse/DM-3937?atlOrigin=eyJpIjoiMTRiNTBlNjVjMmY2NDA0ZDg0YmU3ZjJiYzFmNGI2MWIiLCJwIjoiaiJ9)
- Adds a text alignment field to PageBuilder Map Component
-  Converts description field to a WYSIWYG textarea so editors can add a link
1. Sign in as an admin user
2. Create a page group and test page
3. Add three Map components. 
4. Add titles and descriptions to each component.
5. Add a link to an external site to the description of one component. 
6. Add a link to an internal site (i.e. `/about`) to the description of one component
7. Select a different text alignment for each component description 
8. Save the page and confirm styling 
https://www.figma.com/file/ccwLbt94U9QGfnuFCwOXzY/Core-Designs---VA-DM?type=design&node-id=6181%3A38719&t=482uC53bBlMy2B7F- …

Add different column layout options to PB Map Component

---

Gemfile
Gemfile.lock

- Continues work from #602, where we addressed a deprecation warning in the Gemfile. We are now explicitly declaring any dependencies that are not loaded from rubygems.org. Previously, the application would look for dependencies in rails-assets.org if they were not found on rubygems. 
- addresses error from deployment:
```
Your bundle is locked to rails-assets-normalize-css (3.0.3) from rubygems
repository https://rubygems.org/ or installed locally, but that version can no
longer be found in that source. That means the author of
rails-assets-normalize-css (3.0.3) has removed it. You'll need to update your
bundle to a version other than rails-assets-normalize-css (3.0.3) that hasn't
been removed in order to install.
```
- `rails-assets-normalize-css` is an dependency of a dependency …

Force rails-assets-normalize-css to load from railsassets.org

---

app/views/active_admin/resource/_page_header3_component_form.html.arb
app/views/page/show.html.erb

- Removes the 'Right' text alignment option for Header 3 components, per designer request
- aligns the Header 3 description to the component
-  adds the Text and Images component to a `grid-containers`
1. create a new page group and page.
1. Add a Heading 3 component  with text alignment: center
1. Add a Text and Images component
1. Confirm that:
- heading 3 description is aligned with title
- all text and images component content has appropriate whitespace

Component alignment cleanup

---

app/views/page/_news_items_list.html.erb

https://agile6.atlassian.net/browse/DM-3941
swaps position of news pb component's title with it's image
1. create page w/ news component w/ image and title
2. verify the component renders with the title below the image
from application (if applicable)
https://www.figma.com/file/ccwLbt94U9QGfnuFCwOXzY/Core-Designs---VA-DM?type=design&node-id=6181-38719&mode=design&t=gDybDrtTPEizDN3C-0

moves news component titlte under pic

---

app/views/page/_two_to_one_image_component.html.erb

Small follow up to #629 
[DM-3948](https://agile6.atlassian.net/browse/DM-3948)
- Bolds URL text and adds bottom margin to bring it closer to Figma design
https://www.figma.com/file/ccwLbt94U9QGfnuFCwOXzY/Core-Designs---VA-DM?type=design&node-id=6181%3A38719&mode=design&t=ukbYyhEVY0aVzsHN-1

DM-3948: Bold and decrease margin on PageBuilder 2:1 component

---

app/views/page/_two_to_one_image_component.html.erb

Small follow up to #629 
[DM-3948](https://agile6.atlassian.net/browse/DM-3948)
- Updates 2:1 Image to Text component to align images with the top of the component container
https://www.figma.com/file/ccwLbt94U9QGfnuFCwOXzY/Core-Designs---VA-DM?type=design&node-id=6181%3A39179&mode=design&t=HjmE44OB3I9RHEoM-1

Align PageBuilder 2:1 Image to Text component towards top of container

---

app/admin/pages.rb
app/assets/javascripts/active_admin.js
app/models/concerns/text_and_image_component.rb
app/models/page_component.rb
app/models/page_one_to_one_image_component.rb
app/models/page_two_to_one_image_component.rb
app/views/active_admin/resource/_page_components_form.html.arb
app/views/active_admin/resource/_page_one_to_one_image_component_form.html.arb
app/views/page/_one_to_one_image_component.html.erb
app/views/page/show.html.erb
db/migrate/20230720184846_create_page_one_to_one_image_component.rb
db/schema.rb
spec/features/pages/one_to_one_image_spec.rb
spec/models/page_one_to_one_image_spec.rb

https://agile6.atlassian.net/browse/DM-4056
Adds new 1:1 Image To Text page-builder component
1. Create a group, create a page, add the group to the page
2. Add the new component, include a few sentences worth of text and a url
3. View the page and verify the component renders as seen in the screenshots below
4. Edit the component and set the text alignment to be on the right
5. View the page and verify the component renders with the text to the right of the image.
6. Using dev tools reduce the resolution to mobile view, verify the text changes position to be below the image, above if the text alignment is set to "Right".
https://www.figma.com/file/ccwLbt94U9QGfnuFCwOXzY/Core-Designs---VA-DM?type=design&node-id=6181-38719&mode=design&t=nCtYqPdvAf6SU5cQ-0

Dm 4056 create one to one pb component

---

app/views/page/_one_to_one_image_component.html.erb

Small addition to #635 
This moves the link in the 1:1 Image to Text component below the body text
https://www.figma.com/file/ccwLbt94U9QGfnuFCwOXzY/Core-Designs---VA-DM?type=design&node-id=6181%3A38719&mode=design&t=e7q0GZMOMgO0OVnq-1

Move link below body text for 1:1 Image and Text component

---

app/views/shared/_breadcrumbs.html.erb

[DM-4062](https://agile6.atlassian.net/browse/DM-4062?atlOrigin=eyJpIjoiYzQ4MTYyYjYyMTZhNDhhNjlhNmQyMWM1MDA0MWYwN2IiLCJwIjoiaiJ9)
- Increases the font size of the blue banner text across the application

DM-4062: Increase font size of blue banner subtext

---

app/views/page/show.html.erb

[DM-4064](https://agile6.atlassian.net/browse/DM-4064?atlOrigin=eyJpIjoiNDI5N2Y0NDUwOTBjNDg4YmJjOTJiYzZhZGVhYWFhNGYiLCJwIjoiaiJ9)
- Swaps out font classes for non-button text on the CTA PageBuilder component
https://www.figma.com/file/ccwLbt94U9QGfnuFCwOXzY/Core-Designs---VA-DM?type=design&node-id=6181%3A38719&mode=design&t=XAZpl8b9jfdjTvmU-1

Update styling of CTA non-button text

---

app/assets/stylesheets/dm/components/page_component.scss
app/views/page/_events_list.html.erb

[DM-4065](https://agile6.atlassian.net/browse/DM-4065?atlOrigin=eyJpIjoiMThjZjU2ZWNmOGFlNDYzYTk1ODU4MTdiNjZkZjYxMDkiLCJwIjoiaiJ9)
- Most of this is SCSS to undo whitespace styling from the USWDS Card component. Because these styles are shared by two not-exactly-similar components, I opted to do it in the stylesheet.
- aligns Event / News cards with the grid container's left margin
- updates markup and styling for Event date and location info
- generally reduces padding and margins within the card component to match the Figma design
- Sets line-height to `1.62px` across PageBuilder components ([DM-4066](https://agile6.atlassian.net/browse/DM-4066?atlOrigin=eyJpIjoiZWE4MTkzZGMyYzIxNDU5MzlkYjRhMmEyYTI0ZmI0ZTMiLCJwIjoiaiJ9)
https://www.figma.com/file/ccwLbt94U9QGfnuFCwOXzY/Core-Designs---VA-DM …

DM-4065: Adds SCSS to unset whitespace from USWDS card styling for PageBuilder News and Events

---

app/views/page/show.html.erb

[DM-4063](https://agile6.atlassian.net/browse/DM-4063?atlOrigin=eyJpIjoiYjQ2OWQ0MjE5ZTc4NDkyOWJlNDE4Y2Q3NDJlY2U5NjAiLCJwIjoiaiJ9)
Small visual design tweak. Removes letter spacing from block quote component
https://www.figma.com/file/ccwLbt94U9QGfnuFCwOXzY/Core-Designs---VA-DM?type=design&node-id=6181%3A38719&mode=design&t=XAZpl8b9jfdjTvmU-1

Remove letter spacing from PageBuilder BlockQuote component

---

app/assets/stylesheets/dm/components/page_component.scss
app/views/page/_publications_list_cards.html.erb

Add on to DM-4065 / #646 
- Adds visual design updates for USWDS card component styling to PageBuilder Publication component lists of <2. 
https://www.figma.com/file/ccwLbt94U9QGfnuFCwOXzY/Core-Designs---VA-DM?type=design&node-id=6181%3A38719&mode=design&t=BQ1YuZbZrRo0lRUx-1

DM-4065: Apply card whitespacing rules to PageBuilder publication lists of <2

---

app/assets/stylesheets/dm/components/_gradient_banner.scss
app/views/shared/_breadcrumbs.html.erb

[DM-4072](https://agile6.atlassian.net/jira/software/c/projects/DM/boards/22?modal=detail&selectedIssue=DM-4072)	
- Sets the line height for blue banners to `1.53` across the app. (Note this is a little different from what USWDS offers for [line height utilities](https://designsystem.digital.gov/design-tokens/typesetting/line-height/#line-height-tokens). I'm making the exception here because it's a component defined by the [Diffusion Marketplace internal design system](https://www.figma.com/file/dkvSpADVqwN5KKByF1TVIa/Design-System---VA-DM?type=design&node-id=1305-3&mode=design&t=ln1GK4CrmlhnIYXB-0))

DM-4072: Set blue banner line heights to 1.53

---

app/assets/javascripts/active_admin.js
spec/features/admin/admin_page_spec.rb
spec/features/pages/show_page_spec.rb

https://agile6.atlassian.net/browse/DM-4069
Edits functions to now initialize tinyMCE on only one text input at a time through use of focus event listeners. This should in theory help the page's load time and responsiveness as previously it was being initialized on not only each visible text input but also those for each element's list of elements in the drop-downs that also had text input fields.
Removes un-needed functions involved in initializing tinyMCE on new components and re-initiliazing on components that have been dragged and dropped.
1. create a pb page, add a few components with large text fields such as "Body Text", "Block Quote", or "1:1"
2. Verify that a TinyMCE initializes on a text field only upon clicking in
3. Verify that upon clicking a different text field the previous …

DM-4069 refactor pb edit page js

---

app/admin/pages.rb
app/assets/stylesheets/dm/components/page_component.scss
app/models/page_event_component.rb
app/views/active_admin/resource/_page_event_component_form.html.arb
app/views/page/_events_list.html.erb
db/migrate/20230728213402_add_presented_by_to_page_event_components.rb
db/schema.rb
spec/models/page_event_component_spec.rb

[DM-4073](https://agile6.atlassian.net/browse/DM-4073?atlOrigin=eyJpIjoiOWI0NmU4NDZhMzVjNGEyOTgzZTg5M2IzYTY0NDVhNmEiLCJwIjoiaiJ9)
- Adds a "Presented by" field to the PB Events component
- Adds a validation to reject events with an end date but no start date
- Adjusts whitespace between event title and metadata (and applies this to News and Publication cards too)
- Adds Event component info to the content preview in `/admin/pages/:id`
1. Log in as an admin and create a page group and page
2. Create a new event component with a Title and save. 
3. Add an end date to event component and save. 
4. Edit the component. Event component should not have persisted an end date. 
5. Fill out the rest of the info as expected and save. 
6. Check `/admin/pages/:id` to confirm all component info is …

DM-4073: Add 'Presented by' field to PageBuilder Event components

---

app/assets/javascripts/_header_utilities.es6
app/assets/stylesheets/dm/pages/_partials/_header.scss
app/views/shared/_header.html.erb
spec/features/shared/header_spec.rb
spec/requests/page_controller_spec.rb

[DM-4044](https://agile6.atlassian.net/browse/DM-4044?atlOrigin=eyJpIjoiN2MwYWE4OTdkMjU0NDNkMDlhNzQzNDA3MjBkMDhjZGUiLCJwIjoiaiJ9)
- Swaps "XR Network" for "VA Immersive" pages in navbar dropdown
- Removes "News" and renames "Events" to "Events and News"
- Adds "Getting Started" page to navbar

DM-4044 Swap out XR Network navbar URLs for VA Immersive

---

app/models/page_event_component.rb
spec/models/page_event_component_spec.rb

Part of DM-3780 efforts
- Updates a validation on PageEventComponent that was preventing users from creating new events and causing `paginated_components_spec.rb` to fail locally and in CI. 
1. Log in as an admin and access a PageBuilder page.
2. Add a new event component with no date information
3. Save
Your new component should be saved.

Update Event validation method and unit tests

---

config/environments/production.rb

[DM-4096](https://agile6.atlassian.net/browse/DM-4096?atlOrigin=eyJpIjoiNzI1ODc2NTE0YmYzNGY3MGExMTFmZjU2MTBjMjcyNGEiLCJwIjoiaiJ9)
Set log levels to `info` to make logs less verbose. See [Debugging Rails Applications](https://guides.rubyonrails.org/debugging_rails_applications.html#log-levels) for more info.
1. In config/environments/development.rb, add `config.log_level = :info`.
1. Start your local rails server
1. Compare the output

Set log levels to info

---

app/helpers/application_helper.rb
app/views/practices/form/editors.html.erb
app/views/practices/show/implementation/_resource_link_attachment.html.erb
spec/helpers/application_helper_spec.rb

https://agile6.atlassian.net/browse/DM-4109
Edit external link tags as per codeql security warning "js/unsafe-external-link"
1. Edit a current practice
2. Go to "Editors" tab, click the email link, verify it opens mail client
3. Go to "Implementation" tab, add a resource link
4. View the practice's page, verify the added link opens a new tab to the correct url when clicked

DM-4109 Fix CodeQl security warning "unsafe-external-link"

---

app/views/layouts/application.html.erb

[DM-4110](https://agile6.atlassian.net/browse/DM-4110)
- Removes extra Google Analytics tag that was slowing down page load times
- Simplifies logic for adding the DAP Analytics program snippet
1. Deploy the branch to DEV.
1.  Access a public page (e.g. the homepage) and inspect the markup. You should see ` `. 
1. Go to a page requiring a user account e.g. `/innovations/vha-rapid-naloxone/edit/metrics`. Inspect the markup. You should NOT see ` `.

DM-4110: Remove legacy Google Analytics tag

---

app/views/practices/form/about.html.erb
app/views/practices/form/introduction.html.erb
app/views/practices/form/overview.html.erb
spec/features/practice_editor/introduction/introduction_spec.rb
spec/features/search_spec.rb

[DM-3214](https://agile6.atlassian.net/browse/DM-3214)
- Updates required fields in the Innovation Editor to use asterisks to match the Editing guide

DM-3214: Use asterisks for required field labels in Innovation Editor 

---

app/models/page_component.rb

https://agile6.atlassian.net/browse/DM-4043
* remove "Text and Images" option from components options in PB edit
1. Go to the edit view for a PB page
2. Add new component, verify "Text and Images" is not an option in the dropdown
ifs, Videos from application (if applicable)

remove "Text and Images" option from components options in PB edit

---

app/models/page_component.rb

[DM-4060](https://agile6.atlassian.net/browse/DM-4060)
- Adds section dividers to PageBuilder component selection per designer request
1. Log in as an admin. Create a page group and test page. 
2. Add a new component
3. Select a section divider (e.g. `---Text---`)
4. Save the page. The divider should not have persisted
5. Select a normal component (e.g. `Heading 2`) and add text.
6. Save the page. The component should have persisted.

DM-4060: Add section dividers to PageBuilder component selection

---

.github/workflows/run-tests.yml

Added a new service called selenium that uses the latest stable version of Chrome and ChromeDriver. This service runs in a separate container and provides everything needed to run Chrome-based tests.
Removed Manual Chrome and ChromeDriver Installation: Since the Selenium service provides Chrome and ChromeDriver, we no longer need to manually install them on the runner.
Added a step to check that ChromeDriver is running correctly in the Selenium service. This ensures that everything is set up properly before running the tests.

Add selenium service to gh actions rspec

---

app/helpers/application_helper.rb
spec/helpers/application_helper_spec.rb

adds rescue block to `#is_internal_link?` to sanitize urls with special characters that would otherwise break `URI.parse`
1. for an existing page under the implementation tab add a few resource links
2. make the resource links any text that would break `URI.parse` such as "THIS IS OBVIOUSLY NOT A LINK" or "https://editions.mydigitalpublication.com/publication/?i=645297&p=&pn=#{"issue_id":645297,"publication_id":"60085","page":26}"
3. save and verify the show page renders.

add rescue block to #is_internal_link?

---

app/controllers/home_controller.rb
app/controllers/page_controller.rb
app/controllers/practices_controller.rb
app/controllers/visns_controller.rb
app/views/layouts/application.html.erb

https://agile6.atlassian.net/browse/DM-4111
Adds instance variable created in `show` actions of `PageController` and `PracticesController` to allow or prevent calls for gmaps assets from `application.html.erb`
1. Add a gmap component to an innovation
2. Verify the map component renders when viewing the innovation show page (make sure your `GOOGLE_API_KEY` is present and uncommented in `application.yml`)
3. Check the show page of an existing practice, such as `/innovations/flow3`, verify the map renders.
4. Visit `/diffusion-map` and `/visns` and verify the map renders.
5. To verify calls are not being made for gmaps assets when not needed check a page without a gmap component or go to `/search` and verify in the Network tab that no requests for gmaps are carried out.

add instance variable to allow requests for gmaps assets

---

app/views/layouts/application.html.erb

Adds preload for google font assets fetch in `application.html.erb`
Fonts, especially those from external sources like Google Fonts, can be render-blocking. When a browser encounters a font it needs to load from an external source, it might delay the rendering of the text until that font is loaded, leading to what's often called the "Flash of Invisible Text" (or FOIT). This means users might see blank spaces where text should be until the font is loaded.
By preloading the font, we're giving the browser a hint to fetch this resource earlier in the loading process. Even though the actual time it takes to fully load the page might not change significantly, the perceived performance can improve since crucial text content can be rendered sooner, making the site feel faster to users.
load a few …

Preload google fonts

---

app/views/page/show.html.erb

[DM-4080](https://agile6.atlassian.net/browse/DM-4045?atlOrigin=eyJpIjoiYjE2MzBkY2I2OWQxNDBiNmJkZjlkZTU3MmQxN2IyMTQiLCJwIjoiaiJ9)
Unifies the treatment of whitespace between PageBuilder components! We were getting weird whitespace around the Map, three column text, and call to action components because some also applied whitespace above the component.
See: VA Immersive clone page in DEV (`/communities/va-immersive`)
https://www.figma.com/file/ccwLbt94U9QGfnuFCwOXzY/Core-Designs---VA-DM?type=design&node-id=6181-38719&mode=design&t=fNia1FbnSMlNAlv3-0

DM-4080: Consistently apply about 80px of bottom margin to PageBuilder components

---

app/assets/javascripts/_page_show.es6
app/assets/javascripts/shared/_signed_resource.es6
app/assets/stylesheets/dm/components/_practice_card.scss
app/controllers/application_controller.rb
app/views/practices/_search.js.erb
app/views/shared/_practice_card.html.erb
lib/modules/practice_utils.rb
spec/lib/practice_utils_spec.rb

JIRA issue link
https://agile6.atlassian.net/browse/DM-4136
The main point of these changes is to implement a `placeholder` for practice card images on the search page. 
Previously, there was a redundant image rendering happening in which the initial response for the `/search` page included signed S3 urls that were obtained by the server. Those urls were inserted into the practice cards' html and later on in within the same JS code were replaced by a different signed S2 url that were fetched by the client from the server (which in turn was requesting them from S3).
These changes remove the signed s3 urls from the initial response, render the practice cards with a simple solid color background in the image container, sends fetch requests to the server for the signed urls, and replaces the …

Dm 4136 implement practice card img placeholder

---

app/helpers/application_helper.rb

https://agile6.atlassian.net/browse/DM-4157
edits query in `#origin_display_name`, removes eager loading of `:clinical_resource_hub association`
Verify the search page loads locally as expected, verify the warning does not appear in the dev tools console

dm-4157 remove unnecessary eager loading from #origin_display_name

---

app/models/practice.rb

https://agile6.atlassian.net/browse/DM-4155
Adds eager loading to queries that provide scoped `practices` data from within the `Practice` model's `#cached_json_practices` method.
Verify the search page loads locally as expected, verify the warning does not appear in the dev tools console

DM-4155 edit `#cached_json_practices` method to use eager loading

---

proxy/nginx.conf

Edits nginx.conf file to enable gzip compression
deployed to DEV, currently awaiting reload of Nginx via AWS console..
Once reloaded the response headers from our server should indicate text compression was enabled with `Content-Encoding: gzip`
current response headers (before update):

dm-4140 add text compression to nginx config file

---

app/views/layouts/application.html.erb
app/views/practices/search.html.erb
app/views/shared/_messages.erb

https://agile6.atlassian.net/browse/DM-4123
Adds `defer` attributes to js scripts to prevent blocking initial page render, `defer ` is generally preferred over `async` so that the scripts run in their intended order.
Various pieces of functionality that the deferred scripts enable should be checked:
1. Save and publish button in practice editor works, leave a required field empty to verify the modal that pops up upon clicking the "Save and Publish" button appears, does not flicker, closes.
2. Practice editor header does not flicker.
3. Terms and conditions modal does not flicker, to verify sign in as user with `accepted_terms` set to false, modal closes
4. Crisis line modal works / doesn’t flicker (top right of page)
5. Gmaps appear and markers have aria labels and title (as per …

dm-4123 defer render-blocking js tags

---

app/controllers/va_facilities_controller.rb
app/views/va_facilities/map/_facility_map.html.erb
spec/features/va_facility_spec.rb

Adds `include_google_maps` instance var to `#show` in `VaFacilitiesController` in order to allow rendering of gmaps. 
The requirement for the instance variable was added recently with https://github.com/department-of-veterans-affairs/diffusion-marketplace/pull/679, the inclusion of the variable for this controller action was an oversight due to lack of testing and my own lack of familiarity with the app. Test added for posterity.
run the app locally and verify the map renders under facility show pages.

Add gmaps inst var to facilities show

---

app/models/diffusion_history.rb
db/migrate/20230907210242_add_diffusion_histories_count_to_practices.rb
db/schema.rb
lib/tasks/dm.rake
lib/tasks/update_counters.rake
spec/models/practice_spec.rb

https://agile6.atlassian.net/browse/DM-4156
Adds counter cache column to `practices` to alleviate N+1 query identified by bullet gem (see jira ticket for details)
1. run the pending migration
2. run the rake task: `rake practice:update_diffusion_histories_counts`
3. run the app, login as admin, load the search page, verify expected render / functionality
4. verify the bullet warning no longer appears in the console (see screenshot)
before fix:

dm-4156 add counter cache to practices

---

Gemfile
Gemfile.lock

[DM-4199 ](https://agile6.atlassian.net/browse/DM-4199)/ Part of [DM-3771](https://agile6.atlassian.net/browse/DM-3771)
- Upgrades dependency that was clashing with Rails 6.1 to the last version that supports Rails 6.0
- [release notes](https://github.com/activeadmin/activeadmin/releases?page=1)
- Try out various functions in `/admin`

Update activeadmin to avoid Rails 6.1 clash

---

Gemfile
Gemfile.lock
app/assets/stylesheets/dm_uswds/theme/_uswds-theme-general.scss

Part of [DM-3774](https://agile6.atlassian.net/browse/DM-3771)
- Uses a version of uswds-rails with `bourbon` and `neat` dependencies unpinned in the upstream gem (see [branch](https://github.com/agilesix/uswds-rails/compare/dm-ruby-2.7-uswds-2.11.1...camillevilla:uswds-rails:dm-rails-6-1?expand=1)

Bump up clashing dependencies in uswds-rails

---

Gemfile.lock

Our lockfile's bundler version is a couple of versions behind what we're using in PROD. Bumping up our bundler version after seeing a reminder during deploy.

Bump up bundler version to 2.4.20

---

app/controllers/va_facilities_controller.rb
spec/factories/diffusion_history_statuses.rb

https://agile6.atlassian.net/browse/DM-4241
Various alterations to queries involved in response for `/facilities` endpoint, removes and adds eager loading in a few places as per warnings from bullet gem.
1. As admin go to the `/facilities` page, verify no bullet gem warnings appear in devtools console or in the terminal by keyword searching "Eager" (sometimes warnings will appear in the terminal but not the console).
2. Filter search by facility and then by visn, checking for bullet gem warnings as in previous step.

dm-4241 facilities index bullet warnings

---

app/helpers/application_helper.rb

https://agile6.atlassian.net/browse/DM-4157
I realized that my original fix for this bullet warning wasn't working as I'd thought, the query results were being cached and so subsequent page loads that were absent of the bullet warning were not telling the full truth.
This refactors the `#origin_display_name` method in `ApplicationHelper` to conditionally preload associations, which alleviates the bullet gem warning.
1. Locally, signed in as admin, visting `/search` and verify no bullet gem warning appears in either devtools console or the server output in the terminal (always appears towards the bottom but keyword searching for `Eager` is a good idea to be sure).
2. In rails console run: `Rails.cache.clear`
3. Reload the page and reverify no bullet warnings appear.

dm-4157 refactor #origin_display_name

---

app/helpers/application_helper.rb

https://agile6.atlassian.net/browse/DM-4157
follow up to https://github.com/department-of-veterans-affairs/diffusion-marketplace/pull/720, forgot to add change to `#construct_facility_name` method
I realized that my original fix for this bullet warning wasn't working as I'd thought, the query results were being cached and so subsequent page loads that were absent of the bullet warning were not telling the full truth.
This refactors the `#origin_display_name` method in `ApplicationHelper` to conditionally preload associations, which alleviates the bullet gem warning.
1. Locally, signed in as admin, visting `/search` and verify no bullet gem warning appears in either devtools console or the server output in the terminal (always appears towards the bottom but keyword searching for `Eager` is …

dm-4157 search page bullet warning fix

---

app/assets/javascripts/_page_show.es6
app/assets/javascripts/_practice_card_utilities.es6
app/assets/javascripts/va_facilities/facility_adopted_practice_search.es6
app/assets/javascripts/va_facilities/facility_created_practice_search.es6
app/views/clinical_resource_hubs/_crh_show.js.erb
app/views/page/show.html.erb
app/views/practices/_search.js.erb
app/views/shared/_practice_card.html.erb
app/views/va_facilities/show.html.erb
app/views/visns/_show.js.erb

https://agile6.atlassian.net/browse/DM-4256
The main point of these changes is to make sure that practice card images always start as a background placeholder that is subsequently replaced with the practice card image. This had already been implemented everywhere but for facility and page-builder* show pages, this update adds it for said pages and refactors the involved methods a bit. 
As logged-in admin:
1. Create a page-builder page and add and Innovations component with some innovations, view the page and verify the practice card images load and replace background images
2. Go to a few facility show pages that have created and adopted innovations, verify the same expected practice card image behavior as above.
3. Check for background-replacing practice card images on the practice …

dm-4256 refactor practice card img placeholders for pagebuilder show and facility show

---

app/assets/javascripts/practice_page.es6

[DM-4258](https://agile6.atlassian.net/browse/DM-4258)
- This PR improves the fallback behavior for innovation show pages where image requests fail. Previously, captions would be set to 50px wide columns when S3 image requests failed. This PR adds a conditional so that broken image captions appear at full column width instead. 
As an innovation editor:
1. upload an image that is 50px wide. Give it a caption that is about 190 characters long. 
2. upload an image that is 500px wide. Give it a caption that is about 190 characters long. 
3. Save changes
4. Go to the innovation page
5. Confirm that the 500px wide image caption is as wide as the image
6. Confirm that the narrow image's caption is 450px wide.

DM-4258: Improve fallback behavior for innovation show page images

---

app/views/home/_featured_section.html.erb

[DM-4267](https://agile6.atlassian.net/browse/DM-4267)
- In cases where the homepage image requests for Featured Innovation and Feature Topic breaks: 
- Hides the broken icon
- adds a light grey background to the parent div
1. Log in as an admin 
2. In `/admin/topics` add a topic with an image attachment. Save.
3. In `/admin/topics`, click on `Feature`
4. In `/admin/practices`, select an innovation to Feature. Make sure it's also Public. 
5. In `/admin/practices`, go to Edit, add an image and feature body text
6. On the homepage, confirm you see the images load. 
7. in the browser, edit the `src` of one of the images to something invalid. (e.g. `src="nonsense"`). 
8. The image should immediately change to a light grey placeholder.

Use a grey placeholder if Featured Topic/Innovation images fail

---

app/controllers/system/operational_tasks_controller.rb
config/environments/test.rb
config/routes.rb
spec/requests/operational_tasks_controller_spec.rb

https://agile6.atlassian.net/browse/DM-4281
Adds controller with action with the sole purpose of clearing the `s3_signer` object from the Rails cache. Authorization will be handled by checking a bearer token sent in the authorization header of the request.
1. set a `CLEAR_SIGNER_CACHE_TOKEN` env variable in `application.yml`
2. run the server locally and `redis-server`, load the home page
3. in rails console, run: `Rails.cache.fetch('s3_signer')` and verify it returns a `WT::S3Signer` object
4. from a separate terminal window send a request to the endpoint with:
```
curl -X POST http://localhost:3200/system/clear-signer-cache \
-H "Authorization: Bearer 123456" \
-H "Content-Type: application/json"
```
6. It should respond with `{"status":"Cache cleared successfully"}% `
7. re-run …

dm-4281 clear signer cache endpoint

---

app/views/about/index.html.erb

N/A
The Diffusion of Excellence team recently updated their program website. I noticed this when a test started failing on a [recent PR](https://github.com/department-of-veterans-affairs/diffusion-marketplace/actions/runs/6802885776/job/18496968353):
https://github.com/department-of-veterans-affairs/diffusion-marketplace/blob/51c744850c35d4272add9babf518d2e2564528f5/spec/features/about_spec.rb#L12-L22
1. Go to About Us page on PROD (https://marketplace.va.gov/about)
2. Click on Diffusion of Excellence and confirm the current link leads to a 404 page
3. In local dev, go to `/about` and click on Diffusion of Excellence. 
4. Confirm that it successfully loads the cc
from application (if applicable)

Update Diffusion of Excellence link on About us page

---

app/controllers/application_controller.rb

reverts change to the expiration timing of `s3_signer` object in rails cache, 45 minutes seems to be the ideal time given the token refresh interval appears to be set to 45 min as well:

update `expires_in` for cached s3 signer

---

Gemfile
Gemfile.lock

[DM-4315](https://agile6.atlassian.net/browse/DM-4315)
Updates `jquery-ui-rails` to `7.0.0` per security advice. This Gemfile update points to the repo directly. The maintainer who cut the new release does not have permissions to push the package to Rubygems.org and is waiting for other maintainers to publish.

DM-4315: Upgrade jquery-ui-rails

---

app/views/practices/search.html.erb

edits `javascript_include_tag` in `search.html.erb`, removes deferment and sets `'data-turbolinks-track': 'false'`
nav from home page to search page via the "Browse all innovations" link and verify the practice card images load

Edit practice card util js tag

---

Gemfile
Gemfile.lock
db/schema.rb

- This fixes an error we were getting when running migrations in local dev: https://stackoverflow.com/questions/71006085/paperclip-gem-rails-6-1-migration-error-wrong-number-of-arguments-given-3
- Updates `paperclip` to include additional Ruby 3.2 patches: https://github.com/agilesix/paperclip/compare/ruby-2.7.x-deprecation-fix...agilesix:paperclip:ruby-3-2-patched
1. On `master`, run `rails dm:reset_up` in local dev. Confirm that it fails with the error below:
2. Using this branch, run `rails dm:reset_up` in local dev and confirm that it reaches the end of the data seeding process

Update paperclip to include patched schema method

---

app/views/shared/_email_form.html.erb

DM-4340
- small follow up to DM-4340 to get tests that involve email forms passing. This only affects local dev and testing. 
1. Make sure that `RECAPTCHA_SITE_KEY_V3` is not present in your local `.env` file. 
2. On `master`, start local dev and navigate to `About.`
3. You should receive the error `Recaptcha::RecaptchaError in About#index No site key specified.`
4. Check out this branch. Restart your server and navigate to the `About` page. The form should still render. Check the inspector and confirm that no recaptcha snippet is loaded.

DM-4340: Don't render RECAPTCHA if key isn't available

---

app/views/about/index.html.erb
app/views/shared/_email_form.html.erb
spec/features/about_spec.rb

[DM-4349](https://agile6.atlassian.net/browse/DM-4349)
- Removes the contact form from the "About us" page
- temporarily disables relevant tests until we have confirmation this experiment has been successful
1. Go to the "About page"
1. Confirm that the alert banner with info about getting patient care is still present
1. Confirm that the marketplace contact email is still present

DM-4349: Disable contact form on About page

---

app/views/layouts/application.html.erb

[DM-4346](https://agile6.atlassian.net/browse/DM-4346)
- Disables Google Analytics in DEV and STG
1. Deploy this branch to DEV. 
2. Open the inspector and confirm this is not in the page's `<head>`
```
<script async type="text/javascript" src="https://dap.digitalgov.gov/Universal-Federated-Analytics-Min.js?agency=VA" id="_fed_an_ua_tag"></script>
```
4. Go to STG (with `master` deployed)
5. Open the inspector and confirm the DAP analytics snippet is rendered in `<head>`

Disable Google Analytics in DEV and STG

---

Gemfile
Gemfile.lock

- Minor version updates for `activeadmin`
- Release notes: https://github.com/activeadmin/activeadmin/blob/master/CHANGELOG.md#2140-
- Upstream code diff: https://github.com/activeadmin/activeadmin/compare/v2.12.0...v2.14.0
Note: There are some breaking changes in the major version update. I'll work on this in a separate PR.
- Log in as an admin and confirm that `/admin` functions are still working

Bump activeadmin to 2.14

---

app/controllers/nominate_practices_controller.rb
app/helpers/contact_email_helper.rb
app/views/nominate_a_practice_mailer/nominate_a_practice_email.html.erb
spec/features/nominate_practices/nominate_a_practice_page_spec.rb

[DM-4339](https://agile6.atlassian.net/browse/DM-4339)
- Adds a URL to emails sent via the Nominate form from DEV and STG
- cleans up and reorganizes the related spec
- reflects that public users are able to nominate an innovation
- separate messages involving email messages from render / redirect tests
- Go to `/nominate-an-innovation` in local dev
- Fill out the form fields and send the message
- The email generated by `letter_opener` should say `Sent from http://localhost...` under the message

DM-4339: Add a URL to messages sent from non-PROD forms

---

.github/workflows/run-tests.yml

Address GitHub Actions warning:
```
The following actions uses node12 which is deprecated and will be forced to run on node16: actions/setup-node@v2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
```
- Inspect GitHub Actions output for [an old workflow run](https://github.com/department-of-veterans-affairs/diffusion-marketplace/actions/runs/7294807368?pr=756) and compare it with [one for this PR](https://github.com/department-of-veterans-affairs/diffusion-marketplace/actions/runs/7295213948).

Update node version in GitHub Actions CI

---

db/migrate/20240102214641_fix_versions_item_type.rb
db/schema.rb

https://agile6.atlassian.net/browse/DM-4391
* adds migration to remove "{:null=>false}" column from `versions` table
* changes `item_type` column to be non-null, backfills any existing null `item_type` values with default string
* locally, sign in as admin and verify the filtration options appear as the second screenshot below with the `"{:null=>false}"` filter removed
* verify the `"{:null=>false}"` column is removed from the `versions` table in the db and schema

Dm-4391 fix versions item type column

---

app/helpers/active_admin_helpers.rb

https://agile6.atlassian.net/browse/DM-4389
fixes `bullet` gem warning for N+1 query on `admin/adoptions` page
verify the `admin/adoptions` page loads without the `bullet` warning appearing in the devtools console (should load a bit faster as well)

DM-4389 add eager loading to queries for `admin/adoptions` page

---

app/admin/practices.rb
app/models/practice.rb

https://agile6.atlassian.net/browse/DM-4390
Within the code for the admin/practices page its clear that there was an intended filter for an "owner email" that does not appear on the page. This was likely due to a misunderstanding about there being no `owner_email` attribute on the practices table, a bit of custom code is needed for such a filter to exist.
* adds `scoped_collection` to `admin/practices.rb` (added bonus, the eager loading added here fixes the `bullet` gem N+1 warning for the `admin/practices` page) and edits the `owner_email` filter to be `user_email`
* adds `ransacker` block to `Practice` model to make `user.email` available in `activeadmin` as filter
1. Locally, as admin, create a new practice and assign a user's email as the "user email`, some user email other than the …

DM-4390 add `user_email` as "Owner Email" to admin/practices filters

---

Gemfile.lock

N/A
- bumps `shoulda-matchers` from v5.1.0 to v6.0.0
- Release notes: 
- https://github.com/thoughtbot/shoulda-matchers/releases/tag/v6.0.0
- https://github.com/thoughtbot/shoulda-matchers/releases/tag/v5.3.0
- https://github.com/thoughtbot/shoulda-matchers/releases/tag/v5.2.0
- Diff: https://github.com/thoughtbot/shoulda-matchers/compare/v5.1.0...v6.0.0
- Confirm that CI runs as expected

Bump shoulda-matchers to v6.0.0

---

app/views/shared/_header.html.erb

[DM-4424](https://agile6.atlassian.net/browse/DM-4424)
Adds a link to the VA Immersive Publications page to the nav dropdown.
1. Go to the VA Immersive dropdown and hover over Publications.
2. Check that the relative link directs to `/communities/va-immersive/publications` (Note that you will run into an error if your local dev environment doesn't have the relevant page group and page)

Add Publications page to VA Immersive dropdown

---

app/assets/stylesheets/dm/components/_buttons.scss
app/assets/stylesheets/dm/components/_links.scss
app/assets/stylesheets/dm/pages/_home.scss
app/assets/stylesheets/dm/pages/_partials/_navbar_search.scss
app/assets/stylesheets/dm/pages/_search.scss
app/views/home/index.html.erb

[DM-4417](https://agile6.atlassian.net/browse/DM-4417?atlOrigin=eyJpIjoiOTMzYmEwYmMxZGY3NDMxMjhjMTBkNzI5YzJiYmNiMDYiLCJwIjoiaiJ9)
- Updates search buttons to new darker blue
- Updates Shark Tank banner color and cleans up markup
- Uses a mixin to apply new darker blue color to similar buttons in search (¯\_(ツ)_/¯ just updating `.usa-button` would also affect innovation editor, which is outside of the scope. I'm just focusing on public facing pages for now).
1. Go to homepage and ensure that the welcome banner's background matches both search buttons
1. Go to search and check the following buttons match:
- search in navbar
- search in main page
- "Filters" at responsive width
1. Click on "Filters" dropdown and check that "Update results" button also matches …

DM-4417: Update Home Page for Design Consistency

---

app/controllers/practices_controller.rb

N/A
Addresses a deprecation warning that shows up in CI runs / when you run tests locally. 
```
DEPRECATION WARNING: Rendering actions with '.' in the name is deprecated: practices/form/adoptions_forms/create_or_update_diffusion_history.js.erb (called from block (2 levels) in create_or_update_diffusion_history at /home/runner/work/diffusion-marketplace/diffusion-marketplace/app/controllers/practices_controller.rb:491)
```
1. Log in and navigate to an innovation page
2. Edit your innovation and 
3. Go to the "Adoptions" tab
4. Confirm that you can successfully add and save adoptions
5. Go to the CI run for this PR and confirm the deprecation warning does not appear. 
6. Go to a CI run for a previous build (e.g. latest PR to `master` or `feature/` and confirm the deprecation warning is …

Address rendering deprecation warning

---

app/assets/javascripts/search.es6
spec/features/homepage_spec.rb

https://agile6.atlassian.net/browse/DM-4427
update `setupSearchDropdown` function event functions to recognize keyboard navigation
1. Locally on the homepage, verify you can navigate to the search bar with the tab key
2. Verify the dropdown appears once the search bar is in focus
3. Verify you can use the tab key to navigate through the options in the dropdown and that, when a category or the "browse all" link is in focus, the enter key initiates the page navigation to the search page with the category in place in the filtration dropdown.
4. Back on the homepage, verify that when the dropdown is engaged you can navigate out of the dropdown with the tab key and that once out the dropdown disengages.
5. Re-engage the dropdown and verify you can navigate the options with the up and down …

Dm 4427 update homepage search 1 categories keyboard accessibility

---

app/assets/javascripts/search.es6

[DM-4396](https://agile6.atlassian.net/browse/DM-4396)
- Truncates homepage search dropdown results to the first 3 substring matches. This is a temporary solution until sort-by-popularity #783 is resolved
1. Type `he` into the search bar and confirm that only 3 or fewer results are returned. 
2. On STG or a local copy of `feature/homepage-refresh` type `he` into the search bar and confirm that more than 3 results are returned (i.e. every category with the term "health")

Truncate dropdown results to a simple list of 3

---

app/views/home/index.html.erb

[DM-4435](https://agile6.atlassian.net/browse/DM-4435)
- Updates encoding to ensure categories with ampersands (e.g. `Obstetrics & Gynecology`, `Nutrition & Food`) both 
- render correctly in the dropdown
- are handed off to search
1. If you're testing in local dev, log in as an admin. 
1. In `feature/homepage-refresh`, search for `Obstetrics` or `Nutrition`.
1. Categories with ampersands should render with `u\2006`
1. Select `Nutrition \u2006 Food` and submit search
1. No search results should be returned
1. Reset the filters on /search 
1. Select Nutrition & Food from the filters and Update results
1. You should get 8 results back
1. In `feature/homepage-refresh`, search for `Obstetrics` or `Nutrition`.
1. Categories with ampersands should render the character correctly
1. Select …

DM-4435: Handle categories with ampersands in homepage search dropdown

---

app/assets/javascripts/practice_editor_utilities.es6
spec/features/practice_editor/about_spec.rb

https://agile6.atlassian.net/browse/DM-4402
* adds jquery / js to allow submission of empty innovation cc email value, recognizes empty value specifically for `pe-address-input` class and utilizes `_destroy` param to let backend know to destroy the record
1. Visit the `edit/about` page for an innovation
2. Make sure there is an email address saved for the "Copied (cc’ed) email address" field, if none, add one and save by clicking the  green `Save and update` button at the top right of the page
3. Clear the address from the "Copied (cc’ed) email address" field, save the page
4. Verify the field is now empty.

Dm 4402 fix innovation cc email bug

---

app/assets/javascripts/search.es6
app/assets/stylesheets/dm/pages/_home.scss
app/controllers/home_controller.rb
app/views/home/index.html.erb
app/views/shared/_navbar_search.html.erb
spec/features/homepage_spec.rb

[DM-4431](https://agile6.atlassian.net/browse/DM-4431)
- Adds Innovations to search dropdown
- Only shows public innovation to public users
- Cleans up markup and CSS to make it reusable for additional dropdown sections
- Adds responsive truncation to long result names
- Updates placeholder text [per team feedback](https://agile6.atlassian.net/browse/DM-4431?focusedCommentId=11915)
- Backfills some tests for #786 #779
In local dev:
1. Go to homepage and confirm you only see public innovations
2. Sign in and then return to the homepage
3. You should see 3 innovations, ordered by their `created_at` date
4. Start typing a string like `service`. As you type you should see both Innovations and Categories updating
5. Click on an innovation and confirm that it takes you to the innovation show …

Add innovations to homepage search dropdown

---

app/admin/pages.rb
app/assets/stylesheets/active_admin.scss
app/views/active_admin/resource/_page_accordion_component_form.html.arb
app/views/active_admin/resource/_page_event_component_form.html.arb
app/views/active_admin/resource/_page_header2_component_form.html.arb
app/views/active_admin/resource/_page_header3_component_form.html.arb
app/views/active_admin/resource/_page_image_component_form.html.arb
app/views/active_admin/resource/_page_map_component_form.html.arb
app/views/active_admin/resource/_page_news_component_form.html.arb
app/views/active_admin/resource/_page_one_to_one_image_component_form.html.arb
app/views/active_admin/resource/_page_practice_list_component_form.html.arb
app/views/active_admin/resource/_page_subpage_hyperlink_component_form.html.arb
app/views/active_admin/resource/_page_triple_paragraph_component_form.html.arb
app/views/active_admin/resource/_page_two_to_one_image_component_form.html.arb
app/views/active_admin/resource/_page_you_tube_player_component_form.html.arb

[DM-4439](https://agile6.atlassian.net/browse/DM-4439)
- Adds styling to `required` CSS class so that an asterisk is added automatically
- Increase label text size so that asterisks are actually legible
- Add an explainer for required fields near the submit button
- Adds `required = required` to fields that were missing it and vice versa, removes `required=required` copy pasta from optional fields
Review the fields documentation in [DM-4439](https://agile6.atlassian.net/browse/DM-4439). Confirm that it matches.

DM-4439: Clean up PageBuilder components' required fields

---

app/mailers/practice_editor_mailer.rb
app/services/practice_mailer_service.rb
app/views/practice_editor_mailer/send_batch_email_confirmation.html.erb
spec/features/admin/email_selected_practices_editors_spec.rb
spec/services/practice_mailer_service_spec.rb

Adds a step to the [Innovation batch email feature](https://github.com/department-of-veterans-affairs/diffusion-marketplace/pull/789) to send confirmation email containing batch email recipients, subject / message, and applied scope filters to the admin user that utilized.
same as qa steps for the [most recent pr](https://github.com/department-of-veterans-affairs/diffusion-marketplace/pull/789) for this feature, but verify a confirmation email is sent to the email for the admin account used to send the batch emails:
1. Send a batch email with no filters and verify that a confirmation email is sent to the admin user's email indicating the message has been sent, the confirmation email should contain the original message and subject and indicate that it was sent to the owners and editors of …

Add confirmation email to batch email

---

app/views/admin/practices/_email_preview_modal.html.erb
app/views/practice_editor_mailer/send_batch_email_confirmation.html.erb
app/views/practice_editor_mailer/send_batch_email_to_editor.html.erb

adds language to the bottom of the template body
* Adds language to the bottom of Innovation batch email template
* moves confirmation email specific language, the filters applied and Innovation recipient list, to bottom of template
1. As admin utilize the batch email feature from `admin/practices`
2. Verify the preview modal, the batch emails, and the confirmation emails all contain the new language at the bottom above the footer
Innovation editor email:
Admin confirmation email:

update innovation batch email template

---

app/views/home/index.html.erb

DM-4478
- Updates the homepage banner text for the 2024 Shark Tank competition

Update Shark Tank banner for 2024

---

app/admin/topics.rb
app/controllers/practices_controller.rb
app/models/topic.rb
spec/assets/invalid.jpeg.svg
spec/features/admin/admin_topics_spec.rb

https://agile6.atlassian.net/browse/DM-4371
Edits controller logic for `practices` and `topics` in order to intercept `Paperclip::Errors::NotIdentifiedByImageMagickError` errors and replace with a generic message that does not implicate specific components of our tech stack as per WASA scan warning (see jira ticket)
Note: if you cannot recreate `ImageMagick` errors locally with a corrupted image file this branch needs to be deployed DEV to test.
1. As admin, edit an existing topic, try and add a corrupted image file, verify the form reloads with error message "There was an issue with uploading your image file under the image input field (screenshot 1).
2. Verify that you can load a non-corrupted file as expected.
3. Try and create a new `Topic` with a corrupted image file, verify the form …

Dm 4317 obscure imagemagick error details

---

app/views/practices/form/editors.html.erb
app/views/practices/shared/_practice_editor_header.html.erb
app/views/practices/show/show.html.erb
spec/features/practice_editor/authorization_spec.rb
spec/features/practice_editor/header_and_footer_spec.rb
spec/features/practice_editor/metrics_spec.rb

[DM-4479](https://agile6.atlassian.net/browse/DM-4479)
- Updates order of links in innovation editor navbar
- Points 'Edit innovation' button at the first editing page instead of metrics

DM-4479: Reorder innovation editor navbar & update edit innovation button

---

Gemfile
Gemfile.lock
config/environments/production.rb

https://agile6.atlassian.net/browse/DM-4383
1. bumps `tinymce-rails` minor version from 6.1 to 6.8.3 (latest)
2. adds `terser` gem to replace removed `uglifier` gem
3. updates `production.rb` to implement `:terser` as JS compression tool
1. Run the app locally and click around various places where tinymce editor can be found, verify it works as expected
2. With this branch deployed on DEV repeat step 1 , also take a quick peek at the deployment logs to verify there are no hidden errors I missed.
3. Verify that JS files are being compressed in dev tools on DEV (compare with PROD or STG, they should generally be the same sizes for the various files)

Dm 4383 tinymce rails 6.8.3

---

app/services/practice_mailer_service.rb
app/views/admin/practices/_email_preview_modal.html.erb
app/views/practice_editor_mailer/send_batch_email_to_editor.html.erb
spec/features/admin/email_selected_practices_editors_spec.rb

https://agile6.atlassian.net/browse/DM-4500
Adds `updated_at` dates beside listed practices in batch email template
1. Locally, log in as admin and send a batch email from `admin/practices`
2. Verify the preview modal includes a date next to the example innovation link (screenshot 1)
3. Verify the emails generated include the `updated_at`s next to the respective innovation names listed in the editor / owner emails (screenshot 2)

Dm 4500 add updated date to batch emails

---

app/views/practices/shared/_practice_editor_header.html.erb
spec/features/practice_editor/header_and_footer_spec.rb

[DM-4501](https://agile6.atlassian.net/browse/DM-4501)
- For published innovations: changes the `Save and update` button text to `Save and publish`
- Update specs that look for the `Save and update` button
1. In local dev, log in as an admin.
1. look for a published practice and click on `Edit your innovation`
1. For each of the editor steps (except for `Adoptions`), check that the header button says `Save and publish`
1. Create a new innovation in `/admin/practices` and go to its edit page
1. Confirm that each editor section (except for `Adoptions`) has two header buttons, `Save and draft` and `Save and publish`.
A/C:
1. The 'Save and update' CTA on existing, published pages within the Innovation Editor should be replaced with the 'Save and publish' CTA.
2. Clicking on the 'Save and …

DM-4501: Change 'Save and update' button to 'Save and publish'

---

Gemfile
Gemfile.lock
spec/spec_helper.rb

[DM-4456](https://agile6.atlassian.net/browse/DM-4456)
- Removes the `webdrivers` gem and upgrades `selenium-webdriver`, per the [maintainer's advice](https://github.com/titusfortner/webdrivers#update-future-of-this-project):
> With Google's new [Chrome for Testing](https://developer.chrome.com/blog/chrome-for-testing/) project, and Selenium's new [Selenium Manager](https://www.selenium.dev/documentation/selenium_manager/) feature, what is required of this gem has changed.
If you can update to the latest version of Selenium (4.11+), please do so and stop requiring this gem. Provide feedback or raise issues to [Selenium Project](https://github.com/SeleniumHQ/selenium/issues/new/choose)
If you cannot upgrade to Selenium 4.11, Webdrivers 5.3.0 will continue to support Ruby 2.6+ and Selenium …

DM-4456: Remove webdrivers and upgrade selenium-webdriver

---

app/assets/stylesheets/dm/components/page_component.scss
app/views/page/show.html.erb

https://agile6.atlassian.net/browse/DM-4531
adds custom css class for background color of `page-triple-paragraph-component`
1. Add the `page-triple-paragraph-component` to a page locally, toggle the background color
2. Verify the page renders with the correct color for the component (#f5f5f5)

add custom css class for pb triple paragraph component bg color

---

app/views/home/index.html.erb

adds `URI.encode_www_form_component` call to category name so that properly encoded param is sent in request
verify that when clicking a category in the homepage dropdown, the `/search` page loads with the category pre-selected as a filter

fix homepage dropdown category link param

---

.github/workflows/codeql-analysis.yml
app/assets/javascripts/application.js
app/assets/javascripts/homepage.es6
app/assets/javascripts/search.es6
app/assets/stylesheets/dm/components/_buttons.scss
app/assets/stylesheets/dm/components/_links.scss
app/assets/stylesheets/dm/pages/_home.scss
app/assets/stylesheets/dm/pages/_partials/_navbar_search.scss
app/assets/stylesheets/dm/pages/_search.scss
app/controllers/home_controller.rb
app/helpers/categories_helper.rb
app/views/home/index.html.erb
app/views/practices/_search.js.erb
app/views/shared/_navbar_search.html.erb
spec/factories/ahoy_events.rb
spec/factories/ahoy_visits.rb
spec/factories/categories.rb
spec/features/homepage_spec.rb
spec/features/practice_spec.rb
spec/features/shared/breadcrumbs_spec.rb
spec/helpers/categories_helper_spec.rb
spec/spec_helper.rb

[DM-4077](https://agile6.atlassian.net/browse/DM-4077)
- Adds a dropdown to the homepage that provides autocomplete suggestions from innovations and categories
- Updates visual design of homepage
- Removes "Explore popular categories" section from homepage
1. [Marketplace summary update](https://github.com/department-of-veterans-affairs/diffusion-marketplace/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed#:~:text=DM%2D4398%20update%20homepage%20welcome%20banner%20styling)
1. #770
2. #772
3. #776
4. #778
5. #779
7. #784
8. #786
9. #787
10. #793 
11. #823 
12. #824

Feature: Homepage refresh

---

app/controllers/practices_controller.rb
app/views/practices/form/about.html.erb
app/views/practices/show/contact/_contact.html.erb
app/views/practices/show/show.html.erb
db/migrate/20240320195215_add_private_contact_info_to_practices.rb
db/schema.rb
spec/features/practice_viewer/contact_spec.rb

[DM-4552](https://agile6.atlassian.net/browse/DM-4552)
- Allows innovation editors to hide the `Email` section from public users
1. In `/admin/practices`, choose an innovation and make it public
1. Go to the innovation's edit page
1. Under `About`, add a main contact email address.
1. Go to the innovation page and confirm there is an `Email` section with the listed contact
1. Go back to the editor's `About` section and select `Hide contact info from public users`
1. Go to the innovation page. Confirm there is an `Email` section with the listed contact
1. Log out. Go to the innovation page.
1. Confirm the `Email` section is hidden. Confirm there is no `Email innovation` button in the side navigation.

DM-4552: Allow innovation editors to hide their contact info from public users

---

app/assets/javascripts/_page_show.es6
app/assets/stylesheets/dm/pages/_page_builder_page.scss
app/views/shared/_breadcrumbs.html.erb
spec/features/shared/breadcrumbs_spec.rb

[DM-4509](https://agile6.atlassian.net/browse/DM-4509) / [DM-4527](https://agile6.atlassian.net/browse/DM-4527)
- Adds subnavigation links to the PageBuilder pages that are part of a whitelisted community `PageGroup`.
- Subnav links are hidden in a toggle when in mobile widths
1. In `/admin/page_groups` create a page group named `va-immersive`
1. Create a page and add it to the `va-immersive` community
1. Go to the page and confirm that the hardcoded subpages are rendered
1. Reduce window size to mobile. Confirm that a toggle menu button appears above the page's blue banner. 
1. Open and close the menu
1. check that the rendered link slugs match their title
https://agile6.atlassian.net/browse/DM-4509

DM-4509: Add subnav for VA Immersive community pages

---

app/assets/stylesheets/dm/pages/_home.scss
app/views/home/index.html.erb

https://agile6.atlassian.net/browse/DM-4576
- Updates link styling for Shark Tank Banner
- Default: No underline
- On hover: Underline
- No color change
- Capitalize “Competition”

DM-4576: Update link styling for Shark Tank banner

---

app/views/shared/_header.html.erb
spec/features/shared/breadcrumbs_spec.rb
spec/features/shared/header_spec.rb

[DM-4574](https://agile6.atlassian.net/browse/DM-4574)
- Removes `Partners` page from main nav

DM-4574: Remove Partners page from main nav

---

app/admin/pages.rb
app/assets/stylesheets/active_admin.scss
spec/features/admin/admin_page_spec.rb

[DM-4544](https://agile6.atlassian.net/browse/DM-4544)
- Move `Page Group` above the URL suffix for a more intuitive page creation experience.
- Rename `Page Group` to `Community` and update inline hint guidance

DM-4544: Move the page group to the top of the form and update hints

---

app/assets/stylesheets/dm/pages/_partials/_header.scss

[DM-4607](https://agile6.atlassian.net/browse/DM-4607)
- Dropdowns became misaligned after shipping #832. This PR adjusts the CSS to account for this.

DM-4607: Nudge navbar dropdowns over

---

app/admin/pages.rb
app/models/page_component.rb
spec/factories/page_block_quote_component.rb
spec/features/admin/admin_page_spec.rb
spec/models/page_component_spec.rb

https://agile6.atlassian.net/browse/DM-4469
This fix makes use of the established pattern for validation error handling for submitting a pagebuilder form. Previously, most validation errors relating the `page` or its `components` would fail silently as the user was redirected back to the top level admin show page for the `page` with no indication that their changes were not persisted due.
The main story here is the addition of `validate :custom_component_validation_message` to the `PageComponent` model which drills down into error messages generated by the `component` association, which is necessary to extract the class name of the component in order to deliver a helpful error message, via 2 new helper methods, that indicates the user-facing name of the component and the attribute issue. …

DM-4469 fix pb update silent failure

---

app/admin/pages.rb

adds escape for regex being used in `admin/pages` controller helper method `rewrite_error_message`
1. verify that `diffusion-marketplace/app/admin/pages.rb:296: warning: regular expression has ']' without escape: /(?<=])/` warning does not pop up when running the application locally
2. verify that the PB error messaging introduced with https://github.com/department-of-veterans-affairs/diffusion-marketplace/pull/838 still functions as expected

fix regex for warning in `admin/pages#rewrite_error_message`

---

app/controllers/practices_controller.rb
app/views/practices/show/introduction/_introduction.html.erb
spec/features/practice_editor/introduction/introduction_spec.rb
spec/features/practice_viewer/introduction_spec.rb

[DM-4629](https://agile6.atlassian.net/browse/DM-4629)
- Removes links to major practice partners from innovation show page
- Removes naturalsorter invocation 
- Move db query out of view into controller 
1. Log in as and go to an innovation's edit' page. e.g. `/innovations/flow3`
2. Go to the `Introduction` section and add several partners. 
3. Save the innovation
4. Go to the innovation show page and confirm that partners are sorted alphabetically by `name`.
5. Select `None of the above, or Unsure` from the list.
6. Save the innovation and go to the innovation's show page
7. Confirm that no `Partners` section is visible.
Innovation show page:

DM-4629: Remove links from major partners on innovation show page

---

app/helpers/navigation_helper.rb
app/models/page_group.rb
app/views/page/_community_subnav.html.erb
app/views/page/_community_subnav_mobile.html.erb
app/views/shared/_breadcrumbs.html.erb
app/views/shared/_page_heading_banner.html.erb
spec/factories/page_groups.rb
spec/features/pages/community_spec.rb
spec/features/shared/breadcrumbs_spec.rb

This PR cleans up some code around communities & breadcrumbs
- Removes communities from breadcrumb code (we are not using these in the new Community designs) and updates specs
- Starts extracting partials from the breadcrumbs partial that's used across the app to make things clearer for a later refactor
- Stops hardcoding community name in community mobile subnav
- Adds feature tests for community subnav
- IF the homepage has been published:
- Only render community subnav links for subpages that exist AND have been published
-  ELSE: show all subnav links for subpages that exist
1. Log in as an admin. 
2. Create a page group with the slug "va-immersive". Save. 
3. Go back to edit the page group and update the name to "VA Immersive"
4. Create a page with the slug `home` and set its page …

Clean up code around community subnav and breadcrumbs

---

app/assets/stylesheets/dm/pages/_page_builder_page.scss
app/views/page/_community_subnav.html.erb
app/views/page/_community_subnav_mobile.html.erb
app/views/shared/_breadcrumbs.html.erb

[DM-4553](https://agile6.atlassian.net/browse/DM-4553)
(another PR coming soon)
- Semantically moves community subnav out of blue banner
- Changes subnav background color & link styles
- Updates responsive behavior
In local dev: 
```
FactoryBot.create(:community)
approved_subpages =  { 
"Community": "home",
"About": "about",
"Innovations": "innovations",
"Events and News": "events-and-news",
"Getting Started": "getting-started",
"Publications": "publications"
}
approved_subpages.each {|k,v| FactoryBot.create(:page, title: k, slug: v, is_publi
c: true)}
```
1. Go to `/communities/va-immersive`
2. Confirm that all subnav links are rendered
3. Confirm that subnav is hidden at mobile widths 
4. Click on the "VA Immersive" button and confirm the menu opens …

DM-4553: Extract community subnav and update colors

---

app/admin/editor/pages.rb

https://agile6.atlassian.net/browse/DM-4693
Updates `editor/pages` config:
1. removes redundant `as: "Pages` from main block
2. removes `config.clear_action_items!` - I originally thought that had to be included to remove download buttons
3. removes now-redundant `action_item` button for new page
1. As admin or `page_group` editor visit `/editor`
2. Verify there is a "New Page" button in the top left
3. For a page click "View"
4. Verify there are "Edit Page" and "Delete Page" buttons in the top left

Dm 4693 add edit button to PB editor page

---

app/assets/javascripts/homepage.es6
app/views/home/index.html.erb

https://agile6.atlassian.net/browse/DM-4705
fix event tracking for category selection from home page
changes property key "category-id" to "category_id",  store "category_id" value as int
1. locally from the homepage select a category from the dropdown
2. In rails console check the last event by running `Ahoy::Event.last`
3. the `properties` jsonb hash should include the  selected category's id as `category_id => {int}` where `int` is an integer and not a string.

fix event tracking for category selection from home page

---

app/admin/editor/page_group.rb
app/admin/editor/pages.rb
app/models/editor_auth_adapter.rb
spec/features/admin/admin_page_group_spec.rb
spec/features/editor/editor_page_group_spec.rb
spec/features/editor/editor_page_spec.rb

https://agile6.atlassian.net/browse/DM-4702
* Adds `page_groups` to Community Editor Portal
* Remove delete functionality from `editor/pages`
1. As admin add an editor to an existing `page_group`
2. Log in as that editor and visit `/editor`
3. Verify you can see and access the "Page Groups" tab
4. Verify you can add and delete editors from `page_group`s

Dm 4702 editor page groups

---

app/controllers/application_controller.rb
config/initializers/active_admin.rb
spec/features/admin/admin_spec.rb

https://agile6.atlassian.net/browse/DM-4748
* add redirect_editor_from_admin_dashboard method to ApplicationController, call as before_action for `activeadmin` requests
1. As a user with a `page_group_editor` role, try and access the admin dashboard
2. Verify you are redirected to the Community Editor Portal

dm-4748 redirect editors from admin

---

app/assets/stylesheets/dm/components/page_component.scss

[DM-4744](https://agile6.atlassian.net/browse/DM-4744)
Tweaks the CSS on the news component to set News Component images to a 6:5 ratio instead of a (? 516: 395) ratio
1. Create three news components with titles and descriptions.
2. Upload 3 types of images: 
- portrait (longer than wide)
- square 
- landscape (wider than long)
3. Confirm that when rendered, images are cropped to similar proportions.

Change news component image ratio to 6:5

---

app/helpers/navbar_helper.rb
app/models/page_group.rb
spec/helpers/navbar_helper_spec.rb

https://agile6.atlassian.net/browse/DM-4626
Updates `PageGroup::COMMUNITIES` ordering as per design
Updates `NavbarHelper#assemble_page_group_hash` so that the `page_groups` being returned in the hash are ordered according to `PageGroup::COMMUNITIES`
1. Add the "Age-Friendly", "VA Immersive", and "Suicide Prevention" page groups, make sure to add their home pages
2. Verify they appear in order regardless of their published or public status (if not public they should only appear for logged-in va users and if not published they should only appear for admins or editors of the given `page_group` with " - Preview" added to the link in the "Communities" dropdown)

Dm 4626 reorder communities dropdown

---

app/admin/users.rb
spec/features/admin/admin_spec.rb

https://agile6.atlassian.net/browse/DM-4749
* Adds "Admin" and "PageGroup Editor Roles" to both the csv export and `show` configuration for `admin/users`
1. As admin, add a user to a few `page_group`s
2. Verify that when you "view" a user from the `admin/users` page (`/admin/users/{id})` you see the "PageGroup Editor Roles" row with the names of the `page_group`s the user is an editor for listed
3. Also verify there is an "Admin" role that populates with AA's "yes" or "no" colored boxes indicating the presence of an `:admin` role for the user.
4. Go back to the `admin/users` pages and utilize "Download: CSV" button to the bottom left of the index
5. Verify the output includes 2 columns coinciding with the new rows from step 2, but for the "Admin" value there will populate "TRUE" or …

dm-4749 add user roles to report

---

app/models/practice.rb

https://agile6.atlassian.net/browse/DM-4811
adds 3 new awards to `Practice::PRACTICE_EDITOR_AWARDS_AND_RECOGNITION`
1. Verify the 3 new "Mission Daybreak" awards are selectable in the Innovation editor workflow under the "Introduction" tab
2. Verify that when selected they render under the "AWARDS AND RECOGNITION" section of the given Innovations show page

add Mission Daybreak awards to awards const in Practice model

---

app/views/practices/show/show.html.erb
spec/features/practice_editor/implementation/department_spec.rb

https://agile6.atlassian.net/browse/DM-4810
adds conditional in innovation show view to check for presence of implementation data in order to render section
1. Create or edit an existing practice
2. Leave all fields in the "Implementation" tab of the editor workflow blank
3. Verify the "Implementation" header and side nav tab don't appear in the show view
4. Verify the "Implementation" header and side nav tab do appear for Innovations with any data input in the "Implementation" tab of the editor workflow.
before:
after:

DM-4810: Hide "Implementation" section from innovation#show if no fields are filled out

---

app/controllers/practices_controller.rb
app/services/save_practice_service.rb

https://agile6.atlassian.net/browse/DM-4765
Updates strong params in `PracticesController` to whitelist attrs as per [codeql alert](https://github.com/department-of-veterans-affairs/diffusion-marketplace/security/code-scanning/335) - difficult due to the dynamic nature of the param keys within the nested attributes, the keys need to be dynamic due to the javascript involved with the form for adding and removing fields but rails disallows strong params with integers as keys (even if in string form, if there is only ints in the string as the key it throws out the entirety of that nested attribute, thank you @aurora-a-k-a-lightning for shedding light on this). In order to get around this the keys needed to be updated to include alpha chars.
This touched many pieces of the Innovation editor …

dm-4764 fix mass assignment warning

---

app/controllers/page_controller.rb
app/models/page_event_component.rb
app/views/page/_events_list.html.erb
app/views/page/_news_items_list.html.erb
app/views/page/show.html.erb
spec/features/pages/event_component_spec.rb
spec/features/pages/news_component_spec.rb
spec/features/pages/paginated_components_spec.rb

[DM-4745](https://agile6.atlassian.net/browse/DM-4745)
[DM-4559](https://agile6.atlassian.net/browse/DM-4559)
- Updates News and Events components to use a 3 column layout
- tweak the margin between columns
- Updates specs for event components so that they're easier to rewrite if pagination thresholds change
- Uses some factorybot methods to deal with repetitive fixture creation 
1. Create a page group
1. Create a page
1. Create 7 News components
1. Create 4 Events components
1. Confirm that news components are paginated after 6 
1. Confirm that event components are paginated after 4

DM-4742: Update news and event component layouts to use 3 columns

---

app/models/page_event_component.rb
app/models/page_news_component.rb
app/models/page_publication_component.rb
app/views/page/_events_list.html.erb
app/views/page/_news_items_list.html.erb
app/views/page/_publications_list_cards.html.erb
app/views/page/show.html.erb
spec/features/pages/publication_component_spec.rb

[DM-4742](https://agile6.atlassian.net/browse/DM-4559?focusedCommentId=12037)
- Adjusts component column sizes when fewer than 3 items are provided. This is to provide a graceful fallback for legacy content that used only 2 items.
- Updates publications to use 3 column card layout for 3 or fewer items

DM-4742: Add graceful fallbacks for paginated components with less than 3 items

---

app/models/page_event_component.rb
app/models/page_news_component.rb
app/views/active_admin/resource/_page_event_component_form.html.arb
app/views/active_admin/resource/_page_news_component_form.html.arb
app/views/active_admin/resource/_page_publication_component_form.html.arb
app/views/page/_events_list.html.erb
app/views/page/_news_items_list.html.erb
app/views/page/_publications_list.html.erb
app/views/page/_publications_list_cards.html.erb
app/views/page/show.html.erb
db/migrate/20240517212034_add_url_link_text_to_page_news_components.rb
db/migrate/20240517214134_add_url_link_text_to_page_event_components.rb
db/migrate/20240522201114_add_url_link_text_to_page_publication_component.rb
db/schema.rb
spec/features/pages/event_component_spec.rb
spec/features/pages/news_component_spec.rb
spec/features/pages/publication_component_spec.rb

[DM-4742](https://agile6.atlassian.net/browse/DM-4742)
- Moves links out of Event, News, and Publication component titles
- Adds a field for a link title to components and renders it at the bottom of the component
- If a title is supplied: render the custom link title
- If no title is supplied: render a generic link title (`View Event`, `View News`, `Read publication`)
- Adds an aria label concatenating link title + event / news item title to provide more info to screenreaders
2. Create a page group and page
3. Create an Event Component, a News Component, and a Publication component. Fill out title and any required fields.
4. Provide a URL for each component
5. Save.
6. Confirm that a link is provided for each component with generic text (`View Event`, `View News`, …

DM-4742: Move links out of Event, News, and Publication component titles

---

app/views/page/_two_to_one_image_component.html.erb

- Moves 2:1 Text to Image component link below body text to match PB design patterns

Move 2:1 component link below body text

---

app/views/home/_featured_section.html.erb
spec/features/admin/admin_topics_spec.rb

[DM-4830](https://agile6.atlassian.net/browse/DM-4830)
- Removes `h6` tags for `Featured topic` and `Featured innovation`
- Add an aria-label with concatenated title to avoid vague links for screenreader users
1. Log in as an admin and add a featured innovation and featured topic
1. Open VoiceOver on a Mac.
1. Open the Voiceover menu and the arrow keys to open the Links menu
1. Confirm that the link for each featured item renders both link text and the section title. e.g. `View Innovation: Innovation Title`.

DM-4830: Remove 'Featured topic' and 'Featured innovation' headings

---

app/assets/stylesheets/dm/components/_links.scss
app/assets/stylesheets/dm/pages/_partials/_footer.scss
app/views/home/index.html.erb
app/views/shared/_footer.html.erb
spec/features/homepage_spec.rb

[DM-4830](https://agile6.atlassian.net/browse/DM-4830) and a few items from [DM-4578](https://agile6.atlassian.net/browse/DM-4578)
- add headings to sections of the footer
- adjust font color + hover styles for footer links 
- adds an `aria-describedby` property to describe the lists via their headings
- move the footer into a `grid-container` so that it fits within the page margins
- adjust responsive behavior for tablets
1. Open VoiceOver on a Mac.
1. Open the Voiceover menu and the arrow keys to open the Lists menu
1. Confirm that each of the footer links is described by their heading
1. open the website at desktop width and confirm that the footer links are spread across 4 columns
2. narrow the browser window to tablet width. Confirm that links are now split into 2 rows of 2 columns …

DM-4830: Footer headings and minor style tweaks

---

app/assets/stylesheets/dm/components/_breadcrumbs.scss
app/assets/stylesheets/dm/pages/_facilities.scss
app/views/home/_featured_section.html.erb
app/views/shared/_breadcrumbs.html.erb
app/views/va_facilities/show.html.erb
spec/features/admin/admin_topics_spec.rb

Folllow up to DM-4583 / #886
Unsets SCSS color values and applies USWDS theme link styles to:
- breadcrumb links
- facility phone numbers

Apply usa-link styles to some stray links

---

app/controllers/page_controller.rb
app/models/page_news_component.rb
app/models/page_practice_list_component.rb
app/models/page_publication_component.rb
app/views/page/show.html.erb
spec/features/pages/paginated_components_spec.rb

Some cleanup after #881 / DM-4742
- applies the same pattern used for Events to other paginated components. In the past, we've experienced bugs because component pagination changes were applied in the view but not in the controller. Unifying the pagination threshold in one place eliminates this type of bug from happening in the future

Paginated component cleanup

---

app/assets/stylesheets/dm/pages/_home.scss

- Adjusts homepage image ratio. Taller images make for less weird image crops
https://www.figma.com/design/D16fyBygVx88HpyczTuqXs/Diffusion-Marketplace-(2024)%2B?node-id=1469-853&t=PglSnRrycuWId9J2-1

Adjust aspec ratio for homepage featured topic / innovation images

---

app/views/practices/_search.js.erb
app/views/shared/_practice_card.html.erb

https://agile6.atlassian.net/browse/DM-4865
check the Innovation (practice) cards found on the search page and page-builder pages (with Innovations component present and populated) and verify the bottom appears as seen in the second screenshot below
before:
after:

dm-4865 Remove “Creation Date” from the Innovation Cards

---

app/admin/pages.rb

[DM-4710](https://agile6.atlassian.net/browse/DM-4710)
- Adds a suggested (but not required) image size to the PageBuilder banner image upload

DM-4710: Add a recommended image size to PageBuilder banner image upload

---

app/assets/stylesheets/dm/pages/_partials/_footer.scss
app/views/practices/shared/_practice_editor_footer.html.erb
app/views/shared/_footer.html.erb
spec/features/shared/footer_spec.rb

[DM-4578](https://agile6.atlassian.net/browse/DM-4578)
- Updates styling for the `Return to top` link to make it button-ier
- Changes the public-facing button text to `Back to top`
- Retains a separate style for the innovation editor footer to avoid confusion with `Back` button
1. Open the homepage using dev tools Responsive mode. Set width to a mobile device. 
2. Scroll down to the footer and confirm the new styling + text change is applied 
3. Click on the `Back to top` button and confirm that it brings you to the top of the page

DM-4578: Adjust styling for sitewide footer 'Return to top' button

---

app/assets/stylesheets/dm/pages/_search.scss
app/controllers/practices_controller.rb
app/views/practices/_search.js.erb
app/views/practices/search_partials/_search_filters.html.erb
spec/features/admin/admin_practice_partners_spec.rb
spec/features/search_spec.rb

[DM-4864](https://agile6.atlassian.net/browse/DM-4864)
- Removes Innovation Partners from the search filter UI
1. Go to `/search` 
2. Confirm that `Innovation Partners` are no longer available as a filter option
3. Select multiple filters and update results. 
4. Confirm that the number of filters is reflected in the Accordion title e.g. `Filters (3)`

DM-4864: Remove innovation partners from search filters view

---

app/views/practices/_search.js.erb

DM-4864, rebase after #905 is merged
- Follow up to #905, where we removed `Innovation Partners` from the search interface
- This PR removes code from our main search logic that included Partners
I recommend testing this in DEV, where more complete filter data is available.
1. On `master`, run several searches and note their result numbers: 
- search w/ category
- search w/ adoption facility
- search w/ originating facility 
2. Deploy this branch to DEV
3. Run the same searches and compare search result numbers

DM-4864: Remove partners from main search algorithm

---

app/admin/editor/page_group.rb
app/admin/editor/pages.rb
app/admin/page_group.rb
app/admin/pages.rb
app/assets/javascripts/active_admin.js
app/assets/javascripts/admin/page_group.js
app/assets/stylesheets/active_admin.scss
app/controllers/admin_controller.rb
app/models/page.rb
app/models/page_group.rb
app/views/shared/_breadcrumbs.html.erb
db/migrate/20240516224142_add_position_to_pages.rb
db/migrate/20240528183046_add_short_name_to_pages.rb
db/schema.rb
spec/features/admin/admin_page_group_spec.rb
spec/features/admin/admin_page_spec.rb
spec/features/editor/editor_page_group_spec.rb
spec/features/editor/editor_page_spec.rb
spec/features/pages/community_spec.rb
spec/models/page_spec.rb

https://agile6.atlassian.net/browse/DM-4562
Adds feature allowing management of community pages subnav links
The original goal (see jira ticket) was to remove the hard-coded community page subnav logic and replace it with dynamic logic that would allow for admins and page editors to add and remove links as well as control the text that appears for each page's link.
This ended up being a bit complicated as one of the things needed to be taken into consideration is the ordering of the links. We already had the `acts_as_list` gem as well as the `sortable` jquery library so I implemented a solution that allows for drag-and-drop reordering of the links from the `admin/page_group/edit` view. This solution required a new column, `position`,  to be added to the `pages` table. The column value is …

dm-4562 enable community subnav management

---

app/models/category.rb
spec/models/category_spec.rb

edits so that it returns a hash of parent categories and their subcategories ordered by count of subcategories in ascending order
1. running the app locally, verify that the filters within the dropdown are ordered by count of subcategories in ascending order

Render categories in ascending order by count in search

---

app/admin/editor/pages.rb
app/admin/pages.rb

https://agile6.atlassian.net/browse/DM-4806
add  Is Public column column to admin/pages and editor/pages index
1. As admin visit `/admin/pages` and `editor/pages` and verify the "Is Public" column appears in the grid as per the "After" screenshot below.
Before:
After:

DM-4806 add column to admin/pages and editor/pages index

---

app/admin/pages.rb

https://agile6.atlassian.net/browse/DM-4627
removes un-needed fields from the `admin/pages` index
1. As admin visit the `/admin/pages` page and verify the filters appear as per the "After" screenshot below
Before:
After:

DM-4627 remove un-needed filters from admin/pages

---

app/views/home/index.html.erb
app/views/practices/search.html.erb

https://agile6.atlassian.net/browse/DM-4860
Adds placeholder text in the search field on the `/search` page
1. On the `/search` page verify the placeholder text appears in the search field as per the "After" screenshot below
Before:
After:

DM-4860 add placeholder text to search page search field

---

app/views/page/show.html.erb
spec/features/pages/show_page_spec.rb

https://agile6.atlassian.net/browse/DM-4876
Adds banner to the top of pagebuilder pages when they are unpublished
1. Go to a page that is not published and verify the banner appears below the blue banner

Dm 4876 add unpublished page banner

---

app/admin/categories.rb
app/admin/site_metrics.rb
config/initializers/active_admin.rb
spec/features/admin/admin_categories_spec.rb
spec/features/admin/admin_spec.rb
spec/features/admin/site_metrics_spec.rb
spec/features/practice_spec.rb

https://agile6.atlassian.net/browse/DM-4908
updates landing page for admin access to be `/categories` instead of `/site_metrics`
1. go to `/admin` and verify the `/admin/categories` page renders
2. Verify the subnav link and  title reads "Tags" and that the admin show view for a tag (category) reads "ADMIN / TAGS" in the breadcrumbs - see screenshots
before:
after:

dm-4908 Change admin landing page

---

app/assets/stylesheets/dm/pages/_search.scss
app/views/practices/_search.js.erb
app/views/practices/search.html.erb
spec/features/search_spec.rb

https://agile6.atlassian.net/browse/DM-4910
Updates new search page header section to interpolate query term if present
1. Locally, from the home page enter something into the search bar and click the search button
2. Verify on the `/search` page that the new headers appear above the new search results section and that your search query is interpolated
3. While on the page enter another search and verify that upon submission the new search headers update with the new search query interpolated
5. From the landing page, click the "Search" button with nothing in the input
6. Verify that the `/search` page header displays only the text "Search"
with no search query:
with search query:

Dm 4910 update search page headers

---

app/views/maps/_home_map_filters.html.erb

https://agile6.atlassian.net/browse/DM-4930
Implements simple fragment caching within the `home_map_filters` partial that renders hundreds (on prod) of subsequent 'shared/checkbox' partials. The cache key is the most recent `updated_at` of the `VaFacility` collection, which is automatically invalidated when there is a new most recent `updated_at`.
You can see evidence of the cache working in the terminal output after initially loading the `/diffusion_map` page, the first time will run as it usually does but after that the output will be considerably reduced as hundreds of `Rendered shared/_checkbox.html.erb` will be replaced by `Rendered maps/_home_map_filters.html.erb (Duration: 45.9ms | Allocations: 128471) [cache hit]`
It's unclear if this will help page load times until we test it out …

dm-4930 add fragment caching to home_map_filters partial

---

app/assets/stylesheets/dm/pages/_home.scss

[DM-4965](https://agile6.atlassian.net/browse/DM-4965)
- Fixes a bug where homepage search results were overflowing the dropdown container
- Update CSS to make sure that ellipses truncation is applied to homepage search results
1. Update a fixture practice to have a very long title
2. Search for your practice on the homepage
3. Confirm that the practice title is truncated with ellipses

DM-4965: fix ellipses truncation on homepage search

---

app/helpers/va_employees_helper.rb
db/migrate/20240716000712_change_va_employees.rb
db/schema.rb

[DM-4968](https://agile6.atlassian.net/browse/DM-4968) (see ticket for info on data analysis)
- VaEmployee is used for the About section to list members of the original innovation team. We do not collect data via the UI for the fields being dropped.

DM-4968:  Remove legacy data from VaEmployee

---

app/controllers/home_controller.rb

follow up to added caching in `HomeController#fetch_va_facilities`, removes redundant cache call for `va_facilities`
1. You can confirm that this results in the same data by running the following in local rails console:
```
x = VaFacility.cached_va_facilities.get_relevant_attributes.order_by_state_and_station_name
y = VaFacility.where(hidden: false).get_relevant_attributes.order_by_state_and_station_name
x == y
```

update diffusion map query

---

app/views/practices/search.html.erb
app/views/practices/search_partials/_search_filters.html.erb
app/views/shared/_search_sort_select_section.html.erb
spec/features/homepage_spec.rb
spec/features/practice_viewer/introduction_spec.rb
spec/features/search_spec.rb
spec/features/shared/header_spec.rb
spec/features/users/recommended_for_you_spec.rb

Part of DM-4866 / #921
- Comment out placeholder HTML to get tests working
- Remove "Reset filters" button and point tests at the new "Clear filters" button in header
- Update a test to reflect new string behavior for `Results` (e.g. previously, when we had zero results on a page we didn't use `Result` anywhere on the page. Now we show `0 Results`.)

Get test suite working for feature branch

---

config/routes.rb

[DM-5004](https://agile6.atlassian.net/browse/DM-5004)
- Sets up a permanent redirect for a renamed innovation. This should help with any instances of the old URL showing up in search engine results.
On DEV, visit `/innovations/save-a-trip-to-primary-care-tool` and confirm that it redirects to `/innovations/patient-facing-materials-for-care-coordination-in-va-primary-care`

DM-5004: Set up a courtesy redirect for renamed innovation

---

README.md
app/admin/practices.rb
app/controllers/home_controller.rb
app/controllers/practices_controller.rb
app/models/practice.rb
config/routes.rb
db/migrate/20240726002037_remove_highlight_from_practices.rb
db/schema.rb
lib/tasks/dm.rake
lib/tasks/importer.rake
spec/features/admin/admin_spec.rb
spec/features/favorite_spec.rb
spec/features/practice_spec.rb
spec/features/retire_practice_spec.rb
spec/features/shared/breadcrumbs_spec.rb
spec/features/users/user_profile_spec.rb

Part of [DM-4894](https://agile6.atlassian.net/browse/DM-4894) / #956 
Rebase after #958
We are moving towards a less record-centric content management system for homepage content. This PR drops the notion of featured innovations. Many of the fields dropped refer to "highlight". An earlier version of the VADM homepage differentiated between featured practices and a single highlighted practice. 
- Visit the `/admin/practices` panel and confirm that a practice can no longer be featured

DM-4894: Remove featured practices workflow

---

app/models/practice_editor.rb
db/seeds.rb
lib/tasks/categories.rake
lib/tasks/dm.rake

https://agile6.atlassian.net/browse/DM-4940
1. Adds "Communities" parent category with 4 sub-categories to seeds file
2. Adds `categories:add_communities_cats` rake task that associates 3 innovations with each Community sub category
3. Adds `categories:add_communities_cats` to sequentially called tasks within the `dm:full_import` task
4. Updates `PracticeEditor#create_and_invite` method to send invite emails only when not in development environment (QOL improvement so that when running the `dm:full_import` task it won't open a new browser window for each simulated email notification as users are associated with innovations, not necessarily needed)
1. Reset your db with `rails db:{drop,create,migrate}`
2. Run the `dm:full_import` task
3. Verify that emails are not generated and rendered in …

Dm 4940 add community tags to seeds

---

app/assets/javascripts/va_facilities/map.es6
app/assets/javascripts/visns/maps.es6

https://agile6.atlassian.net/browse/DM-4992
As per bug ticket the navbar dropdown content was not loading on facilities and visns pages..
Turns out the issue was gmaps loading scripts left over from the previous implementation strategy that has since been updated as per https://github.com/department-of-veterans-affairs/diffusion-marketplace/commit/cb1742581d94a45eb6e8c31f7f15d8d81494f96a in which the loading has been updated to be async and centralized in the `application.html.erb` file.
Verify the navbar dropdown content and gmap loads as expected for facility and visn show pages (you may need to add valid communities via `active_admin`)

dm-4992 remove gmap load scripts from facilities and visns js

---

app/views/practices/search_partials/_search_filters.html.erb
app/views/practices/search_partials/_visn_facility_combo_box.html.erb

[DM-5904](https://agile6.atlassian.net/browse/DM-5094)
1. Updates the combobox partial so that the `<label>` accurately reflects what it's for
2. Remove the `Search by VISN or facility` span per Figma design, as well as the link to the VISN definition
1. Go to `/search` and open VoiceOver screenreader
4. Open the [VoiceOver form controls menu ](https://support.apple.com/guide/voiceover/general-commands-cpvokys01/mac)
5. Confirm that the combobox form labels now begin with differentiating info e.g. "Originating Location..."

DM-5904: Fix up screenreader accessibility on Originating / Adoption location comboboxes

---

app/controllers/practices_controller.rb
db/migrate/20240819002628_remove_more_fields_from_practices.rb
db/schema.rb
lib/tasks/importer.rake
spec/features/practice_spec.rb
spec/tasks/importer_spec.rb

[DM-5103](https://agile6.atlassian.net/browse/DM-5103)
More of DM-4056 / #968
Drops more retired fields from the DB. 
1. Run the importer workflow (``dm:reset_up`) and confirm that it runs successfully.

DM-5103: Clean up Practice model

---

app/assets/javascripts/va_facilities/facility_adopted_practice_search.es6
app/assets/javascripts/va_facilities/facility_created_practice_search.es6
app/views/clinical_resource_hubs/_crh_show.js.erb
app/views/practices/_search.js.erb
app/views/visns/_show.js.erb

N/A
- Removes legacy custom events that were created when VADM had its own Google Analytics events. 
- DAP does not allow us to register custom events
- this syntax is from a previous version of GA that is not forward compatible
- GA4 automatically collects data on search terms that appear in the URL via query params ([Read more: view_search_results](https://support.google.com/analytics/answer/9234069))
1. Log in to DAP Google Analytics
2. Go to `Reports > Life Cycle > Engagement > Events` and confirm that the list of events collected does not match the name of any of the events removed in this PR.

Remove legacy custom Google Analytics events

---

app/controllers/nominate_practices_controller.rb
app/views/home/index.html.erb
app/views/shared/_email_form.html.erb
spec/features/nominate_practices/nominate_a_practice_page_spec.rb

https://agile6.atlassian.net/browse/DM-5102
changes `NominatePracticesController#email` endpoint to check reCAPTCHA score only if `current_user` is not present, meaning guest users will be subjected to reCAPTCHA evaluation
lowers reCAPTCHA tolerance at `NominatePracticesController#email` endpoint to 0.3 and adds logging for submissions coming in below threshold for the score
Note: I chose 0.3 as the three because I was seeing that as the typical score when testing submissions on DEV from gfe
Locally, submit the form at `/nominate-an-innovation` and verify it succeeds as expected, repeat on DEV

dm-5904 fix innovation submission form reCAPTCHA tolerance

---

app/models/practice.rb

Follow-up to #987
- Restores the ability to supply alt text for a Practice's main display image
- Removes the other call to `#main_display_image_alt_text` that was interfering with the importer workflow
1. Go to a practice
2. Add an large image as a practice's main display image. 
3. Add alt text to the image and save. 
4. Confirm that the text was saved and edit it a few times.

Restore alt text to Practice main display image

---

app/models/va_facility.rb

https://agile6.atlassian.net/browse/DM-5113
As of the recent facilities update that occurred on 7/19, some facilities have nils for address values which now causes a breakage in a [helper method utilized in the visn show view](https://github.com/department-of-veterans-affairs/diffusion-marketplace/blob/8a834834d42812e86fdd7f594e0a74833978ca97/app/helpers/application_helper.rb#L183)
Simple fix is to update `VaFacility#get_locations` to remove nils from return value.
Locally, go to `/visns/23` and verify the page loads

dm-5113 update VaFacility#get_locations to remove nils from return

---

app/views/practices/_search.js.erb

https://agile6.atlassian.net/browse/DM-5116
updates search js to disable / enable and check / uncheck "most relevant" sort option depending on presence of search params
1. Locally on the search page with no search query and no filters submitted, verify that the "most relevant" sort option is disabled and the "most adoptions" sort option is selected.
2. Submit a search with a query and verify the "most relevant" option is enabled and checked, repeat with any filter and verify the same.
3. From the homepage search dropdown, verify that selecting a category or entering a search takes you to the search page with the "most relevant" option enabled and selected.

dm-5116 disable top sort on empty search

---

app/assets/stylesheets/dm/pages/_search.scss
app/views/practices/_search.js.erb
app/views/practices/search.html.erb
app/views/practices/search_partials/_search_filters.html.erb
spec/features/search_spec.rb

https://agile6.atlassian.net/browse/DM-5118
update search filters copy: changed header, sort options, submit button, clear filters button, applied filter copy (to use fa "x" icon)
1. Locally, verify expected keyboard accessibility for the applied filter icons - should be a single focusable element that is removed when triggered with the space or enter key.

dm-5118 search refresh copy changes

---

app/assets/stylesheets/dm/components/_search_result.scss

[DM-5119](https://agile6.atlassian.net/browse/DM-5119)
- Updates styling for search results to account for longer-than-usual taglines

DM-5119: tweak text truncation

---

app/admin/homepage.rb
app/models/homepage.rb
app/models/homepage_feature.rb

N/A. Follow up to #1002 
- When a homepage is published via the ActiveAdmin UI, any other unpublished homepages are unpublished. This PR moves this logic out of the ActiveAdmin action definition and into a callback on the `Homepage` model. This should result in more predictable behavior when we publish next month's homepage via automation. 
- Adds URL validation to homepage features
1. Create several homepages in `/admin/homepages`
2. Publish a homepage
3. Update an unpublished homepage via the rails console, e.g. `Homepage.find(2).update(published: true)`. 
4. Confirm that the previous homepage is now unpublished in both the UI and the DB. 
1. Edit a homepage
2. Add 2 new features
3. Provide an invalid URL for one feature, e.g. `asd;lkfjaw;fijawe;ofiv`
4. Provide a relative link to a …

Homepage CMS: Move publishing workflow to model; add URL validation

---

app/admin/homepage.rb
app/controllers/home_controller.rb
app/helpers/application_helper.rb
app/views/home/index.html.erb
config/routes.rb
spec/features/admin/admin_homepage_spec.rb

[DM-5129](https://agile6.atlassian.net/browse/DM-5129)
- Adds a "Preview" link to homepages admin index and show pages. This preview largely reuses the `home#index` action but sets DB pulls related to activerecord to nil. 
1. Go to `/admin/homepages` 
2. create a new homepage and save with empty content. 
3. Click `Preview` and confirm the hardcoded content is gone. 
4. go back and edit your homepage and add some content. 
5. Click `Preview` and confirm your content is rendered.

DM-5129: Homepage preview

---

app/assets/stylesheets/dm/components/_buttons.scss

Part of [DM-5117](https://agile6.atlassian.net/browse/DM-5117)
- Updates several "unstyled" button styles so they're more link-ish. Remove dark background that they received via inheritance from `.usa-button`.
1. Go to `/innovations/vha-rapid-naloxone/edit/implementation`
2. In the `Risks and Mitigations` section, hover over `Add Another` link. Confirm that no background color is applied
3. Hover over the `Delete entry` link. Confirm that no background color is applied
4. On the same practice editor page, hover over the `Return to Top` link in the footer. Confirm that no background color is applied

DM-5117: Remove dark background from 'unstyled' buttons

---

app/admin/products.rb
app/controllers/products_controller.rb
app/views/products/form/description.html.erb
config/routes.rb
db/schema.rb
spec/features/product_editor/description_spec.rb

https://agile6.atlassian.net/browse/DM-5077
adds first page & endpoint for `Product` editor
1. locally with products loaded via `:full_import` task go to `/admin/products/12` and click the "Edit Url" link
2. verify you can update the various fields and you see a success flash upon clicking the submit button, note: the "Submit" button will be replaced with a "Save and Continue" button in a footer that is being built and that the page will redirect to the next editor page once built, for now it just re-renders the "Description" form)
3. Verify that required fields will prevent form submission when left blank with an indicator under the field
4. Verify that when submitting with a "Innovation Title*" that duplicates another "product"'s name the change does not persist and the page re-renders …

dm-5077 product editor description

---

spec/factories/products.rb

DM-5069
- Add PracticeMultimedia to Products factory to verify behavior 
1. Open the rails console and run `FactoryBot.create(:product, :with_multimedia)`
2. Confirm that `Product.last.practice_multimedia` returns a video, a file, a link, and an image.

DM-5069: Add PracticeMultimedia to Products factory

---

app/admin/products.rb
app/controllers/products_controller.rb
app/models/product.rb
db/migrate/20240918010354_add_slug_to_products.rb
db/schema.rb

[DM-5069](https://agile6.atlassian.net/browse/DM-5069)
- Adds FriendlyID to Products so that they have nice URLs
1. On a previous commit, look at a Product in the rails console and confirm it has no `slug` property. 
2. Check out this branch and run the migrations. 
3. Run `Product.find_each(&:save)`.
4. Confirm that all products now have a slug based off their `name`. e.g. `thermal-fuse-cover`

DM-5069: Add FriendlyID slugs to products for pretty URLs

---

app/admin/products.rb
app/assets/stylesheets/dm/pages/_products.scss
app/controllers/products_controller.rb
app/helpers/navigation_helper.rb
app/views/products/_product_status_banner.html.erb
app/views/products/show.html.erb
config/routes.rb
spec/features/product_viewer_spec.rb

[DM-5198](https://agile6.atlassian.net/browse/DM-5198)
- Set up routes for product show page
- Do simple authorization checks for whether the page is published
- Render provided text-based data
- Render provided videos, images, and links (Files TBD)
1. As an admin go to `/admin/products` and create a new product
2. Go to the admin show page and confirm that the URL is using a sluggified version of the product name e.g. `/products/thermal-fuse-cover`.
3. Visit the product's show page at `/products/thermal-fuse-cover`. 
4. Confirm that provided data is rendered. 
5. Confirm that fields with missing data do not have a heading rendered
6. Log out. 
7. Access `/products/thermal-fuse-cover` as a public user. 
8. Confirm that you are redirected to the home page.

DM-5198: Set up routing and basic templates for Product pages

---

.github/workflows/run-tests.yml

[DM-4333](https://agile6.atlassian.net/browse/DM-4333)
Bumps up our GitHub Actions CI Postgres version to match our Docker image & AWS RDS

Bump GitHub Actions CI PostgreSQL version to 12

---

Gemfile
Gemfile.lock

N/A, related to #1043 
- Moves a gem that we only use for development workflows into the development group

Unpin mechanize gem & move to development group

---

app/controllers/application_controller.rb
app/views/shared/_header.html.erb
spec/features/shared/header_spec.rb

[DM-5242](https://agile6.atlassian.net/browse/DM-5242)
- Temporarily use hardcoding for Communities dropdown links to improve site performance. 
- Access the site as a public user and confirm the relevant communities are rendered in the dropdown

Temporarily disable Communities dropdown preview for admins

---

app/assets/stylesheets/dm/components/_tags.scss
app/assets/stylesheets/dm/pages/_products.scss
app/controllers/practices_controller.rb
app/controllers/products_controller.rb
app/models/category.rb
app/views/practices/show/desktop_partials/_search_terms.html.erb
app/views/practices/show/search_terms/_category.html.erb
app/views/products/show.html.erb
spec/factories/category_practices.rb
spec/factories/products.rb
spec/features/practice_viewer/introduction_spec.rb
spec/features/product_viewer_spec.rb

[DM-5220](https://agile6.atlassian.net/browse/DM-5220)
- Adds a siderail to the Product show page
- Create a class for the customized USWDS `Tags` used on the show pages to make it clearer these are modded components
- Utilize existing practice page JS for see more / see less logic and showing the Tags section in different parts of the page. (Note: I've left this in the same file for now. I'll decide if all the functions can be in a shared partial after I've finished [DM-5069 for updating the in page nav](https://agile6.atlassian.net/browse/DM-5081))
- Move `Partners` further up the page in response to client feedback / updated show page designs
1. Go to `/admin/products/` and choose a product to edit
2. Go to the product's description page and add 11 tags to it.
3. Go to the product's …

DM-5220: Add siderail with Tags to Product page

---

app/admin/adoptions.rb
app/admin/homepage.rb
app/admin/innovation_search_terms.rb
app/admin/site_metrics.rb
config/initializers/active_admin.rb
spec/features/admin/admin_adoptions_spec.rb
spec/features/admin/admin_spec.rb

https://agile6.atlassian.net/browse/DM-5249
- Remove admin menu items that are not being used / need to be refactored
- Disable ActiveAdmin comments feature (this is not the same as the `commontator` comments)
1. In PROD, review each of the removed menu items 
2. In local, review this branch and confirm the removed items are still accessible at their URL `e.g. `/admin/adoptions`)

DM-5249: Update admin menu items

---

spec/features/shared/header_spec.rb

N/A
Cleans up CI by disabling a test. This feature was disabled to improve performance in #1055

Clean up specs from disabled Communities navbar preview

---

app/models/homepage.rb

N/A
- Add PaperTrail versioning to Homepages 
1. Log in as an admin user
2. Go to `/admin/homepages`
3. Create a homepage
4.  edit the page's internal title and save
5. In another terminal, open the rails console and check the `Homepage` responds to `versions` and records a user ID for `whodunnit`. 
```
rails console
Homepage.last.versions
```

Add versioning to Homepages

---

app/assets/stylesheets/dm/components/_buttons.scss
app/assets/stylesheets/dm/pages/_home.scss

N/A
- Update the styling of the `Subscribe` button to deal with some visual regressions after style consolidation

Update subscribe button styling

---

app/assets/javascripts/practice_page.es6
app/assets/stylesheets/dm/components/_sidenav.scss
app/assets/stylesheets/dm/pages/_products.scss
app/views/practices/show/about/_about.html.erb
app/views/practices/show/contact/_contact.html.erb
app/views/practices/show/mobile_partials/_search_terms.html.erb
app/views/practices/show/show.html.erb
app/views/products/form/description.html.erb
app/views/products/show.html.erb
spec/factories/practice_partners.rb
spec/factories/products.rb
spec/features/product_viewer_spec.rb

[DM-5081](https://agile6.atlassian.net/browse/DM-5081)
- Add an in-page nav to the Product page side rails
- Update render logic for Vendors so that `Vendors` header is not rendered if Vendor name is missing (e.g. if a link is present by Vendor name is not)
- Add Partners to factories and show page spec
- Add Price to factories and show page spec
1. Go to a product show page, e.g. `/products/thermal-fuse-cover`
2. Click on each sidenav link 
3. Confirm that your browser's URL is updated to show the section's ID (e.g. `#intrapreneur`)
4. Confirm the window scrolls to the appropriate heading
5. Scroll up and down the show page. Confirm that the sidenav's "current" style changes as you scroll. e.g. You should see "Order Product" highlighted when you have scrolled towards the bottom of the …

DM-5081: In-page sidenav and other Product page tweaks

---

app/assets/stylesheets/dm/pages/_products.scss
app/controllers/products_controller.rb
app/models/product.rb
app/services/save_product_service.rb
app/views/practices/introduction_forms/_image_editor.html.erb
app/views/practices/show/overview/_overview_sections.html.erb
app/views/products/_main_display_image.html.erb
app/views/products/form/description.html.erb
db/migrate/20241010210000_add_main_display_image_caption_to_products.rb
db/schema.rb
spec/factories/products.rb
spec/features/product_editor/description_spec.rb
spec/features/product_viewer_spec.rb

https://agile6.atlassian.net/browse/DM-5201
* Adds `:main_display_image_caption` col to `products` table
* Adds text field for `:main_display_image_alt_text` and `:main_display_image_caption` to `/editor/description` page in product editor workflow
* Also re-adds `data-model-type` value to top-level div in `image_editor` partial that was mistakenly removed in rebase of last branch merged into feature branch (needed for making the image handling js work)
1. go `/products/thermal-fuse-cover/edit/description` and verify you can add text to the caption and alt-text fields
2. go back to the previous page and verify you can switch out the "Thumbnail" image with a different image and verify the change persists upon form submission.
3. go to the "Introduction" page of the innovation editor for a …

dm-5201 prod editor mdi alt text field

---

app/assets/javascripts/homepage_search_dropdown.es6
app/assets/stylesheets/dm/pages/_home.scss
app/controllers/home_controller.rb
app/views/home/index.html.erb
spec/features/homepage_spec.rb

[DM-5254](https://agile6.atlassian.net/browse/DM-5074)
- Adds published Products to homepage dropdown search
- Adds Ahoy tracking events products and `Browse all Products` link 
- Note: `Browse all` links to IPM PageBuilder page for MVP
- Move Products above Tags in dropdown
- Only show 2 items per type in dropdown. Updates spec expectations to account for this
1. Run the `rake dm:reset_up` task to make sure Products are in your DB
2. In the rails console, run `Product.all.update(published: true) to publish products
3. Create a page group and page for the incoming IPM pagebuilder page `pg = FactoryBot.create(:page_group, name: "Intrapreneurial Product Marketplace"); FactoryBot.create(:page, page_group: pg, title: "Intrapreneurial Product Marketplace")`
4. Log in as an admin
5. Place …

DM-5254: Add Products to homepage search dropdown

---

config/routes.rb

N/A
- Removes courtesy redirect now that the agreed upon timeframe has expired
- Remove routes for controller actions that no longer exist
- Search the codebase and confirm that `planning_checklist` and `view_toolkit` are no longer in use

Remove outdated redirects

---

app/controllers/users_controller.rb
app/views/users/edit_profile.html.erb
db/migrate/20241030205550_add_columns_to_users.rb
db/schema.rb
spec/features/users/user_profile_spec.rb

https://agile6.atlassian.net/browse/DM-5091
adds public-bio specific fields to user profile edit page, fields are only accessible to users with `granted_public_profile: true`
1. Update a user with `granted_public_profile: true` either via console or through active admin
2. sign in as that user and go to http://localhost:3200/edit-profile
3. fill out the new fields and verify the data persists upon form submission.
4. log in as a different user with `granted_public_profile: false`, go to the profile edit page and verify the public-bio fields do not appear

dm-5091 fellow profile edit fields

---

app/assets/javascripts/_user_profile_utilities.es6
app/assets/stylesheets/dm/components/_profile.scss
app/views/users/edit_profile.html.erb
spec/features/users/user_profile_spec.rb

https://agile6.atlassian.net/browse/DM-5091
Adds user avatar management functionality to user profile edit page for users with `granted_public_bio: true`
1. Sign in as a user with `granted_public_bio` set to `true` and go to the profile edit page `/edit-profile`
2. verify you can add, change, and delete an avatar image.
3. verify the avatar appears on the profile show page `/users/{id}`
4. update the user by setting `granted_public_bio: false`
5. reload the profile edit page and verify the avatar management ui is no longer visible

dm-5091 add avatar management to user profile edit page

---

app/models/user.rb
spec/models/user_spec.rb

[DM-5300](https://agile6.atlassian.net/browse/DM-5300)
- In the Page Group editors workflow, treat `test@va.gov` the same as `Test@va.gov`
1. In `master`, go to `/admin/page_groups` and create a new page group without editors
2. Edit the page group and try to add `Demo@va.gov` as a user. 
3. You should see an error that the user does not exist
4. Go to `/admin/users` and confirm that a user with email `demo@va.gov` exists
5. Check out this branch 
6. Repeat the workflow and confirm that you are able to add `Demo@va.gov` as a user
7. Confirm that the saved email is downcase and appears in the UI as `demo@va.gov`

DM-5300: Make page group editor emails case insensitive

---

app/admin/categories.rb
app/assets/stylesheets/dm/pages/_practice.scss
app/controllers/practices_controller.rb
app/controllers/products_controller.rb
app/models/category.rb
app/views/practices/form/introduction.html.erb
app/views/practices/introduction_forms/_category_checkbox.html.erb
spec/features/practice_editor/introduction/introduction_spec.rb
spec/models/category_spec.rb

[DM-5224](https://agile6.atlassian.net/browse/DM-5224)
- Changes behavior for "Community" category checkboxes to remediate a bug
- show Community category checkboxes to non-admin editors but disable them
- See bug reproduction steps in JIRA ticket
1.  Log in as an admin and apply a community tag to an innovation. 
2. For the same innovation, add a non-admin user as an editor (e.g. `demo@va.gov`). 
3. Log out. Log in as `demo@va.gov`. 
4. Go to the innovation's edit page. 
5. Confirm that the community tags are rendered as disabled. 
6. Add / remove non-community tags. 
7. Save the innovation.

DM-5224: Show disabled Community category checkboxes for non-admin editors

---

Gemfile
Gemfile.lock

Addresses various warnings re: gems that will not bundled with Ruby 3.4 that are used by activesupport.
```
.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-6.1.7.9/lib/active_support/dependencies.rb:299: warning: .rbenv/versions/3.3.6/lib/ruby/3.3.0/mutex_m.rb was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.4.0.
You can add mutex_m to your Gemfile or gemspec to silence this warning.
```
[mutex_m](https://github.com/ruby/mutex_m)
[drb](https://github.com/ruby/drb)
[observer](https://github.com/ruby/observer)
[base64](https://github.com/ruby/base64)
[bigdecimal](https://github.com/ruby/bigdecimal)
These can likely be removed after upgrading to Rails 7, where they will be included in activesupport …

Address Ruby 3.4 gem warnings

---

app/controllers/users_controller.rb
app/views/users/edit_profile.html.erb
db/migrate/20241030205550_add_columns_to_users.rb
db/schema.rb
spec/features/users/user_profile_spec.rb

https://agile6.atlassian.net/browse/DM-5331
adds `:accolades` col to `users` table and field to profile edit form for management
1. drop local db and run the import task to update the schema with the new users table col
2. Locally, set a user to `granted_public_bio: true`
3. sign in as that user, go to `/edit-profile`
4. update the "Honors, degress (Public Bio)" field, verify the change persists

add :accolades col to users table

---

lib/tasks/va_facilities.rake

https://agile6.atlassian.net/browse/DM-5183
updates `va_facilities:create_or_update_va_facilities` task to skip facility data that is missing a street address
1. go into the source file for `va_facility` import (`/lib/assets/va_facilities.json`, copy one of the objects, and paste into the list a few times with unique "Official Station Name"s, "Station Number"s, and empty strings for the "Street Address"es
2. run the `va_facilities:create_or_update_va_facilities` task and verify there is a message indicating the objects you added were found to have empty "Street Address"es and that they were not persisted to the db as `va_facility` records.

dm-5115 update facility importer to skip no address data

---

app/models/user.rb
app/views/users/_side_nav.html.erb
app/views/users/edit_profile.html.erb
spec/features/users/user_bio_page_spec.rb
spec/features/users/user_profile_spec.rb

https://agile6.atlassian.net/browse/DM-5337
Adds link to user's bio page from edit profile page
1. Log in as a user with `granted_public_bio: false` and nav to `/edit-profile`
2. verify there is no link to a bio page for the user in the left nav
3. in rails console update the user to `granted_public_bio: true`
4. refresh the edit profile page and verify there is now a link to the user's bio page in the left nav
5. click the link, verify you are navd to the bio page and that the url contains the alt-names for the user if present, if not present it should default to the user's normal name (see screenshot)

dm-5337 link edit profile page to bio page

---

app/views/about/index.html.erb
app/views/practices/show/introduction/_introduction.html.erb
app/views/practices/show/show.html.erb
spec/features/practice_viewer/contact_spec.rb

[DM-5028](https://agile6.atlassian.net/browse/DM-5028)
[DM-5029](https://agile6.atlassian.net/browse/DM-5029)
- Change 'Email Innovation' CTA button to 'Contact Team'
- Update references to button in FAQs
- Move "last updated" string above practice title

DM-5028: Change 'Email Innovation' CTA button to 'Contact Team'

---

app/assets/javascripts/_user_profile_utilities.es6
app/controllers/users_controller.rb
app/models/user.rb
app/views/users/bio.html.erb
app/views/users/edit_profile.html.erb
db/migrate/20241030205550_add_columns_to_users.rb
db/schema.rb
spec/features/users/user_bio_page_spec.rb
spec/features/users/user_profile_spec.rb
spec/models/user_spec.rb

https://agile6.atlassian.net/browse/DM-5338
Adds logic and updates views to allow for management and display of users' `work` entries as hyperlinks
1. update a user to `granted_public_bio: true`, nav to `/edit-profile`
2. add text and valid url to the empty fields in the "Work" section, verify they persist upon form submission
3. verify you can add another by clicking the "Add Another Work Link" button, wherein a blank set of fields appear and the "Add Another Work Link" button moves to be below the empty fields.
4. Verify that added links persist, and that links removed with the "Remove" button persist as being removed.
5. Verify that when you remove all links a blank set of fields appears and that the data persists as expected when the form is submitted.
6. Verify that a work entry with …

update users migration to make :work col json

---

app/controllers/practices_controller.rb
app/views/practices/form/introduction.html.erb

https://agile6.atlassian.net/browse/DM-4877
update introduction partial to escape html-sensitive chars for originData js var in order to satisfy codeql warning for [stored xss vulnerability](https://github.com/department-of-veterans-affairs/diffusion-marketplace/security/code-scanning/1)
go to the `/introduction` page of the of the innovation editor and verify the "Originating Location*" selection functions as expected

dm-4877 xss warning fix innovation editor intro page

---

app/admin/users.rb

[DM-5347](https://agile6.atlassian.net/browse/DM-5347)
- Adds a link to users' public bio page from the admin interface so that admins can easily review content
1. As an admin, grant a user a public bio page
2. Go to that user's show page on `/admin/users`. 
3. Confirm that a link is available 
4. Go to a user that has NOT been granted a public bio page
5. Confirm that `No` is rendered next to `Granted Public Bio`

DM-5347: Add a link to public bio pages from admin interface

---

app/assets/stylesheets/dm/components/_profile.scss
app/views/users/show.html.erb
spec/features/users/user_profile_spec.rb

[DM-5349](https://agile6.atlassian.net/browse/DM-5349)
Change edit profile button from icon to button to make the editor more accessible to users granted public bios

DM-5349: Change edit profile button from icon to button

---

app/assets/javascripts/practice_editor_utilities.es6

https://agile6.atlassian.net/browse/DM-4880
in JS containing file upload logic for the "Implementation" tab of the innovation editor - adds lodash function `escape` to ensure safe encoding of chars rendered to html as filename to prevent xss vulnerability
go to the "Implementation" tab of the innovation editor and verify files can be uploaded as resource attachments and that the ui behaves as expected

dm-4880 XSS vulnerability fix 2

---

app/admin/users.rb
app/controllers/users_controller.rb
app/views/users/bio.html.erb
app/views/users/edit_profile.html.erb
app/views/users/show.html.erb
config/routes.rb
spec/features/users/user_bio_page_spec.rb
spec/features/users/user_profile_spec.rb

s### JIRA issue link
https://agile6.atlassian.net/browse/DM-5348
Adds routing for admin access to users' profile edit pages.
Adds link from user public bio pages to edit user profile page that appears when the logged in user is the given bio page user OR current user is admin

dm-5348 admin access to user profile edit pages

---

app/views/commontator/comments/_show.html.erb

https://agile6.atlassian.net/browse/DM-4878
updates comment report submission confirmation link to use path helper which ensure safe parameter handling in order to satisfy codeql warning for [stored xss vulnerability](https://github.com/department-of-veterans-affairs/diffusion-marketplace/security/code-scanning/1)
1. leave a comment on the show page for an innovation
2. sign in as another user and click the red flag to submit a report for the comment
3. verify that the report submits upon clicking the confirmation button (sends email with report)

dm-4878 xss warning fix innovation show page

---

app/assets/javascripts/practice_page.es6

https://agile6.atlassian.net/browse/DM-4881
updates innovation show page js function setMoreLessHTML to properly escape potentially harmful chars to prevent xss vulnerability 
On an innovation show page leave a long comment, verify that once persisted the comment text properly paginates with the "See more" / "See less" buttons.

dm-4881 dom text reinterpret / xss codeql warning 3

---

Gemfile
Gemfile.lock

https://agile6.atlassian.net/browse/DM-5360

Add sprockets-rails gem

---

app/controllers/page_resources_controller.rb
app/controllers/practice_resources_controller.rb
app/controllers/product_multimedia_controller.rb

DM-5378
- Explicitly allow redirects to S3 buckets containing innovation page attachments
To reproduce bug:
1. Go to an innovation show page with an uploaded file attachment (e.g. `VHA Rapid Naloxone`)
2. Click on the file link
3. Confirm that an error is produced in local dev
To test fix:
1. Go to an innovation show page with an uploaded file attachment (e.g. `VHA Rapid Naloxone`)
2. Click on the file link
3. Confirm that you are redirected to the file's s3 bucket link

DM-5378: allow download redirects to s3 bucket

---

app/controllers/practices_controller.rb

Fixes bug in which a query for `PracticePartnerPractice`s did not specify `innovable_type` and so the return included all with an `innovable_id` that matched the given innovation's id, which could also include those belonging to a `Product` with the same id. 
Basically, if a `Practice` with the id of 1 had a `practice_partner` that is also associated with a `Product` with id 1, that `practice_partner` would appear twice as selections on the given `Practice`'s "Introduction" page and would also be included in the params from the form submission and cause an error in the `SavePracticeService`.
This is not an issue in the `Product` editor workflow, where the query for `PracticePartnerPractice`s are properly scoped.
Tested on DEV (currently deployed) by deploying fix and verifying that the …

bug fix: innovation editor "Introduction" page

---

app/mailers/comment_mailer.rb
app/views/practices/form/adoptions_forms/_existing_adoption_warning.html.erb

DM-5379
- Remove defunct support email from application

Remove vendor support email

---

app/models/diffusion_history.rb
proxy/nginx.conf

updates nginx config with increased values for buffer size and body size
adds eager loading to `DiffusionHistory:by_status` scope to alleviate N+1 query identified by the bullet gem on the "adoptions" page of the innovation editor
Tested locally and on DEV

adoptions page fix
